### ISSUE TITLE
Allow switching keyboard layout

### ISSUE THREAD

**Issue by mneumann** [trueos/lumina#149]
Would be nice to have a simple way to switch keyboard layout between preconfigured entries (e.g. from EN to DE). At the moment I have a ```setxkbmap de``` call in my ```.xinitrc```. Being able to set this in lumina-config would be more elegant, especially for beginners.

**Comment by beanpole135** [comment]
I agree that this is a good idea. 
Offhand I think it might be better to use the XCB keyboard support classes instead of setxkbmap, but that is something that needs to be evaluated when I start working on this.

**Comment by mneumann** [comment]
:+1:

**Comment by yurkis** [comment]
https://github.com/pcbsd/pcbsd/tree/master/src-qt5/pc-syskeyboard
May be better than nothing for start. But I think you should remove some PC-BSD specific code.

**Comment by sk8harddiefast** [comment]
I believe also that is a great idea and a "must" for a modern DE.

For now i change layout using this lines on **_.xinitrc_** (You need to install _**setxkbmap**_ first)

```
setxkbmap -layout 'us,gr' -option "grp:alt_shift_toggle"
setxkbmap -option terminate:ctrl_alt_bksp
```

**Comment by kmoore134** [comment]
+1 yea, we should have some layout switcher somewhere in the DE

**Comment by beanpole135** [comment]
FYI: The Fcitx utility is pre-installed on TrueOS systems now, and is specifically designed for this type of keyboard/locale switching from within a desktop session (another utility similar to this is IBUS).

This should work for now, although we will re-evaluate how *embedded* we want this functionality within the desktop itself at a later date.

**Comment by utrenkner** [comment]
Short update: The problem exists also in Lumina 1.1.0p1
