### ISSUE TITLE
(Feature) Font weight selection

### ISSUE THREAD

**Issue by rbns** [trueos/lumina#191]
Change the font-selector for the desktop theme settings to include the font style (light,italic,bold,etc.).

For example the Roboto font ships in several weights ([Google Fonts Roboto](https://www.google.com/fonts/specimen/Roboto)) where the "light" variant looks best on my screen, but "normal" is selected as default.

**Comment by q5sys** [comment]
We're going to have to inquire with the QT devs about this.  As of right now the internal QFont class isnt reading any of the extra weights.  I know it's been a while since you filed this ticket, but we haven't forgotten about it. I'll investigate.

**Comment by q5sys** [comment]
I've gotten nowhere with the qt devs on this.  It's still on my list though. I'll keep hammering away on it as I get time.

**Comment by beanpole135** [comment]
Done.
The new lumina theme engine is used for this now, and that provides all the various font weights/options.
