### ISSUE TITLE
lumina-fm (insight): Unable to move files between smb shares

### ISSUE THREAD

**Issue by abelbabel** [trueos/lumina#198]
I run lumina on a FreeBSD amd64 10.2 machine.
When I move files between two smb shares on the same server (running FreeNAS by the way) mounted by `mount_smbfs`, insight starts copying the files, but fails at the end (probably when it tries to remove the source files?).

Edit: the same operation works when choosing a different file manager.

**Comment by beanpole135** [comment]
Please re-test this on the newer lumina-fm update. A significant amount has changed in the backend, and it might already be fixed.

**Comment by q5sys** [comment]
We've had multiple comments from people who have been able to do this since this ticket was created.  If you are still having this issue, please let us know so we can look into it further.
