### ISSUE TITLE
feature request: automatically resize windows when dragging them to certain regions

### ISSUE THREAD

**Issue by abelbabel** [trueos/lumina#203]
It would be nice to have a feature like it exists on MATE or Windows. For example: When dragging a window to the upper right corner, it automatically will be resized to consume the right half of the screen; same with the upper left corner. If it gets dragged to the upper border of the screen, it automatically will be maximized.

**Comment by baitisj** [comment]
This is a crucial feature for me.

**Comment by abelbabel** [comment]
Yesterday, I saw that KDE has this feature, too.

**Comment by beanpole135** [comment]
Yes, that is a WM feature which fluxbox is lacking. 
I do plan on having something like that in the new lumina-wm as well.

**Comment by mike-pt** [comment]
Just bumped into this... as a workaround for now, I just "pkill" fluxbox and then use fluxbox -rc .lumina/fluxbox-int to have fluxbox start as it would from lumina's start and it brings windows decorations back...

Seems to happen more with terminal emulators btw, as I see this mostly with "Sakura" or "gnome-terminal" (not xterm though)

**Comment by q5sys** [comment]
I'm going to close this, since it's an old ticket and we're already working on the code to implement this.
