### ISSUE TITLE
Crash completely out of X on OpenBSD 6.0-current with 0.88 (latest in ports)

### ISSUE THREAD

**Issue by bceverly** [trueos/lumina#233]
Hi,

I'm running Lumina as my daily driver now (thank you so much for such a functional, BSD-licensed and lightweight DE!!) but I have a bit of a problem I'm happy to help track down.  Here are my steps to reproduce:

1.  Click on start menu
2.  Click on "browse applications"
3.  Select a category (any category will do)

You are now kicked completely out of X and back to either your console (if you are a startx kind of person) or your graphical login prompt (if you prefer those).

If someone can nudge the n00b in the right direction of what logfiles or corefiles would be helpful in tracking this down, I'd be more than happy to do the legwork.

Thanks again.

**Comment by JoshDW19** [comment]
Hey bceverly!  You need to rebuild from source.  That's an old bug we fixed a while ago.  It'd be even better if you can get the openBSD lumina port maintainer to update the port.  We're just about on 0.9.1.  That will be a lot less intrusive if they just update the port.
