### ISSUE TITLE
All pages on website "not found"

### ISSUE THREAD

**Issue by crutchcorn** [trueos/lumina#236]
This excludes the index website. Should be fixed. Was interested about the icon thing as I'm a designer, but am unable to read now. ;)

**Comment by rmgrimm** [comment]
I came here to report the same thing. What I'm seeing is that everything except the homepage is not found when pulling over HTTPS. When pulling over HTTP, things are available:

This doesn't work: https://lumina-desktop.org/features/
This works: http://lumina-desktop.org/features/

**Comment by beanpole135** [comment]
This should be fixed now.
Thanks for reporting it!
