### ISSUE TITLE
top/bottom bars missing

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/lumina#237]
![no-launcher](https://cloud.githubusercontent.com/assets/1111743/16643611/0d193d46-43cb-11e6-9485-b2d500e0018d.png)

As you see in the attached picture, there's no top or bottom launcher. Why? What happened to it and how can I get it back?

This is on DragonflyBSD current from a few days ago and Lumina master.

**Comment by beanpole135** [comment]
See issue #238 - looks like the wrong binary used to launch the desktop.
