### ISSUE TITLE
can't move windows

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/lumina#238]
![no-launcher](https://cloud.githubusercontent.com/assets/1111743/16643655/8843c22a-43cb-11e6-9fbe-3d61ba33a7ae.png)

I cannot move the desktop settings window from its current position to anywhere else on the screen. The same happens for any application I open up.

dragonflyBSD current from a few days ago and lumina master.

**Comment by beanpole135** [comment]
That looks like Fluxbox is not running and/or you used the old binary for launching Lumina  (so all the config files you need do not exist).

You should now be using the "start-lumina-desktop" binary to startup Lumina (*not* "Lumina-DE" - that is the old binary which might still be installed if you recompiled from master sources on top of an existing Dragonfly package for Lumina)

**Comment by jungle-boogie** [comment]
HI @beanpole135,

You're right, my old startx had this:

```
% cat .xinitrc
exec Lumina-DE
```

However, using `start-lumina-desktop` results in the same behavior where I can't move any windows and there's no top/bottom bars. I did a quick ps and fluxbox was running.

Do I need to delete any configuration files that existed before? If so, which files? I didn't have any customization when this was working.

Thanks!

**Comment by beanpole135** [comment]
Make sure you rebuild Lumina from source. The Fluxbox process startup routine was just moved out of the lumina-desktop binary and into the start-lumina-desktop binary. You might have build from source right when I was making the move... :-)

**Comment by jungle-boogie** [comment]
> Make sure you rebuild Lumina from source

I just brought it up to master without any problems. If you make anymore commits between now and when I get home, I'll rebuild again.

So I don't need to delete any config files to have a fresh start---just rebuild from source?

I do this:
```
cd bin/lumina
git pull
/usr/local/lib/qt5/bin/qmake lumina.pro
make
make install
make distclean
```

Thanks a million for quickly responding!

**Comment by jungle-boogie** [comment]
![what-now](https://cloud.githubusercontent.com/assets/1111743/16677289/faab4abe-4488-11e6-9951-cf5cffbf18ff.png)

As you see, I'm on the latest commit and there's still no top/bottom bar. I'm also not able to move windows around.

**Comment by beanpole135** [comment]
Strange... 
Try removing your "~/.lumina" and "~/.config/lumina-desktop" directories, then logout/login. That will force Lumina to re-build all your settings from the luminDesktop.conf installed on your system.

**Comment by jungle-boogie** [comment]
Those directories have been removed.

I needed to restart the computer twice as the first time the terminal application didn't have a menu bar, but upon logging into `start-lumina-desktop` again, the top/bottom menu bars are absent.

Is there some way I can delete all of lumina, install and start it up again to see if anything changed?

Also, I'll start lumina as a different user to see if there's a different behavior.

**Comment by jungle-boogie** [comment]
> Also, I'll start lumina as a different user to see if there's a different behavior.

I can't `start-lumina-desktop` as a different user but I can run startxfce4 as that user.

**Comment by jungle-boogie** [comment]
Any updates/advice?

I realize if I reimage the machine and install lumina from source, this may not be an issue anymore, but that's something rather drastic that would take some time.

**Comment by Mrt134** [comment]
I just wanted to let you know Ken (Beanpole) is out of the office and will take a look when he gets back.

**Comment by beanpole135** [comment]
Sorry - was on vacation all last week... :-)

Ok, I have a couple things I want to check with you:
Within your checked-out/cloned copy of the Lumina source tree, run these commands and let me know what the output is (run `git pull` and `make distclean` first just to ensure everything is up to date and clean as well):

1. `git status -v`
2. `git remote -v`
3. `cd src-qt5 ; /usr/local/lib/qt5/bin/qmake`

That should be the majority of the pre-build information, now go ahead and run the build and save the output to a file which you can attach here as well so I can just verify that everything was building/installing into the proper places:
`make > lumina_build.log`

I might have a couple more things for you to check after I see those logs, but one step at a time... :-)

**Comment by beanpole135** [comment]
Ah - I think I may have found the issue as well - give it a few minutes before you pull down the new sources (the fluxbox config files might not be getting saved into the user's dir properly).

**Comment by beanpole135** [comment]
Ok, I think I found/fixed the problem - try it now:

https://github.com/trueos/lumina/commit/9459a002e0450e2fe4ee77b52f31d37c78399c62

**Comment by jungle-boogie** [comment]
Hi Ken!

Welcome back from vacation.

I'll `git pull && make distclean` now and all the regular stuff on bringing it up to the latest and check it out when I'm in front of the machine.

I'll update this entry with the build log.

**Comment by jungle-boogie** [comment]
The updates from the 18th of July didn't resolve anything, so I re-installed the OS and I'm in the process of bringing my environment back up.

**Comment by jungle-boogie** [comment]
Once all the dependencies are installed, can I run `start-lumina-desktop` or do I need to first launch into something else?

**Comment by beanpole135** [comment]
You should be able to just run "start-lumina-desktop" from the CLI after logging in. That will try to detect if X is currently running, and wrap itself within an "xinit" call as needed.

**Comment by jungle-boogie** [comment]
So if X is not running, start-lumina will start it up and load the DE/WM? Okay, I'll take a picture of the error when I try that.

**Comment by jungle-boogie** [comment]
I have an older openbsd laptop with master lumina running, I must first `startx` and then `start-lumina-desktop` but I am taken to a lumina-DE with a menu bar or two.

**Comment by jungle-boogie** [comment]
![img_8291](https://cloud.githubusercontent.com/assets/1111743/17106189/539dedca-523f-11e6-943c-417502683e31.JPG)

After updating my dfly system, I see the message above when attempting to start lumina.

**Comment by beanpole135** [comment]
That looks like graphics driver issues (did it get updated on DragonFly to a broken version?).

**Comment by jungle-boogie** [comment]
http://lists.dragonflybsd.org/pipermail/users/2016-July/312961.html

I should be able to `start-lumina-desktop` or do I need something in the xinitrc file?

**Comment by beanpole135** [comment]
You should not need anything else, but that has also not been tested very rigorously on various OS's. 
Basically, start-lumina-desktop simply looks for the X environment variables to see if an X session is already running, and re-starts itself with `xinit <path-to-binary>/start-lumina-desktop` if a running X session was not detected[1].

Maybe try running the `xinit <path-to>/start-lumina-desktop` command manually and see if that works?

[1] https://github.com/trueos/lumina/blob/master/src-qt5/core/lumina-session/main.cpp
Lines 34-38

**Comment by beanpole135** [comment]
Oh, another thing to try if that still does not work is to look at the contents of ~/.config/lumina-desktop/logs/runtime.log (if it even got far enough to start logging the startup routine).

**Comment by jungle-boogie** [comment]
[runtime.txt](https://github.com/trueos/lumina/files/387668/runtime.txt)

Pretty unhelpful log ^

w.r.t `xinit /usr/local/bin/start-lumina-desktop`, I get a core dump about half a second after it looks like it will load some gui.

I don't have any debugging enabled in the build so the bt is pretty useless.  Sadly, I don't have any other hardware to try dragonfly on to see what happens.

**Comment by beanpole135** [comment]
Ah - looks like the Qt/DBUS bug which I reported upstream to Qt a while back[1].
You need to startup a dbus session before launching any Qt app (even Lumina), otherwise Qt will crash (unless you built Qt without DBUS support - which most people never do)
Run this instead:
"dbus-launch --exit-with-session start-lumina-desktop"

**Comment by jungle-boogie** [comment]
> "dbus-launch --exit-with-session start-lumina-desktop"

I'll give that a go!

**Comment by jungle-boogie** [comment]
Your command to start the DE did work!! However, the same issue as before: I don't have top/bottom menu bars nor and I able to move windows around.

**Comment by beanpole135** [comment]
I wonder... What does your /usr/local/etc/luminaDesktop.conf file look like?
It might be that you have an old config file which did not make the transition to the newer syntax very well or has disabled most of the interface by default.

**Comment by jungle-boogie** [comment]
> /usr/local/etc/luminaDesktop.conf

Don't have that file but I have /usr/local/etc/luminaDesktop.conf.dist

would you like to see its contents?

**Comment by beanpole135** [comment]
I don't need to see the whole thing, just the `desktop_*` and `panel*` sections.

**Comment by jungle-boogie** [comment]
Here you are! Keep in mind that I re-installed dragonflyBSD and started everything from a fresh start.

```
#DESKTOP SETTINGS (used for the primary screen in multi-screen setups)
desktop_visiblepanels=2 #[0 - 12] The number of panels visible by default
#desktop.backgroundfiles= #list of absolute file paths for image files (disable for Lumina default)
desktop_backgroundrotateminutes=5 #[positive integer] number of minutes between background rotations (if multiple files)
desktop_plugins=rssreader #list of plugins to be shown on the desktop by default
desktop_generate_icons=true #[true/false] Auto-generate launchers for ~/Desktop items 
```

```
#PANEL SETTINGS (preface with panel1.<setting> or panel2.<setting>, depending on the number of panels you have visible by default)
panel1_location=bottom #[top/bottom/left/right] Screen edge the panel should be on
panel1_pixelsize=3.5%H #number of pixels wide/high the panel should be (or <number>%[W/H] for a percentage of the screen width/height)
panel1_autohide=false #[true/false] Have the panel become visible on mouse-over
panel1_plugins=systemstart, taskmanager-nogroups, spacer, systemtray, clock, battery #list of plugins for the panel
panel1_pinlocation=center #[left/center/right] Note:[left/right] corresponds to [top/bottom] for vertical panels
panel1_edgepercent=99 #[1->100] percentage of the screen edge to use

panel2_location=top
panel2_pixelsize=3%H
panel2_autohide=true
panel2_plugins=spacer, desktopbar, spacer
panel2_pinlocation=center
panel2_edgepercent=10 
```

**Comment by beanpole135** [comment]
That looks like the standard settings, so that looks like another dead-end.

I think I am on the last two other things to check and then I am out of ideas...
1) Run `xrandr -q` to look at your monitor configuration settings
2) Look at the contents of ~/.config/lumina-desktop/desktopsettings.conf to ensure that you *do* have panels defined for your desktop.

**Comment by jungle-boogie** [comment]
Regarding 2, I have this below. I'll rung xrandr later today.


```
[desktop-0]
background\minutesToChange=5
generateDesktopIcons=true
panels=2
pluginlist=rssreader

[menu]
itemlist=terminal, filemanager, applications, line, settings

[panel0.0]
color="rgba(255,255,255,160)"
customColor=false
height=26
hidepanel=false
lengthPercent=99
location=bottom
pinLocation=center
pluginlist=systemstart, taskmanager-nogroups, spacer, systemtray, clock, battery

[panel0.1]
color="rgba(255,255,255,160)"
customColor=false
height=23
hidepanel=true
lengthPercent=10
location=top
pinLocation=center
pluginlist=spacer, desktopbar, spacer

[panel0.2]
color="rgba(255,255,255,160)"
customColor=false
height=30
hidepanel=false
lengthPercent=100
location=left
pinLocation=center
pluginlist=@Invalid()
```

**Comment by beanpole135** [comment]
Yeah, those desktop settings look right for the luminaDesktop.conf.dist file snippets you showed.

**Comment by jungle-boogie** [comment]
What's this tell you?

![xrandr](https://cloud.githubusercontent.com/assets/1111743/17596225/49aaec64-5fa5-11e6-9882-83b7779dd32c.png)

**Comment by beanpole135** [comment]
well, that shoots down one of the last ideas I had about the possible problem.... You only have a single monitor enabled - so it is not a "mirrored" monitor covering the real one....

Just for kicks, if you run "xprop" and click on the background wallpaper: what does the "_NET_WM_STATE(ATOM) =" line look like?
You should have 3 properties set: _NET_WM_STATE_STICKY, _NET_WM_STATE_BELOW, and _NET_WM_STATE_SKIP_TASKBAR

The "BELOW" flag is the crucial one in this case - that ensures the background *stays* in the background and all the other windows stay above it.

**Comment by jungle-boogie** [comment]
Sorry for the long response on my part.

When I run xprop, I do see `: _NET_WM_STATE_STICKY, _NET_WM_STATE_BELOW, and _NET_WM_STATE_SKIP_TASKBAR`.

I'll occasionally update to the latest master and check to see if the anything looks different.

**Comment by tuxillo** [comment]
Hi,

Got a similar problem here. I can move the windows but I can't resize them. I have noticed this in mate-terminal, xterm o even kate. On the other hand, I can resize the Insight window just fine since there is a small mark on the right bottom part of its window which allows resizing. Am I missing anything?

Let me know if you want to discuss this one on a new issue.

This is Lumina 1.0.0-Release on DragonFlyBSD installed via dports.

Best regards,
Antonio Huete

**Comment by beanpole135** [comment]
@tuxillo : Fluxbox should put small "handles" on the bottom left/right corners of the window for resizing the window (depending on which Fluxbox theme you are using, those handles could be small or missing).
You can also resize a window by holding down "Alt + Right-Mouse-Button" and moving your mouse around.

**Comment by tuxillo** [comment]
Many thanks, the Alt + Right mouse button trick worked. Although the handle is not there.
