### ISSUE TITLE
Monitor Configuration (dual) not saved between logins

### ISSUE THREAD

**Issue by bdklahn** [trueos/lumina#242]
Lumina 0.9.0-Release
PC-BSD 10.3-RELEASE-p5 amd64 GENERIC on an Optiplex-9010 with twin Dell P2312H monitors

Right click on desktop -> Preferences -> Display gives "Monitor Configuration" dialog.
Initially the Add Screen tab is active, and allows "Enable Screen" to add the second available monitor to the right of the other one. "Apply Settings" allows expected behavior: mouse pointer can move off on screen, and over to the other monitor.

If I log out, then log back in, the original duplicated display configuration returns. Should there be a "Save Changes" button at the bottom of this dialog, as there is with the "Lumina Settings" one (Preferences -> Desktop)? It seems l recall having to explicitly push a save button somewhere, when I did that in KDE, also. What was/is the config file that button on the front-end modifies?

**Comment by beanpole135** [comment]
This is most likely caused by running the wrong binary to start your desktop.
You should be using the "start-lumina-desktop" binary, not the "Lumina-DE" binary, since the monitor reset routine is run at the beginning of the "start-lumina-desktop" routine.

**Comment by bdklahn** [comment]
So I should then file this bug with PC-BSD?
I didn't choose the binary. This is what got used/configured after installed the Lumina package via AppCafe, and I select Lumina from the login window desktop environment option.

**Comment by beanpole135** [comment]
Which version of PC-BSD?  There was an old .desktop file for Lumina that came bundled with PCDM which would use the "Lumina-DE" binary instead, but you should have a pkg for Lumina 0.9.1 in the repository instead of 0.9.0 which completely removed the "Lumina-DE" binary - invalidating that old .desktop overlay file. The 0.9.0 bug only impacted PC-BSD for a short while since 0.9.1 pkgs got rolled fairly quickly after that to fix this exact issue on PC-BSD/other OS's.

**Comment by beanpole135** [comment]
BTW: You could always delete that old overlay file from the system manually to ensure it uses the right one ("/usr/local/share/xsessions/02Lumina.desktop" or something like that). That should fix it instantly for you.

**Comment by bdklahn** [comment]
"Which version of PC-BSD?"
Please read the second line, of the first comment.

I accept all the package and system updates pushed for my PC-BSD system. "Lumina 0.9.0_3,1" is the one shown in my AppCafe. So that version is among presumed stable packages, despite not really being sufficiently usable (I just noticed I can't delete desktop shortcuts, also)?

Maybe I should track a more development build branch/package repo, if I wish to help test this experimental DE?

**Comment by bdklahn** [comment]
"Lumina-DE" is in my "/usr/local/share/xsessions/02Lumina.desktop". I can delete that file, but I thought I'd try and see if the updated package (0.9.1) would come if I installed via CLI. So I (from KDE) uninstalled Lumina via AppCafe. Then . . .

'''
# pkg install lumina
Updating pcbsd-major repository catalogue...
pcbsd-major repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The following 17 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        lumina: 0.9.0_3,1
        qt5-multimedia: 5.5.1_1
        xcompmgr: 1.1.7
        gstreamer1-plugins-core: 1.4.0
        gstreamer1-plugins-a52dec: 1.8.0
        gstreamer1-plugins-ugly: 1.8.0
        gstreamer1-plugins-dts: 1.8.0
        gstreamer1-plugins-pango: 1.8.0
        gstreamer1-libav: 1.8.0
        gstreamer1-plugins-theora: 1.8.0
        gstreamer1-plugins-dvdread: 1.8.0
        gstreamer1-plugins-resindvd: 1.8.0
        gstreamer1-plugins-png: 1.8.0
        gstreamer1-plugins-vorbis: 1.8.0
        gstreamer1-plugins-ogg: 1.8.0
        gstreamer1-plugins-mad: 1.8.0
        qt5-imageformats: 5.5.1_1

The process will require 31 MiB more space.
. . .
'''

So apparently "Updating pcbsd-major repository catalogue" doesn't bump it up to "0.9.1".
Do I need to ". .  . :/usr/ports # git pull" to have it get, or be able to build, that newer package?

**Comment by beanpole135** [comment]
I am looking now - apparently the packages for 10.3 have been failing to build for a little bit which might be why the newer version is not there yet.

**Comment by bdklahn** [comment]
Is/was it a good idea to list Lumina as "fully-supported", on the main PC-BSD page, if the stable package fails to even build for the latest OS release? :-)
Anyway, I AM pretty excited, from the little bit of Lumina I was able to see/try, vs KDE.
As of now (Fri Jul 22 11:55:26 EDT 2016), I'm still seeing "lumina: 0.9.0_3,1", when I try to get that package. I'd thought to try building from my updated ports tree. But if you are having building issue, I don't know if I could do better (maybe help troubleshoot?). And part of the goal, I think, is to also test the experience for the target desktop users. --who want their default desktop/packages to just work, without having to compile source.
