### ISSUE TITLE
Screen Locking doesn't work

### ISSUE THREAD

**Issue by bdklahn** [trueos/lumina#243]
Lumina 0.9.0-Release
PC-BSD 10.3-RELEASE-p5 amd64 GENERIC on an Optiplex-9010

Neither clicking the lock button in the pop up menu, nor Ctrl-Alt-l, locks the screen.

**Comment by beanpole135** [comment]
This is most likely caused by running the wrong binary to start your desktop.
You should be using the "start-lumina-desktop" binary, not the "Lumina-DE" binary, since the xscreensaver process is launched/managed via the "start-lumina-desktop" routine.

**Comment by bdklahn** [comment]
So I should then file this bug with PC-BSD?
I didn't choose the binary. This is what got used/configured after I installed the Lumina package via AppCafe, and I select Lumina from the login window desktop environment option.

**Comment by beanpole135** [comment]
Same answer as issue #242 - this has the same root cause.
