### ISSUE TITLE
Sleep (suspend) supported but not offered by the operating system

### ISSUE THREAD

**Issue by kmoore134** [trueos/lumina#246]
_From @grahamperrin on August 9, 2016 9:2_

Ergo Vista 621 notebook, circa 2007. 

There's a hot key combination (Function+F1) that's effective for sleep, and the notebook does wake without difficulty, but TrueOS Desktop does not offer the option to sleep. 

_Copied from original issue: trueos/trueos-core#23_

**Comment by kmoore134** [comment]
You mean a GUI option? Moving this over to lumina

**Comment by grahamperrin** [comment]
Yep, GUI. Thanks.

**Comment by kmoore134** [comment]
ken, this is something we should really consider for Lumina.

**Comment by beanpole135** [comment]
Yes, Lumina is setup to use the pc-sysconfig utility for putting the system into the sleep state (setuid restrictions), but that tool has not been migrated over from the PC-BSD source tree yet. I am open to using an alternative utility for activating the sleep state, but I don't know of any others offhand which can be run with user-level permissions.

**Comment by beanpole135** [comment]
Now that pc-sysconfig has been migrated to TrueOS, the suspend option in Lumina is now available again.
