### ISSUE TITLE
Desktop, contextual menu, Terminal: does not launch a terminal application

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#248]
First use of my PC-BSD PersonaCrypt home directory with TrueOS Desktop. 

With the contextual menu, I made two or three attempts to use Terminal. 

The white cursor bears an apparently endless asynchronous progress indicator. 

On closer inspection, Default Applications has nothing alongside Virtual Terminal.

**Comment by beanpole135** [comment]
This looks like your default terminal setting did not transition properly from PC-BSD to TrueOS (if no default is set, it is supposed to use xterm, but TrueOS does not install xterm out-of-box). The newer defaults for Lumina on PC-BSD/TrueOS ensure that the default terminal setting is properly set (pointing to qterminal for TrueOS), so I think we can close this.
