### ISSUE TITLE
Need something to simplify use of removable media

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#251]
Insight Scan for Devices seems to find nothing and the panel item that was familiar in PC-BSD seems to be missing from TrueOS Desktop. 

```
[bbsadmin-l@momh167-gjp4-ergovista621-trueos] ~% sudo gpart show /dev/da0
Password:
=>      63  30218779  da0  MBR  (14G)
        63  30217761    1  fat32  [active]  (14G)
  30217824      1018       - free -  (509K)

[bbsadmin-l@momh167-gjp4-ergovista621-trueos] ~% date ; freebsd-version ; uname -a
Thursday 11 August 2016 at 19:08:33 BST
12.0-CURRENT
FreeBSD momh167-gjp4-ergovista621-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #13 68e1f06(drm-next-4.6): Thu Aug  4 19:31:14 UTC 2016     root@devastator:/usr/obj/usr/src/sys/GENERIC  amd64
[bbsadmin-l@momh167-gjp4-ergovista621-trueos] ~%
```

**Comment by q5sys** [comment]
Not all of the utilities have been added to sysadm at this point.  That's why things like the device panel widget and the wireless widget aren't included.

I dont know if Ken will agree, but this is more a sysadm issue than a lumina issue.  Lumina is the DE, not the entirity of userspace utilities.

**Comment by beanpole135** [comment]
Yes, this issue should be submitted to the trueos/trueos-core repo. 
The mounttray utility has not been converted over from the PC-BSD->TrueOS source trees yet, but that is high on our list for TrueOS here soon (one of the last tools to be migrated over).
