### ISSUE TITLE
Update README.md to reflect release of 1.0, direction to GitHub for issues, and so on

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#257]
At https://github.com/trueos/lumina/blob/master/README.md 

> Qt4 - 0.7.2 (Beta): Use the qt4/0.7.2 branch of the source tree to fetch this version.
> Qt5 - 0.9.0 (Beta): Use the qt5/0.9.0 branch of the source tree to fetch this version.

Also: for bugs, is the direction to https://bugs.pcbsd.org/projects/pcbsd outdated?

**Comment by beanpole135** [comment]
I just fixed the README.md

We are recommending that bugs get reported right here now (already updated on the website and within the lumina-info utility, since PC-BSD is moving away from using the bugs.pcbsd.org tracker.
