### ISSUE TITLE
Desktop settings window list collapses when returning from a configuration window

### ISSUE THREAD

**Issue by hxw** [trueos/lumina#259]
This is on PCBSD 10.3-p6 with: lumina-1.0.0.r.p1,2

When using the Desktop Settings there are 4 icons with indicator triangles if I expand and resize the window
to be able to see all configuration items.  When any configuration is completed by clicking its 
`back to settings`  button the icon lists will all be collapsed into the 4 icons again.  It just is awkward to use like this.

Is there any setting to start with all icon lists expanded?

**Comment by beanpole135** [comment]
Fixed!
I just made that first page "aware" of the previous page the user was on, and it will now automatically expand a category and highlight that page as needed.
