### ISSUE TITLE
System Monitor desktop plugin shows wrong temp

### ISSUE THREAD

**Issue by ct16k** [trueos/lumina#261]
Hello,

I'm using `lumina-201608251759,2` from an August snapshot of TrueOS Desktop. The `System Monitor` desktop plugin constantly shows `25.1C` as the CPU temp, unlike the `SysAdm` task manager, which shows correct temperatures:
![screenshot](http://i.imgur.com/nDL8j9d.png)

System is a `Latitude E5470`, running `FreeBSD 12.0-CURRENT #0 ba57422(drm-next-4.7): Mon Aug 22 16:19:26 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64`

**Comment by beanpole135** [comment]
Hmm. sounds like something in the backend OS-interface which is not working right in Lumina.

Try this and see what is reported:
`sysctl -ai | grep ".temperature:"`

**Comment by ct16k** [comment]
```csh
> sysctl -ai | grep ".temperature:"
hw.acpi.thermal.tz0.temperature: 25.1C
```
After searching around a bit about getting the temperature from CLI I got to the following (CPU is a `Core i5-6440HQ`):
```csh
[root@pcbl] ~# kldstat | grep core
[root@pcbl] ~# kldload coretemp
[root@pcbl] ~# kldstat | grep core
57    1 0xffffffff8374c000 2b13     coretemp.ko
[root@pcbl] ~# sysctl -ai | grep ".temperature:"
hw.acpi.thermal.tz0.temperature: 25.1C
dev.cpu.3.temperature: 37.0C
dev.cpu.2.temperature: 37.0C
dev.cpu.1.temperature: 40.0C
dev.cpu.0.temperature: 39.0C
```
So I guess `SysAdm` loads the module while `System Monitor` doesn't / can't? (and that I have a broken sensor / buggy firmware on the laptop, that's constantly reporting `25.1C` :/ )

**Comment by beanpole135** [comment]
Hmm, let me look into this and see if I can switch the backend OS interface to load the individual CPU temperatures instead of the overall ACPI value.

**Comment by beanpole135** [comment]
Fixed!
https://github.com/trueos/lumina/commit/c82b3b2e3b10210583f8ae606fc78cfc5b0daad1
