### ISSUE TITLE
Shortcut to open the Menu

### ISSUE THREAD

**Issue by d3xter** [trueos/lumina#265]
It would be nice to have a short cut (Mod4?) to open the user menu.

So I can press Mod4 -> Search for a program -> Press enter -> Program starts up

**Comment by beanpole135** [comment]
The "windows" key should already be setup with this shortcut. If that is *not* working for you, please run "xev" from the command line, move your mouse cursor into the new window, than press the "windows" key and see what key number is detected (115 is the key number Lumina expects for the windows key by default).

**Comment by d3xter** [comment]
Is they key number 115 hardcoded in lumina or is there a way to change it?

**Comment by beanpole135** [comment]
The 115 key is only put into the Fluxbox keyboard shortcuts definitions by default - it can easily be changed via the configuration tool at any time.

**Comment by d3xter** [comment]
Got it, thanks
