### ISSUE TITLE
Regression - problems with to add apps to context menu

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#271]
Regression in Lumina 1.0.1 and TrueOS image from 20-Sep-2016. In settings if to try add Custom application to the context menu, for example Firefox, Lumina can't show the installed apps. On image from 09-Sep-2016 this problem is not observed. On screenshot is the Russian language.

![contextmenu](https://cloud.githubusercontent.com/assets/20837310/18740275/b14ec53e-80ca-11e6-96a8-317f206ed5a3.png)

**Comment by beanpole135** [comment]
This has been fixed in the latest from source.
