### ISSUE TITLE
feature request: advanced mouse configuration settings

### ISSUE THREAD

**Issue by larrydewey** [trueos/lumina#276]
It would be extremely helpful to have a section in the configurations area that will allow you to enable natural scrolling, disable tap to click, etc.

**Comment by beanpole135** [comment]
A new page within the Lumina configuration utility was just committed specifically for managing input device properties.
Note that the properties available are the ones which the device(s) report as available, so the options that are available will greatly depend on the level of hardware support for that particular device.
