### ISSUE TITLE
Regression - failure Startup services and Applications

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#278]
Sorry for my bad English... TrueOS Image from 2016-09-29 and Lumina 1.0.1. Regression in Preferences / Desktop / Desktop Session Options / Startup Services and Applications. If click to menu item "Startup Services and Applications", then settings window closed. This problem is not observed on previous versions of TrueOS.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/885058701071f07690f3e7b396374e8c29a8f05c
