### ISSUE TITLE
Insight displays incorrect file sizes: 1GB appears as 0.1000G

### ISSUE THREAD

**Issue by tHubig** [trueos/lumina#281]
1GB files appear as having size 0.1000G in the Insight file browser. Smaller and larger files have their correct sizes displayed. This quirk has been present for the last 3 updates to TrueOS, so I figured no one has noticed it.

Actual size as reported by ls "1.0G" or "1073741824"

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/c03797a535089d458dffec3ff64ba052542860ed
