### ISSUE TITLE
FR: Lumina-info console output version

### ISSUE THREAD

**Issue by mike-pt** [trueos/lumina#285]
A few days (weeks?) ago while investigating the memory leak issue, I found myself in need of this... 

If lumina crashes... sometimes it might be usefull to get version info without having Xorg running... would it be to complicated to get version info in text output only?

I guess the most important part would be "desktop version"... so maybe even a different tool "lumina-version" is enough.

**Comment by beanpole135** [comment]
This is already possible by running "lumina-desktop --version"
That will just return the current version string for your build of Lumina

**Comment by mike-pt** [comment]
I had no idea :/ sorry for the noise.
