### ISSUE TITLE
Any Issues About Crash on Update RSS Feeds Plugin?

### ISSUE THREAD

**Issue by marcelbonnet** [trueos/lumina#287]
Hi. I'm using  Lumina 1.0.0 on FreeBSD. (loved it, by the way since 0.8).

When starting lumina for the first time after power on the machine, it crashes with signal 6 on update RSS feeds.

Whats the best way to investigate? The core image dump? The lumina logs are not pointing anything, but update RSS are the last logs and there's no error message, nothing clear.

So, after crashing, I "startx " again, and the desktop runs nice. One crash a day, it's fine, but would be good to solve it.

**Comment by beanpole135** [comment]
That is a new one to me. This might already be fixed in 1.0.1 though, since there have been a number of interesting/edge-case crashes which have already been fixed since 1.0.0.

If you can, please rebuild/install Lumina from source and see if the crash still occurs on 1.0.1

**Comment by marcelbonnet** [comment]
> If you can, please rebuild/install Lumina from source and see if the crash still occurs on 1.0.1

is there another tag for that? I've installed tag v1.0.0-Release-p2 , the latest tag I found.

I'll test for some days to be sure.

**Comment by marcelbonnet** [comment]
I compiled and installed 2334aa1c880aecd062a6ff2b272608f675092a95 (it was HEAD a week ago). Stil crashing.
Then I removed the RSS Feeder . No more crashes.
Sorry, I have no more tech details or debug.  I'm not skilled in C++.

**Comment by q5sys** [comment]
Marcel,
Are you still having the same problem on a more recent version of Lumina?

**Comment by marcelbonnet** [comment]
I need to check it. What I can say is that behavior was not reproduced in
another box, running FreeBSD 64 bit.
So, it is possible that is something with my FreeBSD 32bit/ notebook,
packages... I dont know yet.

Marcel Bonnet

Em 16 de dez de 2016 16:24, "JT Pennington" <notifications@github.com>
escreveu:

**Comment by q5sys** [comment]
if this becomes an issue again, please reply back and I'll re-open the ticket.
