### ISSUE TITLE
Feature: Per device mouse settings

### ISSUE THREAD

**Issue by ppumkin** [trueos/lumina#289]
When I first installed PCBSD the onboard mouse was soooo slow. I didnt even know how to change the settings.

When I tried TrueOS and Lumina, the onboard synapitcs mouse is set pretty well.  

Now, the mouse I plugged in, via USB is so sensitive I cannot control the cursor. It is flying from screen to screen but while its plugged in the sensitivity on the touch pad is OK.

Surely there must be a way to set sensitivity per device. Don't "kill me", but on Windows I can set per device. Just saying, would be nice. :)

:+1: 
PS This is the first time I have ever submitted a bug using Lumina and Firefox provided in Lumina. Baby steps.

**Comment by ScottyDM** [comment]
Most excellent.

I came to ask if there was a sensitivity setting for the mouse. Mine seems to have a resolution of pico-nano-whatevers and I guessing Lumina maps that directly to pixels, so like ppumpkin my cursor flies from one side of the screen to the other if I so much as breathe on the mouse.

Luminatis, is there a setting I just don't see?

**Comment by beanpole135** [comment]
A new page for managing input device properties was just added to the lumina-config utility. This will allow the user to view/change almost any property which the device(s) report/use with the X11 subsystem.

**Comment by ScottyDM** [comment]
That's awesome! Where is it? When I check for updates it says my system is up to date. When I look in "lumina-config" I don't see anything about a mouse (or similar pointing device. "config" seems to be a command-line tool. "Fcitx" seems promising but that appears to only cover keyboards. Thanks.

**Comment by q5sys** [comment]
https://github.com/trueos/lumina/blob/master/src-qt5/core-utils/lumina-config/pages/page_mouse.cpp

You'll need to update Lumina to get it, since it's a recent addition.
