### ISSUE TITLE
Feature: Prevent lag click memory

### ISSUE THREAD

**Issue by ppumkin** [trueos/lumina#290]
I'm all new to this. So when I click a button.. I am not sure if something is gonna happen or not. Not sure why I get this feeling? So I click it again, turns out its loading... ok. Hold on then.

Boom, loads and then instantly my previous click, clicks on something in the new window. doh! 

Is there any way to prevent this.. why would my previous click register on the new page 2 or 3 seconds later?

The place it happens to me mostly is while browsing app-cafe. Click on games section at the bottom. OK... nothing happening, no visual cue of any sort :( click again and then when the list eventually loads it clicks into something arbitrary. 

The lagged out, previous click should have been invalidated on the newly rendered page.

**Comment by q5sys** [comment]
I know this is an old ticket, are you still having this issue? I've been unable to reproduce this.

**Comment by Mrt134** [comment]
Closing this issue as there has been no response for over 3 weeks and the issue was not able to be duplicated. Please reopen or create a new issue if this still occurs.
