### ISSUE TITLE
Cannot set primary screen on multi monitor setup

### ISSUE THREAD

**Issue by ppumkin** [trueos/lumina#291]
When I use 

Preferences -> Display

And set my HDMI to be the Primary (cause I want the task bar to be on my big monitor in front of me instead of on the little netbook on the side)

It just reverts the tick box after I press click apply.

I ran dmesg but there is no error relating to that particular issue. I mean.. its great that I can attach another monitor though :+1:  :)

Is there anything I can do to help provide more debug info? Or is this just a known issue maybe?
(since I am using Lumina now.. I don't know how to take screenshots and crop them nicely.. so sorry for lack of screenshots.. im learning)

Hardware:
Lattidue E6220 using built in Intel GFX

**Comment by q5sys** [comment]
With all the recent updates to Lumina, are you still running into this issue?

**Comment by q5sys** [comment]
It's been a month with no response, so I'm going to close this.  If you are still having this issue, please reply and I'll re-open the ticket.
