### ISSUE TITLE
Show some more info on app-cafe 

### ISSUE THREAD

**Issue by ppumkin** [trueos/lumina#292]
After installing an arbitrary package, for example affenspiel.

How do I launch it?
How do I find it?

Sorry.. I just do not know where it is, clearly big n00b here. It would be nice to have a button like the following on the installed packages screen.

-Pin to desktop
-Open location
-Launch Application

**Comment by q5sys** [comment]
sysadm only installs the files that are in the package itself.  If the package does not ship with a `.desktop` file it will not show up in the menu or end up on the desktop.  if you installed a package and are unsure of where to find it.  If you open the application page inside appcafe and go to the 4th tab you can get a full list of all the files in the package.  e.g. for `nano` the first file in the is `/usr/local/bin/nano` which happens to be the binary for that file.  The binary may or may not be the first entry in that list, but you should be able to find the binary to launch for that file.  You can then launch that binary from the command line to start it.  

I should probably write a `.desktop` creator application to help a user create those `.desktop` files if they do not exist.
