### ISSUE TITLE
lumina 1.1.0

### ISSUE THREAD

**Issue by RodMyers** [trueos/lumina#293]
i have 6 screens/work spaces invoked.

upon compiling, installing and rebooting, only workspace 1 has a background image, and is the only workspace that allows menu selections

**Comment by beanpole135** [comment]
Fixed!
I backported this to the 1.1.0 branch as made a new "patchset 1" release/tarball for this as well.

https://github.com/trueos/lumina/commit/0032544d7d9607ad544dd427ea1bd012291ff962
