### ISSUE TITLE
Lumina Calculator

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#294]
;-) For example, (1/3)*3 = must be 1, but not 0.99999... This is situation for consumer calculators, but scientific calculator print correct result. 

![calculator](https://cloud.githubusercontent.com/assets/20837310/19617556/4fa59af4-9855-11e6-8c68-c7dfd8c8d204.png)

**Comment by beanpole135** [comment]
Ah, good catch. I will try to get the algorithm cleaned up so it is a bit smarter and more accurate about things like that... :-)

**Comment by beanpole135** [comment]
Fixed!
The double -> string conversion for equations within parentheses was at fault here (resulted in chopping the number at a lower precision, causing round-off issue).

https://github.com/trueos/lumina/commit/52b42cfa1021edba7a71f47a7c537f24790b9ff5

**Comment by DmitryPostolov** [comment]
Ken, (1/3)*3 now is 1, all OK. Thanks!
But,
1/3=0.333333...
previous result * 3 = 0.999999, but must be 1.
Problem is in rounding of preliminary result and use of the previous rounded value.

![calculator](https://cloud.githubusercontent.com/assets/20837310/19711322/cfe0f944-9b56-11e6-9601-e6d6e42c4a3d.png)

**Comment by beanpole135** [comment]
Here you go!
This makes the history recall routines quite a bit smarter, and if the history result looks like it was rounded off for display purposes, it will re-calculate that equation again to ensure accuracy in the subsequent equations.

https://github.com/trueos/lumina/commit/efbf100822f8a50abdcfb061b7b1bf1be06b868c

**Comment by DmitryPostolov** [comment]
;-) Ken, if manually print 0.333333*3=0.999999 (0. six numbers of 3 *3 = 0. six numbers of 9 and all OK), but if manually print seven and more numbers of 3 (0.3333333*3 = Calculator print 1, but must 0.9999999).

![calculator](https://cloud.githubusercontent.com/assets/20837310/19911042/351d5d84-a0bb-11e6-94aa-613273d15196.png)

**Comment by beanpole135** [comment]
I wanted to make sure the fix I put in was more generic for catching *all* round-off errors rather than hard-coding fixes for known rounding issues. This should ensure the most accurate result when chaining equations together, rather than making assumptions about the intent of the user.

You can tell I have a math/science background.... Too many bad memories about discovering a tool was rounding numbers at lower precision than what I needed.   :-)
