### ISSUE TITLE
Create new file/directory problem on lumina-fm dual column view

### ISSUE THREAD

**Issue by rafeyu** [trueos/lumina#295]
I use Lumina 1.1.0 in VoidLinux. There is a problem when I create file or directory in dual column view. New file and directory are create in first column instead of new column.

**Step to reproduce**:
1. Open lumina-fm
2. Click on Dual Column View
3. In new column, go to different directory then create new file and directoy. They will be created in first column.

**Expectation**:
File and directory I create should be appeared in new column.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/64572549b46acde9ef30565303f59d629cf0eb60
