### ISSUE TITLE
My problem with no sound on startup/exit and internal player on FreeBSD & Lumina from src

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#296]
Ken, can you help me with Lumina 1.1.1 & FreeBSD?

FreeBSD 11.0-RELEASE-p2 amd64.
Already installed: clang 3.8.0

I. Dependences. Manually installed from pkg:
1. Xorg [Xorg, version 7.7_2, xorg-server, version 1.17.4,1]
2. qt5 [manually installed, version: 5.6.1]
   2.1 /usr/local/lib/qt5/bin/qmake [already installed]
   2.2 qt5-linguisttools [already installed]
   2.3 qt5-buildtools [already installed]
   2.4 qt5-core [already installed]
   2.5 qt5-concurrent [already installed]
   2.6 qt5-gui [already installed]
   2.7 qt5-multimedia [already installed]
   2.8 qt5-network [already installed]
   2.9 qt5-x11extras [already installed]
3. xcb [manually installed, version 2.4_3]
   3.1 libxcb [already installed]
   3.2 xcb-util [already installed]
   3.3 xcb-util-wm [already installed]
   3.4 xcb-util-image [already installed
4. fluxbox [manually installed, version 1.3.7_1]
   4.1 fluxbox-tenr-styles-pack [manually installed]
   4.2 kde4-icons-oxygen [manually installed]
5. xscreensaver [manually installed, version 5.35]
6. numlockx [manually installed]
7. xterm [already installed]
8. qterminal [manually installed]
9. xbrightness [manually installed]

II. Lumina src.
1. % git clone https://github.com/trueos/lumina
2. % cd lumina
3. % /usr/local/lib/qt5/bin/qmake
4. % make
5. # make install
6. # make distclean

III. Run Lumina-DE: % start-lumina-desktop

IV. Lumina-DE starts OK, but on FreeBSD after build from src and configure Preferences / Desktop / User Settings / General Options - Play chimes on startup and exit "ON", sound on startup and exit is not played. And in Lumina internal audio player sound is not played and mp3 files are not printed on player menu after add music files/dir.

If in terminal run # cat /dev/random > /dev/dsp sound played OK, Firefox and VLC player play sound OK too. On my Intel NUCs sound plays fine only with setting: "dev.hdac.0.polling=1" in /etc/sysctl.conf. sysctl hw.snd.default_unit by default, =0. Back panel plug for external speakers.

IV. If to install Lumina-1.0 manually from pkg: pkg install lumina, then Lumina internal player play sound OK, and play chimes on startup and exit is also OK. On TrueOS this is also OK with sound with internal utils.

V. Please, help me to fix problem with no sound on FreeBSD & Lumina 1.1.1 internal audio player and play chimes on startup and exit after build and run Lumina 1.1.1 from src...

**Comment by beanpole135** [comment]
It sounds like your FreeBSD system might be missing the multimedia backend for Qt.
If you look at the Lumina port, you can see that the "MULTIMEDIA" option (on by default) will ensure that the gstreamer-plugins-core package is also installed. That is required for Qt to be able to access/play audio/video files (adding more gstreamer plugins will also give Qt more compatibility with various file formats depending on the plugin).

**Comment by q5sys** [comment]
Dmitry,
Are you still having this issue?

**Comment by DmitryPostolov** [comment]
q5sys,
I need more testings and experiments with FreeBSD. Now I am use TrueOS and all OK.

**Comment by q5sys** [comment]
Dmitry,
Thanks for reporting back.  If you run into this again in the future, please let us know.
