### ISSUE TITLE
Port maintainer for OpenBSD here with a question

### ISSUE THREAD

**Issue by bceverly** [trueos/lumina#298]
Hi everyone,

Just wanted to start this out by thanking everyone for their hard work on Lumina.  It's my daily driver on OpenBSD and I really appreciate it.

That said, I'm wrapping up the update to the 1.1 release for our ports/packages system and I have a bit of an issue that I would appreciate help with.  I'm currently working around this with patches applied after the source tarball is expanded but that feels sloppy and I'd prefer to work with my fine friends in the land of Upstream to get a PR approved here so I don't have to do that.

Here's my issue.  In three of the .pro files there are actions being taken in a .extra that use relative pathing (cd i18n && blah blah or cp defaults/blah.jpg, etc.)  Not sure how the ports/packages system works on other BSD family operating systems, but in ours, we build in one directory and we create the install image in another.

Unfortunately the relative pathing fails to work in this situation and my package construction step bombs out with file not found or directory not found.

As I'm not familiar at all with qt applications, I'm unsure of what the right fix would be here.

Could someone point me in the right direction and I'd be happy to submit a PR.

Thanks in advance,
Bryan

**Comment by beanpole135** [comment]
Ok, those relative paths are related to the current organization of the source tree when you run "qmake" to generate the Makefiles.

For a quick example, lets look at the new lumina-calculator project directory (src-qt5/desktop-utils/lumina-calculator):

There is an "i18n" subdirectory which contains all the raw localization files (*.ts). So within the .pro there are two operations which interact with this dir: 

The "TRANSLATIONS" target contains all the relative paths for the .ts files (i18n/l-calc_<locale>.ts), and the "dotrans" target runs the "lrelease" utility from Qt to convert the .ts files into compiled .qm files which can be loaded by the application at runtime, then copy those files into the install dir.

If you need to place all the compiled applications within a different non-install directory prior to packaging, you might want to look into using the "DESTDIR" build flag when running qmake on the Lumina tree (See the explanation of the build flags here[1]). That will basically let you extract the Lumina sources into a "workdir", do the build within the workdir, but have all the compiled/"installed" files put into some packageing dir.

[1] https://github.com/trueos/lumina#how-to-build-from-source
