### ISSUE TITLE
Network manager does not support/work with usb wifi devices  ?

### ISSUE THREAD

**Issue by ZloyHohol** [trueos/lumina#302]
TrueOS desktop (PC-BSD 9 and 10) not work with some devices: tl-wn721n (atheros based) and broadcom wifi+bluetooth m.2 bcm 43142

[network manager and usbconfig](https://yadi.sk/i/aaOqgZZnyaecN)

why these devices not supported on PC-BSD(now TrueOS)?

I know that linux kernel for these devices use next drivers: ath9k and dkms-broadcom.

I hope that i will can  use tl-wn721n device for "surfing" on wireless network 

excuse for my english

**Comment by beanpole135** [comment]
Wireless driver support depends greatly on the version of the OS you are running - FreeBSD/PC-BSD 9 and 10 are very old, and will not have the same driver support as TrueOS or FreeBSD 11.0

Please try TrueOS instead, and see if those wifi chipsets start working for you. If not, please open a ticket on the FreeBSD bug tracker[1] and include as much information about those wireless chipsets as possible.

[1] https://www.freebsd.org/support/bugreports.html
