### ISSUE TITLE
Panels may disappear when Lumina defaults or system defaults are applied, or when adding a panel

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#304]
From [[Solved] Lumina missing panels](https://discourse.trueos.org/t/solved-lumina-missing-panels/225/2?u=grahamperrin):

> … Simple fix … "return to Lumina Defaults".

## Expected

A panel, populated. 

## Actual result

Disappearance of all panels. 

## Environment

[… Intel HD Graphics 5500](https://discourse.trueos.org/t/broadwell-intel-hd-graphics-5500-loader-trueos-branding-then-grey-screen-at-the-notebook-no-problem-with-external-displays/199?u=grahamperrin) … with one external display.

```
$ xrandr
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected 1366x768+0+0 (normal left inverted right x axis y axis) 410mm x 230mm
   1366x768      59.79*+
   1280x800      59.81  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
HDMI-2 disconnected (normal left inverted right x axis y axis)
$ date ; freebsd-version ; uname -a
Sat 19 Nov 2016 09:09:53 GMT
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ 
```

**Comment by q5sys** [comment]
How are you reproducing this issue?  I'm not asking what the person in the thread did... how did 'you' reproduce this on your system?

**Comment by grahamperrin** [comment]
HP EliteBook 850 G2, UEFI with CSM, working with just one display, external. 

(AFAICT: the system stops driving the internal display when it begins driving the external; when kernel modules are loaded.)

I can log on and create panels. If I click either _Return to system defaults_ or _Return to Lumina defaults_ and save settings, then all panels disappear; _Floating Panels and Plugins_ shows just the '+' icon.

**Comment by grahamperrin** [comment]
https://discourse.trueos.org/t/solved-lumina-missing-panels/225/5 a more recent report from someone else: 

> … problems with Lumina missing panels after I installed nVidia 340 drver … dual monitor setup… played a bith with adding some panels manually and after they were added, the "Return to lumina defaults" removes all things added so my desktops are blank: …

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/1b7f0d30506c1c9ff39acbe8cd6e6403a02ae5f2
