### ISSUE TITLE
Lumina preferences: a more visual approach to browsing themes, appearances etc.

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#305]
Consider the two screenshots in the opening post at https://discourse.trueos.org/t/-/233?u=grahamperrin

`lumina-config` (Desktop Settings) typically previews a thing after that thing is selected, sometimes only after a selection is saved. Loosely speaking: one thing at a time. 

## Enhancement request

A more visual approach; a browser of some sort allowing more than one thing at a time to be previewed. 

First thought: an array of reasonably large tiles, each tile representing a theme of some sort. 

### Afterthoughts

Presentation of tiles (or whatever) need not be constrained to the `lumina-config` GUI. If the visuals can be made available from a web server, in an arrangement that complements `lumina-config`, then the user might simply use a web browser. 

There may be the temptation to add screenshots at or around https://lumina-desktop.org/handbook/luminaconfig.html#appearance but (personally) I'd like the handbook to remain reasonably free from clutter :+1: 

For what it's worth, I imagine a milestone of Lumina 2.0 for issues such as this.

**Comment by q5sys** [comment]
Ken and I have talked about this before, but there's so much to do right now that this probably wont be accomplished any time in the near future.
