### ISSUE TITLE
Lumina preference to disable compositing appears to be not saved

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#306]
## Steps

1. In _Compositor Settings_, set the preference then click _Save_
2. log out (end the session)
3. log in 
4. review preferences

## Expected

- the preference

## Actual result

- a repeated prompt to save the preference: 

![2016-11-19 10-56-31](https://cloud.githubusercontent.com/assets/192271/20456167/13068b1c-ae67-11e6-8644-f9af998d3440.png)

**Comment by grahamperrin** [comment]
## Afterthoughts

If you can not easily make this reproducible: 

1. retry as a user who is an operator but not an administrator; and/or 
2. wonder whether my unusual test environment is a factor ([Lumina in ttyv7 with (for example) KDE in ttyv8](https://discourse.trueos.org/t/lumina-in-ttyv7-with-for-example-kde-in-ttyv8/231) …). 

----

(Note to self: periodically test Lumina and the OS in the wild without admin priviliges, and without operator privileges.)

**Comment by q5sys** [comment]
I've been unable to reproduce this on two systems. TrueOS and Slackware.  Also, what do you mean 'without admin priviliges, and without operator privileges.'?  What are you calling an Operator?

**Comment by grahamperrin** [comment]
Operator as in, a member of the operator group; seen in SysAdm (below) when adding a user, and described in the guide. 

![sysadm](https://cloud.githubusercontent.com/assets/192271/20459012/be8b37be-aeab-11e6-9c20-426b25813960.png)

I tested as a different user, an administrator, reproduced the issue. 

```
$ freebsd-version ; uname -a
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ pkg info lumina | grep Version
Version        : 201610280752,2
$ 
```

It's a minor issue, I can retest at a later date with a more recent version of Lumina.

**Comment by grahamperrin** [comment]
Reproduced with the most recent Lumina …

**Comment by q5sys** [comment]
can you reproduce this issue as an adminstrator?

**Comment by grahamperrin** [comment]
Yes, please see https://github.com/trueos/lumina/issues/306#issuecomment-261746040 above.

**Comment by q5sys** [comment]
Can you check your permissions on /usr/local/share/lumina-desktop/compton.conf

**Comment by grahamperrin** [comment]
```
$ ls -l /usr/local/share/lumina-desktop/compton.conf
-rw-r--r--  1 root  wheel  2084 27 Oct 13:26 /usr/local/share/lumina-desktop/compton.conf
$ 
```

Back to basics, for a moment. To double-check that we have a shared understanding of the issue, as I see it: 

- there's the icon for a floppy disc, with the word 'Save' 

– and that prompt to save is unexpected, because the preference was already saved (in a previous session of Lumina). 

----

I'll test a fresh installation at a different computer …

**Comment by q5sys** [comment]
I wanted to see if permissions on that file were messed up somehow.  Everything in page_compton.cpp is working as it should.  It seems odd that you're having a problem because I just did this last week on my laptop without issue, and in testing today, I can turn it on and off without issue.

**Comment by grahamperrin** [comment]
OK, so defocusing from the prompt to save: what should I grep in `/usr/local/share/lumina-desktop/compton.conf` to tell whether a previous save succeeded?

**Comment by grahamperrin** [comment]
> I'll test a fresh installation at a different computer …

Ergo Vista 621 notebook with Intel GM45 graphics hardware. 

```
$ uname -v
FreeBSD 12.0-CURRENT #39 4477733(drm-next-4.7): Wed Nov 16 20:01:55 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$
```

A fresh installation, followed immediately by steps (1)–(4) above, the issue is reproduced; there's the unexpected prompt to save.

**Comment by q5sys** [comment]
Ok you're getting a dialog to save, but is compton disabled after you do it the first time and log out/in?
You should be able to tell easily enough if compton is active by whether you have transparency of windows when you mouse over the main panel.

**Comment by grahamperrin** [comment]
AFAICT, with the black of a Qterminal window partly obscuring the RSS widget: no transparency. That part of the widget remains obscured.

**Comment by q5sys** [comment]
Ok good, Compton is being properly disabled as it should be.  So what you're reporting is that the save icon appears when you load the page?

**Comment by q5sys** [comment]
> So what you're reporting is that the save icon appears when you load the page?

If that was your issue, I've got a patch as a PR to fix it.

**Comment by q5sys** [comment]
Issue was not that the settings were not being saved, but rather that the save icon was always enabled on page load.  This has been fixed.

**Comment by grahamperrin** [comment]
From your https://github.com/trueos/lumina/issues/306#issuecomment-261753835 above: 

>  the save icon appears 

Yes, as I originally described the actual (unexpected) result: 

> a repeated prompt to save the preference

– with the screenshot that showed the save icon :-)
