### ISSUE TITLE
The title of the window of Lumina Screenshot should be 'Lumina Screenshot'

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#311]
The current title, _Take Screenshot_, is not fitting when the application is launched. 

(_Take Screenshot_ becomes a fitting _title_ only after the user switches away from _View/Edit_, to _New Screenshot_; in that tab (to the left) there's the Take Screenshot _button_.)

**Comment by q5sys** [comment]
PR to change title to 'Screenshot Utility' submitted. (not every utility needs to be branded with Lumina (example: Insight File Manager)

**Comment by grahamperrin** [comment]
Thanks. The Lumina branding wasn't a concern, I was more interested in consistency (matching), and in distinction from other applications. Insight is consistent with Insight File Manager :+1: and so on.
