### ISSUE TITLE
an item dragged from Insight should be droppable in an application that supports drop

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#312]
Maybe a regression, compared to https://bugs.pcbsd.org/issues/11597

## KDE

When I begin to drag, there's a 'no entry' cursor before movement of the file goes beyond the window of Insight. 

## With Lumina 1.1.2 (Git Revision: d5a55a0)

In lieu of the no entry cursor there's a simple circle cursor. (Maybe neglible; as the 'test' user in this DE, I recently experimented with changes to appearance.)

## In both environments

When drag continues to (for example) the Firefox window of this 'Submit new issue' dialogue: 

- the cursor remains unchanged
- releasing the button of the mouse does not cause a drop into Firefox.

**Comment by grahamperrin** [comment]
https://gitter.im/trueos/Random?at=58570d93e7bdfe4e296e4b2e

> I have found that both Thunar (xfce) and, now, Lumina
> I think Lumina-fm's :dragon: :droplet: has been fixed

**Comment by baitisj** [comment]
I just tested lumina-fm from lumina-201612132146,2 and drag and drop seems to be working fine
