### ISSUE TITLE
Insight not working as it should with ZFS snapshots: disorderly menu, timeline wrong, inexplicable changes of path …

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#315]
This screen recording should be mostly self-explanatory. 

[2016-11-27 14:45 screen recording.ogv.zip](https://github.com/trueos/lumina/files/615584/2016-11-27.14.45.screen.recording.ogv.zip)

Amongst the symptoms: 

- disorder, not chronological, when the menu is pulled down to the left of the timeline
- inexplicable changes of path, to a nonexistent path – for example (not in the recording, but reproduced whilst reporting this issue) from `/usr/home/gjp4/.mozilla/firefox` to `/usr/home/gjp4/firefox`

## Use case

A refresh of Firefox was followed by restoration of all tabs and automated installation of my preferred add-ons, including [Tab Groups](http://fasezero.com/addons/), but the restoration  occurred without grouping so I aimed to restore, from a ZFS snapshot, [Session Manager](http://sessionmanager.mozdev.org/) data. 

I aimed to go back in time just a little, less than a day. Focused on:  

`/usr/home/gjp4/.mozilla/firefox/`

## Notes

Reproducible with Insight in Lumina. 

I found no problem with: 

- (GNOME) Files
- terminal access to the file system.

[2016-11-27 14:47 terminal output.txt](https://github.com/trueos/lumina/files/615588/2016-11-27.14.47.terminal.output.txt)

[2016-11-27 15:00 browsing snapshots in a terminal.txt](https://github.com/trueos/lumina/files/615593/2016-11-27.15.00.browsing.snapshots.in.a.terminal.txt)

Outputs from `zpool status -v` did show a handful of errors before and after a scrub, however I doubt that those errors were contributory to the symptoms seen in Insight. 

I'm reminded of these bugs in PC-BSD: 

- [Bug #11416: Insight (lumina-fm) sometimes strays from the required path when using the timeline of snapshots …](https://bugs.pcbsd.org/issues/11416)
- [Bug #11488: On the timeline in Insight: two points with the same time, with '1' in their midst …](https://bugs.pcbsd.org/issues/11488) in particular, after supposed resolution: 

> Sorry, symptoms of this bug are still reproducible. …

– yesterday's screen recording does show the same point in time at multiple points on the timeline.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/24d88d1ac4d316da3527b236c6cedb2b4a90bc85
