### ISSUE TITLE
Insight does not reliably show hidden files

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#316]
Observed after reporting #315 and I should probably treat this issue as separate, maybe contributory. 

![2016-11-28 07 28 31](https://cloud.githubusercontent.com/assets/192271/20659582/5206f500-b53c-11e6-81ec-9123a0479bb0.png)

There's my preference to show hidden files, apparent when I launch Insight, but those files are not shown.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/33010dd68c2a80edde7dd9b219a4383453fd132b
