### ISSUE TITLE
Clipboard doesn't retain cut text after source application has been closed

### ISSUE THREAD

**Issue by BlazeTester** [trueos/lumina#317]
(System: TrueOS-Desktop-2016-10-28 installed in VirtualBox; Lumina Desktop).

This problem was observed with every application I examined so far; as an example I choose Firefox and Lumina Text Editor:

Successful operation:
In the address field of Firefox, I type the word crackle_crackle. Then I cut it out with shortcut Ctrl + X and I can paste it into Lumina Text Editor with shortcut Ctrl + V successfully.

Unsuccessful operation:
In the address field of Firefox, I type the word crackle_crackle. Then I cut it out with shortcut Ctrl + X and close Firefox.
Then I try to paste the word into Lumina Text Editor with shortcut Ctrl + V, but the word isn't pasted; thus the cut word is lost.

(Analogous behavior can be observed if the cut operation Ctrl + X is replaced by the copy operation Ctrl + C).

**Comment by beanpole135** [comment]
This is how application clipboards are designed to function on X11. If you want to preserve clipboard contents across all applications, then you need to startup a "clipboard manager" application which is designed to perform this exact functionality in addition to (typically) providing clipboard history and stuff as well.

Some apps like this which come to mind for TrueOS are:
* copyq (my personal recommendation -  works really well with Lumina)
* gnome-clipboard-daemon (if you are using the GNOME desktop)
* xclipboard (old and ugly but works)
* parcellite (GTK2, but might work)
