### ISSUE TITLE
VirtualBox Host Guest OS fullscreen not visible.

### ISSUE THREAD

**Issue by jsm222** [trueos/lumina#319]
Running VirtualBox as host under lumina-desktop courses the fullscreen of a Guest OS in Virtualbox to  be invisible. It does not happen on only fluxbox with or without compton.

**Comment by beanpole135** [comment]
I think I am going to have to flag this as a bug in VirtualBox.

I have reproduced the error on a couple systems, but cannot find anything within Lumina which is mishandling the window based on the flags set on it. In fact, other applications can go fullscreen just fine within Lumina, which seems to indicate that it is something within how VirtualBox flags/manages its fullscreen window.

**Comment by jsm222** [comment]
Actually I think the problem is with fluxbox. Using fuxbox on LXQt, renders also not the full-screen VirutalBox guest os window correctly.
