### ISSUE TITLE
Reduce the likelihood of obscurity of the leave dialogue for Lumina

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#322]
Enhancement request. 

The dialogue should be foremost (in front of, for example, any SysAdm client window). 

(With `FreeBSD 12.0-CURRENT #2 f71568c(drm-next-4.7): Tue Dec 13 21:04:35 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC` I noticed that if a client window is around the centre of the screen, then the leave dialogue can not be seen.)

**Comment by beanpole135** [comment]
I am unable to reproduce this:
The "Leave" dialog is already flagged with the "AlwaysOnTop" property, and Fluxbox seems to be respecting that just fine on all my systems.

I will leave this open for a bit in case somebody else can reproduce this and chimes in as well.

**Comment by grahamperrin** [comment]
Hmm. I can't reproduce the issue at the moment. I might have taken a screenshot (it could be in any one of eight or more home directories across six notebooks …)
