### ISSUE TITLE
With a panel to the left, positioning of initial windows may cause partial obscurity

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#324]
![screenshot-2016-12-17-13-45-11](https://cloud.githubusercontent.com/assets/192271/21287819/f52ce3b4-c46b-11e6-8131-9ba5bdb11d08.png)

![screenshot-2016-12-17-13-46-20](https://cloud.githubusercontent.com/assets/192271/21287822/059fd79c-c46c-11e6-9796-ab32a66730c7.png)

Both applications were launched _after_ the panel was in place.

```
$ uname -a
FreeBSD momh167-gjp4-hpelitebook8540p-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #6 3a85611(drm-next-4.7): Fri Dec 16 19:46:18 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ 
```

I see https://github.com/trueos/lumina/issues/202#issuecomment-195395819

> … Fluxbox… only understands one of the screen reservation protocols (entire screen side - crossing any monitor boundaries), instead of also understanding the partial screen reservation protocol.

– is that the underlying problem for this issue?

**Comment by q5sys** [comment]
This is a fluxbox issue and will be resolved with the forthcoming Lumina WM.
