### ISSUE TITLE
Rationalise the sizes and alignments of TrueOS and Lumina icons that can appear in a panel of Lumina

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#325]
## Background

An attempt to make a Lumina test environment resemble the layout that I prefer (in KDE) began with moving the one panel to the left of the screen. 

Essentially: I like an ever-present at-a-glance overview of the titles of all windows. (A pager of the type outlined at https://github.com/trueos/lumina/issues/318#issuecomment-266006381 may be comparable but that might be _on demand_, not present when required.)

## Issues arising

Much of what's below should be self-explanatory. I expect this Lumina panel-oriented issue to be **an umbrella for other, more specific issues** concerning the items that are represented by these icons. 

![screenshot-2016-12-17-13-44-24](https://cloud.githubusercontent.com/assets/192271/21287964/099d39cc-c46f-11e6-9adc-143fefca4dcc.png)

![screenshot-2016-12-17-13-52-27](https://cloud.githubusercontent.com/assets/192271/21287968/1fd812fc-c46f-11e6-9865-ebb28650473e.png)

![screenshot-2016-12-17-13-55-20](https://cloud.githubusercontent.com/assets/192271/21287971/31b34d52-c46f-11e6-9722-d465261a1eb2.png)

![screenshot-2016-12-17-13-56-16](https://cloud.githubusercontent.com/assets/192271/21287973/38eea7ba-c46f-11e6-9713-f010d599fd91.png)

Plus a screen recording, which was too large to upload: 

- https://drive.google.com/open?id=0B1G6-Ym42bEiakg2YVJPMi1zc0k

**Comment by grahamperrin** [comment]
> … I expect this Lumina panel-oriented issue to be an umbrella for other, more specific issues …

From https://discourse.trueos.org/t/disabling-pulseaudio/207/13?u=grahamperrin: 

> … with KDE, I thought that 'Mixer' was simply a word that appeared, alongside other things, when the audio icon is clicked. Tonight I discovered that the word responds to a click only if some types of pointer movement are avoided prior to the click. The same is true for the slider; if I'm not careful about how I move the pointer before the click on the slider, then the slider will not slide. …

**Comment by grahamperrin** [comment]
From [post 4](https://discourse.trueos.org/t/changing-keyboard-layout-in-x/647/4?u=grahamperrin) under _Changing Keyboard Layout in X_:

> … with KDE a **gb** icon is present in System Tray but it's almost impossible to use, as if I must click, double-click or right-click _away_ from (not on) the icon for its menu to appear; and even when I click _away_, more than ninety percent of attempts fail; and when eventually I _do_ get a menu, the **Configure** option fails to present anything.
> 
> I suspect that the **failures to recognise clicks** (or double-clicks, or right-clicks) in the expected position are a conflict with something in TrueOS, maybe indirectly related to this issue (325). 

And: 

> ### Side note: TrueOS mount tray
> 
> At the time of writing:
> 
> - the submenu option to **Change Settings** fails to present anything
> - the submenu option to **Close Tray** fails to close mount tray.

**Comment by beanpole135** [comment]
Done.
Please retest with the latest Lumina version from source and make a new ticket if the issue still persists.
