### ISSUE TITLE
Optional confirmation dialogue when deleting files without ZFS

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#326]
https://discourse.trueos.org/t/-/138/4

>> Lumina does not use the trash specifications since those specs were really designed for addressing limitations within old filesystems. …
>> 
>> If you delete a file within the Insight file manager, it is "really" deleted from the system, not sent to some trash folder.

Acknowledging that other file systems may be used with Lumina, from https://gitter.im/trueos/Lobby?at=5854d0557a3f79ef5d680eb9: 

> accidentally deleted a few files it was on an internal ext2 drive

Not just ext2. Users may naturally, frequently, work with FAT32, NTFS and other file systems that lack the qualities of ZFS. 

For these use cases it will be good to offer, by default, a **forewarning about the absence of a wastebasket** (or words to that effect) when a user aims to delete a file. Something to help the user realise that deletion will be immediate and irreversible.

**Comment by beanpole135** [comment]
The confirmation/warning about deleting files on the system is already a part of the file manager and has been since it's inception.

![screenshot-2016-12-19-08-46-47](https://cloud.githubusercontent.com/assets/4172864/21314962/d4ae3946-c5c7-11e6-8bac-bd597d0ad6d2.png)

**Comment by grahamperrin** [comment]
Oops! I should have checked before filing. (I assumed that 'accidental' meant without configuration.)
