### ISSUE TITLE
RSS Reader: no entry icon, no content from http://www.trueos.org/?feed=rss2

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#327]
http://www.trueos.org/?feed=rss2 is of two URLs that are present by default, with a clean installation of TrueOS Desktop, in the reader that is embedded in the desktop. 

There's no content, even after an explicit update of feeds. And a no entry icon. 

I experimented with https://www.trueos.org/feed/ (the address to which http://www.trueos.org/?feed=rss2 redirects when visited in Firefox). There's no content. A no entry icon does **not** appear.

**Comment by beanpole135** [comment]
It looks like the RSS feed from the TrueOS website got disabled or broken with a recent update. I have informed the site managers and they are working on it now.
