### ISSUE TITLE
Is there a way I can add some pad between the icon and the text in the right-click desktop menu?

### ISSUE THREAD

**Issue by bceverly** [trueos/lumina#333]
Hi,

I'm trying to run a hiDPI Lumina install on OpenBSD (Thinkpad X1 Carbon 4th Gen max resolution display) and I have managed to tweak everything to work like I would like it with the exception of one thing - when I right click on the desktop and the context menu pops up (the one that lets me fiddle with desktop settings, launch a terminal, etc.) the icon overlaps the text to the right of it.  Is there some setting I can tweak to get some extra padding in there?  I know it's a minor thing but it's triggering my CDO (because that's the order those letters should be in! <grin>).

Thanks in advance for any suggestions / help.

**Comment by beanpole135** [comment]
I have noticed that as well, and I think the stylesheet/theme for Lumina needs to have the QMenu "padding" property updated to fix this.
I will play around with this a bit and see what I can come up with for you... :-)

**Comment by bceverly** [comment]
Thank you sir!  Btw I am the maintainer of this port on OpenBSD - just wondering what the timeline is for the next release. I'm about to do some traveling and wasn't sure if I needed to keep an eye on things.

**Comment by beanpole135** [comment]
Ok, See if this fixes it for you (you can test without rebuilding just by applying the same change to your current Theme setting)[1].

I was planning on releasing Lumina 1.2.0 sometime at the beginning of the new year. Right now I am going through and auditing/testing/fixing things in preparation for that.

[1] https://github.com/trueos/lumina/commit/8e8a2393b16b6244b7f28f761effad16a9a0d0ca

**Comment by bceverly** [comment]
That was close, but 2em for both of them worked perfectly on my machine (Thinkpad X1 Carbon 4th Generation 2560x1440 resolution).

Thanks!

**Comment by beanpole135** [comment]
I just adjusted the Glass theme to use 2em for both left/right margins as well. Thanks for testing that and letting me know what worked!

**Comment by bceverly** [comment]
Thanks for an awesome DE Ken!

Some HiDPI variants of the window themes would be awesome. The title bars
are very small in most of them. I snagged some fluxbix themes from the
internet but didn't find any really good ones that worked on my X1 Carbon
4th gen.

**Comment by beanpole135** [comment]
Yeah, Fluxbox works based on pixel settings, and most of them are older themes for standard res monitors. For TrueOS Kris made a few 4K variants of common Fluxbox themes which you could probably use on OpenBSD too[1], but the ultimate plan is to depreciate/remove Fluxbox from Lumina entirely and go to a new Lumina-specific WM which is 4K aware/scalable out of box. I actually have the entire month of January blocked off to finish up the new WM systems, so hopefully I will have something ready for dev testing by the beginning of Feb or earlier. That is why I am trying to finish cleaning up this version of Lumina and release 1.2.0 at the beginning of Jan so I can put all my focus on the new systems... :-)

[1] https://github.com/trueos/trueos-core/tree/master/xtrafiles/local/share/fluxbox/styles/bora_blue_4k
Note that it is just a simple modification of the bora_blue Fluxbox theme (and copied into the "_4k" name/dir). You can do something similar for other themes really easily as well.
