### ISSUE TITLE
Duplication in Desktop Icons View

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#334]
[duplication.ogv.tar.gz](https://github.com/trueos/lumina/files/670066/duplication.ogv.tar.gz)

**Comment by beanpole135** [comment]
Text so people don't have to view the video file linked above:
The "Desktop Icons View" plugin for the desktop appears to make duplicates icons for each of the file entries.  There is no context given as to "when/how" this happened or steps to reproduce this issue.

**Comment by beanpole135** [comment]
I just tried this out on the latest TrueOS/Lumina and cannot reproduce this.
Things I tried (after adding the plugin to my desktop):
* Touch the ~/Desktop folder to trigger a resync
* Add/Remove files and symlinks from the ~/Desktop folder
* Resize/Move the plugin around the desktop

**Comment by grahamperrin** [comment]
Apologies for the terseness :-) I had a strong feeling that the bug would occur elsewhere, and now it has. 

> duplication.ogv.tar.gz

From the first frame of that video –

![23-41-20](https://cloud.githubusercontent.com/assets/192271/21466682/bb950140-c9ca-11e6-9685-b4a1e1882f23.png)

– I recognise the desktop environment of user _bbsadmin-l_ at computer _momh167-gjp4-hpelitebook8540p-trueos_, an HP EliteBook 8540p notebook. 

This morning I have the same problem with Lumina at a different computer, an Ergo Vista 621 notebook. I'll switch to that notebook and add details …

**Comment by q5sys** [comment]
Still unable to reproduce across at least five different systems.  I'm going to chalk this up to some odd config somewhere.
If you can reproduce this on a fresh install with no other userland tweaking, let us know and we'll re-open the ticket.
