### ISSUE TITLE
Window header can't show japanese text

### ISSUE THREAD

**Issue by everysh95** [trueos/lumina#335]
A header of Lumina desktop's window dose not work well on Japanese localization.
e.g. Window header's text on Japanese include box symbol.

**Comment by beanpole135** [comment]
This is a problem with Fluxbox and needs to be reported to them[1].

While I am not positive about the source of the issue, I would hazard a guess that Fluxbox is not using UTF-8 compatible fonts/strings.

[1] https://sourceforge.net/p/fluxbox/bugs/
