### ISSUE TITLE
Archive Manager does not close or quit in response to Escape, Control-W or Control-Q

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#338]
Gut feeling, it should respond: 

- to Control-W and Control-Q
- but not quit in response to Escape.

**Comment by q5sys** [comment]
The following keyboard shortcuts have been added to lumina-archiver:
Create new archive == CTRL+N
Open existing Archive == CTRL+O
Extract All == CTRL+E
Quit == CTRL+Q

https://github.com/trueos/lumina/commit/fab6d290cc1a94a351a12418373c3690cc8f0e43
