### ISSUE TITLE
Monitor Configuration: Rotation

### ISSUE THREAD

**Issue by mneumann** [trueos/lumina#341]
Add an icon, which allows to rotate the orientation (xrandr --rotate left|right|normal...).

**Comment by q5sys** [comment]
Ken is working on an updated monitor configuration utility and this functionality is slated to be included.  Thanks for filing the issue, sometimes things like this slip our minds and it's nice to have a friendly reminder from the community of end user needs like this.

**Comment by mneumann** [comment]
thanks!
