### ISSUE TITLE
lumina-config (Destkop Settings) does not close or quit in response to Control-W or Control-Q

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#344]
## Enhancement request

Please make the application respond to both shortcuts. Thanks.

**Comment by q5sys** [comment]
Added Ctrl-Q.  Crtl-W is not a standard shortcut for closing windows, it usually is used for closing tabs, like it is implemented in lumina-fm.  We are not going to conflate the two.

https://github.com/trueos/lumina/commit/e555ea9b7f21f1fe5ee03258c1ff8fd58cf7efbd

**Comment by grahamperrin** [comment]
Thanks! The quick fix is greatly appreciated. 

> Added Ctrl-Q. 

:+1: of the two, that one is most important. 

It smooths workflow when, for example, quitting a succession of applications (not necessarily all applications) before logout from a desktop environment. 

> Crtl-W is not a standard shortcut for closing windows, …

That's contrary to standards that I learnt, hands-on, over decades, with other operating systems. 

Without requesting a reopen of this particular issue: 

- for accessibility, consistency and predictability it will be important to get the most commonly used keyboard shortcuts 'feeling' right sooner rather than later (at 1.x, Lumina is relatively young)

– I'll take this to TrueOS community for discussion. 

Thanks again.
