### ISSUE TITLE
'lumina-desktop --show-start': 115 is not a keyboard shortcut

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#345]
![lumina-desktop --show-start 115](https://cloud.githubusercontent.com/assets/192271/21685189/7ef4d598-d358-11e6-86b5-97aff8c575e0.png)

(Ignore the leave dialogue, that's a separate issue.)

115 is apparent for me with at least four user accounts across two installations. Confirmed by another user at https://gitter.im/trueos/lumina?at=586e5f3bc895451b755bba69

**Comment by q5sys** [comment]
Not a bug.  That's the binding for the windows/super key.
