### ISSUE TITLE
OpenBSD port maintainer with question re: xcb/xinput.h

### ISSUE THREAD

**Issue by bceverly** [trueos/lumina#348]
Hi everyone,

I'm trying to update our port of Lumina to 1.2.0 and ran into a fairly significant (at least for me) roadblock and would appreciate some help from the larger brains here.

There is code in libLumina that appears to be walking a list of devices and determining whether they are keyboards, pointers, etc.  Unfortunately (unless there is something in our ports tree I'm not familiar with), it looks like our version of xorg does not contain this functionality.  I did manage to find our version of XInput.h which is in /usr/X11R6/include/X11/extensions but there are some key constants, types and functions that simply aren't there.  I've included the compiler output at the end of this for details.

Some questions:

1.  How critical is this functionality?  For example, could I simple stub out the methods in LInputDevice.cpp and call it a day?

2.  Is there another way of accomplishing this same thing (walking the list of devices, identifying what type they are) that I could use to code around this and create the correct behavior in an #ifdef instead of stubbing it out?

3.  Is there another way this could be implemented that didn't leverage this "missing" (at least from OpenBSD's perspective) functionality so that it could be common code and not a patch that we would need to maintain separately?

Thanks in advance for any suggestions / advice!

--- snip ---
===>  Building for lumina-1.2.0
cd src-qt5/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/src-qt5.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
cd core/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core/core.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
cd lumina-desktop/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core/lumina-desktop/lumina-desktop.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
cd lumina-session/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core/lumina-session/lumina-session.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
cd lumina-open/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core/lumina-open/lumina-open.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
cd lumina-info/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core/lumina-info/lumina-info.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
cd core-utils/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core-utils/core-utils.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
cd lumina-config/ && ( test -e Makefile || /usr/local/bin/qmake-qt5 /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core-utils/lumina-config/lumina-config.pro 'CONFIG+=configure WITH_I18N' -o Makefile ) && make -f Makefile all
g++ -c -pipe -O2 -Wall -W -pthread -fPIC -DPREFIX=QString\(\"/usr/local\"\) -DL_ETCDIR=QString\(\"/etc\"\) -DL_SHAREDIR=QString\(\"/usr/local/share\"\) -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB  -isystem /usr/local/lib/gcc/x86_64-unknown-openbsd6.0/4.9.4/include -I. -I../../core/libLumina -isystem /usr/local/include/X11/qt5 -I/usr/local/lib/qt5 -isystem /usr/local/include -I/usr/ports/pobj/lumina-1.2.0/lumina-1.2.0/src-qt5/core-utils/lumina-config -isystem /usr/local/include/X11/qt5/QtSvg -isystem /usr/local/include/X11/qt5/QtWidgets -isystem /usr/local/include/X11/qt5/QtX11Extras -isystem /usr/local/include/X11/qt5/QtMultimedia -isystem /usr/local/include/X11/qt5/QtGui -isystem /usr/local/include/X11/qt5/QtNetwork -isystem /usr/local/include/X11/qt5/QtConcurrent -isystem /usr/local/include/X11/qt5/QtCore -I. -I/usr/X11R6/include -I. -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/openbsd-g++ -o LInputDevice.o ../../core/libLumina/LInputDevice.cpp
../../core/libLumina/LInputDevice.cpp: In member function 'bool LInputDevice::isPointer()':
../../core/libLumina/LInputDevice.cpp:44:20: error: 'XCB_INPUT_DEVICE_USE_IS_X_POINTER' was not declared in this scope
   return (devType==XCB_INPUT_DEVICE_USE_IS_X_POINTER \
                    ^
../../core/libLumina/LInputDevice.cpp:45:14: error: 'XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_POINTER' was not declared in this scope
  || devType==XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_POINTER);
              ^
../../core/libLumina/LInputDevice.cpp: In member function 'bool LInputDevice::isKeyboard()':
../../core/libLumina/LInputDevice.cpp:49:20: error: 'XCB_INPUT_DEVICE_USE_IS_X_KEYBOARD' was not declared in this scope
   return (devType==XCB_INPUT_DEVICE_USE_IS_X_KEYBOARD \
                    ^
../../core/libLumina/LInputDevice.cpp:50:14: error: 'XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_KEYBOARD' was not declared in this scope
  || devType==XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_KEYBOARD);
              ^
../../core/libLumina/LInputDevice.cpp: In member function 'bool LInputDevice::isExtension()':
../../core/libLumina/LInputDevice.cpp:54:20: error: 'XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_DEVICE' was not declared in this scope
   return (devType==XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_DEVICE \
                    ^
../../core/libLumina/LInputDevice.cpp:55:14: error: 'XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_KEYBOARD' was not declared in this scope
  || devType==XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_KEYBOARD \
              ^
../../core/libLumina/LInputDevice.cpp:56:14: error: 'XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_POINTER' was not declared in this scope
  || devType==XCB_INPUT_DEVICE_USE_IS_X_EXTENSION_POINTER);
              ^
../../core/libLumina/LInputDevice.cpp: In member function 'void LInputDevice::getProperties()':
../../core/libLumina/LInputDevice.cpp:105:3: error: 'xcb_input_list_device_properties_cookie_t' was not declared in this scope
   xcb_input_list_device_properties_cookie_t cookie = xcb_input_list_device_properties_unchecked(QX11Info::connection(), devID);
   ^
../../core/libLumina/LInputDevice.cpp:106:3: error: 'xcb_input_list_device_properties_reply_t' was not declared in this scope
   xcb_input_list_device_properties_reply_t *reply = xcb_input_list_device_properties_reply(QX11Info::connection(), cookie, NULL);
   ^
../../core/libLumina/LInputDevice.cpp:106:45: error: 'reply' was not declared in this scope
   xcb_input_list_device_properties_reply_t *reply = xcb_input_list_device_properties_reply(QX11Info::connection(), cookie, NULL);
                                             ^
../../core/libLumina/LInputDevice.cpp:106:116: error: 'cookie' was not declared in this scope
   xcb_input_list_device_properties_reply_t *reply = xcb_input_list_device_properties_reply(QX11Info::connection(), cookie, NULL);
                                                                                                                    ^
../../core/libLumina/LInputDevice.cpp:106:128: error: 'xcb_input_list_device_properties_reply' was not declared in this scope
   xcb_input_list_device_properties_reply_t *reply = xcb_input_list_device_properties_reply(QX11Info::connection(), cookie, NULL);
                                                                                                                                ^
../../core/libLumina/LInputDevice.cpp:108:67: error: 'xcb_input_list_device_properties_atoms' was not declared in this scope
   xcb_atom_t *atoms = xcb_input_list_device_properties_atoms(reply);
                                                                   ^
../../core/libLumina/LInputDevice.cpp: In static member function 'static QList<LInputDevice*> LInput::listDevices()':
../../core/libLumina/LInputDevice.cpp:255:3: error: 'xcb_input_list_input_devices_cookie_t' was not declared in this scope
   xcb_input_list_input_devices_cookie_t cookie = xcb_input_list_input_devices_unchecked(QX11Info::connection());
   ^
../../core/libLumina/LInputDevice.cpp:256:3: error: 'xcb_input_list_input_devices_reply_t' was not declared in this scope
   xcb_input_list_input_devices_reply_t *reply = xcb_input_list_input_devices_reply(QX11Info::connection(), cookie, NULL);
   ^
../../core/libLumina/LInputDevice.cpp:256:41: error: 'reply' was not declared in this scope
   xcb_input_list_input_devices_reply_t *reply = xcb_input_list_input_devices_reply(QX11Info::connection(), cookie, NULL);
                                         ^
../../core/libLumina/LInputDevice.cpp:256:108: error: 'cookie' was not declared in this scope
   xcb_input_list_input_devices_reply_t *reply = xcb_input_list_input_devices_reply(QX11Info::connection(), cookie, NULL);
                                                                                                            ^
../../core/libLumina/LInputDevice.cpp:256:120: error: 'xcb_input_list_input_devices_reply' was not declared in this scope
   xcb_input_list_input_devices_reply_t *reply = xcb_input_list_input_devices_reply(QX11Info::connection(), cookie, NULL);
                                                                                                                        ^
../../core/libLumina/LInputDevice.cpp:260:3: error: 'xcb_input_device_info_iterator_t' was not declared in this scope
   xcb_input_device_info_iterator_t iter = xcb_input_list_input_devices_devices_iterator(reply);
   ^
../../core/libLumina/LInputDevice.cpp:264:9: error: 'iter' was not declared in this scope
   while(iter.data != 0 ){
         ^
../../core/libLumina/LInputDevice.cpp:268:53: error: 'xcb_input_device_info_next' was not declared in this scope
     if(iter.rem>0){ xcb_input_device_info_next(&iter); }
                                                     ^
../../core/libLumina/LInputDevice.cpp: In member function 'bool LInputDevice::isPointer()':
../../core/libLumina/LInputDevice.cpp:46:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../../core/libLumina/LInputDevice.cpp: In member function 'bool LInputDevice::isKeyboard()':
../../core/libLumina/LInputDevice.cpp:51:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../../core/libLumina/LInputDevice.cpp: In member function 'bool LInputDevice::isExtension()':
../../core/libLumina/LInputDevice.cpp:57:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
*** Error 1 in src-qt5/core-utils/lumina-config (Makefile:1069 'LInputDevice.o')
*** Error 1 in src-qt5/core-utils (Makefile:51 'sub-lumina-config-all')
*** Error 1 in src-qt5 (Makefile:76 'sub-core-utils-all')
*** Error 1 in /usr/ports/pobj/lumina-1.2.0/lumina-1.2.0 (Makefile:49 'sub-src-qt5-all')
*** Error 1 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2687 '/usr/ports/pobj/lumina-1.2.0/.build_done')
*** Error 1 in /usr/ports/x11/lumina (/usr/ports/infrastructure/mk/bsd.port.mk:2389 'all')

**Comment by beanpole135** [comment]
This same question came up with some Linux distro's too[1].

Basically, it looks like OpenBSD is stripping out the xinput class from the XCB library (one of the build arguments for the library?), which is why you don't have that functionality available even though it is a standard component of the library. 

Let me look into this a bit and see if I can add a compile-time flag to disable that functionality..

[1] https://github.com/trueos/lumina/issues/323

**Comment by beanpole135** [comment]
Ok - Try this now: https://github.com/trueos/lumina/commit/dc8e7acb08930a07c76ca700c1d70979c8a51db9

The new "NO_XINPUT" compile-time flag will disable the use of the xcb/xinput.h class (and disable the input device properties page in lumina-config) if your OS does not have that include file for some reason.

**Comment by beanpole135** [comment]
New release archive created for 1.2.0 which includes this change:
https://github.com/trueos/lumina/releases/tag/v1.2.0-p1

**Comment by bceverly** [comment]
Works on OpenBSD!  Thanks Ken!!

I'll submit the updates port tonight.
