### ISSUE TITLE
acpiconf instead of apm

### ISSUE THREAD

**Issue by mstuehn** [trueos/lumina#349]
It would be nice, if the battery-panel-plugin information would be taken from acpiconf(8) instead of apm(8). acpiconf(8) provides all the information which are shown at the moment but also additional infos like present rate and present voltage.

**Comment by q5sys** [comment]
do you know if acpiconf can distinguish between multiple batteries? If there is a way we can get the details from each separate battery we might be able to switch over.  I do like some of the extra information that acpiconf provides.

**Comment by mstuehn** [comment]
You can choose the battery by providing a number to the -i parameter like
`acpiconf -i 0`

**Comment by beanpole135** [comment]
Just a quick warning that for something like battery life polling which runs every few seconds, you need a tool that runs/returns incredibly fast with minimal overhead.

Using `apm` is a one-shot process call that satisfies the speed conditions, but switching to acpiconf looks like it might require a sequence of process calls with parsing in-between. I have not verified that this is indeed what happens, but my gut feeling is that this will end up increasing the baseline CPU usage of the system and reduce battery life of the system.

Another possibility is to link/use some acpi system library and run the functions directly - completely removing the process/parse requirements. This should make the polling itself trivial and reduce the baseline system overhead while also providing possibilities for retrieving additional information about the batteries.
