### ISSUE TITLE
1.2.0-p1 failed on Debian

### ISSUE THREAD

**Issue by pavroo** [trueos/lumina#351]
Due to problem with XINPUT, I tried 1.2.0 patch1 today on Debian stable Jessie 64bit.
The XINPUT passed through, but stuck with the message:
`Makefile:433: recipe for target 'TarBackend.o' failed
make[3]: *** [TarBackend.o] Error 1
make[3]: Leaving directory '/media/pavroo1/05ca0840-c5e5-45a1-b591-7e275319d1ac/builds/lumina/64-120p1/lumina-1.2.0-p1/src-qt5/desktop-utils/lumina-archiver'
Makefile:168: recipe for target 'sub-lumina-archiver-make_first' failed
make[2]: *** [sub-lumina-archiver-make_first] Error 2
make[2]: Leaving directory '/media/pavroo1/05ca0840-c5e5-45a1-b591-7e275319d1ac/builds/lumina/64-120p1/lumina-1.2.0-p1/src-qt5/desktop-utils'
Makefile:90: recipe for target 'sub-desktop-utils-make_first' failed
make[1]: *** [sub-desktop-utils-make_first] Error 2
make[1]: Leaving directory '/media/pavroo1/05ca0840-c5e5-45a1-b591-7e275319d1ac/builds/lumina/64-120p1/lumina-1.2.0-p1/src-qt5'
Makefile:38: recipe for target 'sub-src-qt5-make_first' failed
make: *** [sub-src-qt5-make_first] Error 2`
I used qmake flags: CONFIG+=NO_XINPUT CONFIG+=debug
and: CONFIG+=NO_XINPUT LINUX_DISTRO=Debian
I also can't find any error log.

**Comment by beanpole135** [comment]
The Debian package scripts in the Lumina repository were just updated a moment ago[1]. 
Feel free to re-try with that build recipe and see if that fixes it for you.

[1] https://github.com/trueos/lumina/pull/350

**Comment by pavroo** [comment]
Still no luck, and still the same output message.

**Comment by Nanolx** [comment]
Try without --parallel in debian/rules. This is likely to surpress the actual error message.

If you manually compile, do it using

`make -j1`

to force non-parallel build. You should when get a more meaningful error message.

**Comment by pavroo** [comment]
It's nothing about parallel.
I just cant't build it on Debian stable and testing (my primary environment).
I set *buntu 16.04 and the build was fine, with no problems.
and...
The debian/control's Depends sets libxcb-util1 as a dependency, but there is no lixcb-util1 in Debian and even nano repos - Debian offers libxcb-util0 instead. The libxcb-util1 is available in Ubuntu repos.
Anyway, built successfully and it's coming to sparky repos now.

**Comment by Nanolx** [comment]
There's no libxcb-util1 dependency, only libxcb-util0. But I left over references to libluminautils1, maybe that's what you mean, I just fixed this in my fork, waiting for @beanpole135 to merge (and uploading new packages soon)

And what I meant is, that parallel builds emits the warning message. So with parallel build you can't read what is wrong, of course it does not effect what is wrong. So I advised to do build non-parllel so you can get a more meaningful error message.

**Comment by pavroo** [comment]
I have built with parallel and without to compare it, but the error message is the same.

**Comment by beanpole135** [comment]
Note that @Nanolx 's updated pull request was just merged in.

**Comment by q5sys** [comment]
@pavroo @Nanolx 
Are either of you still having this issue?

**Comment by pavroo** [comment]
Don't know.
Build on Ubuntu was fine so haven't try again on Debian.

**Comment by q5sys** [comment]
@pavroo thanks for letting me know.  Ubuntu is based on Debian... so that's good enough for me.  If it's not fixed I'm sure someone else will report it in short order. :)
