### ISSUE TITLE
Lumina Text Editor: Missing Syntax Highlighting for Python

### ISSUE THREAD

**Issue by possnfiffer** [trueos/lumina#354]
At home I have PC-BSD 10.3-RELEASE installed running Lumina 0.9.0-Release. The Lumina Text Editor on there has Syntax Highlighting available for Python. At work I have TrueOS STABLE installed running whatever Lumina they're shipping(I can update this later) and the Lumina Text Editor is missing Syntax Highlighting for Python for some reason.

**Comment by beanpole135** [comment]
The "Python" syntax highlighting in the early version of the text editor was very early/untested, and was eventually converted into the ReST syntax highlighter.

I think a full Python syntax highlighter is not a bad idea though, so I am going to tag this as a feature request instead and leave it open for that.

**Comment by beanpole135** [comment]
FYI: If anybody wants to take a stab at this, the file to modify is: https://github.com/trueos/lumina/blob/master/src-qt5/desktop-utils/lumina-textedit/syntaxSupport.cpp

I think I still have the old "python" hooks still in there but commented out - those just need to be uncommented, fixed, and tested.

Uncomment line 12 to re-enable the python section of code (lines 166-204)

**Comment by beanpole135** [comment]
An "experimental" ruleset for syntax highlighting in python is now available for testing/fixing[1]. Feel free to try it out and make tweaks as necessary (please send the tweaks back in later so it works better for everyone)...

[1] https://github.com/trueos/lumina/blob/master/src-qt5/desktop-utils/lumina-textedit/syntax_rules/python.syntax
