### ISSUE TITLE
Feature Request: User-Defined Profiles for Panel Configs

### ISSUE THREAD

**Issue by PhiloPolyMath** [trueos/lumina#355]
Currently, there is no way to save a default or user-defined panel configuration. When one selects a configuration to emulate Windows, Mac, XFCE, etc. the current configuration is overridden and seems to be non-recoverable (no back or default settings button). It would be great to be able to create user-defined configurations so that one can save theirs and go back to it. Or at least a default profile saved along with the windows, xfce, mac, etc options so that a user can return to default settings if they decide to.

**Comment by Mrt134** [comment]
Update: work is almost finished on this feature: https://github.com/trueos/lumina/commit/ca225b7bd525ea961bf5aec2fa3f8c05e8307e4e#diff-a9efb41c2cf98ccc76f2f18849f74832

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/lumina/commit/909e7594e9e817c8602e8eade20ac2ade87deb44
