### ISSUE TITLE
Ubuntu (17.04) - error

### ISSUE THREAD

**Issue by myswiat** [trueos/lumina#356]
../libLumina/ExternalProcess.h: In destructor ‘virtual ExternalProcess::~ExternalProcess()’:
../libLumina/ExternalProcess.h:37:12: error: ‘class ExternalProcess’ has no member named ‘detach’
      this->detach(); //about to close down the QProcess - detach the other program so it can continue functioning normally.
Makefile: 1478: command object 'moc_ExternalProcess.o' failed
make [3]: *** [LSession.o] Error 1
make [3]: *** Waiting for unfinished jobs....
In file included from LSession.cpp:19:0:
../libLumina/ExternalProcess.h: In destructor ‘virtual ExternalProcess::~ExternalProcess()’:
../libLumina/ExternalProcess.h:37:12: error: ‘class ExternalProcess’ has no member named ‘detach’
      this->detach(); //about to close down the QProcess - detach the other program so it can continue functioning normally.
Makefile: 1478: command object 'LSession.o' failed
make [3]: *** [LSession.o] Error 1

**Comment by beanpole135** [comment]
That was a temporary bug which snuck into the master branch and has already been corrected.
If you are packaging Lumina for Ubuntu 17.04, please use the stable "qt5/1.2.0" branch instead of master. The master branch is where ongoing development happens and there is a high possibility of temporary bugs like this which sneak in from time to time.

**Comment by myswiat** [comment]
I have another problem. master version, and version 1.2.0-p1 - the same error.
Ubuntu 17.04 (dev), qt 5.7.1.

Compilation on arch linux proceeds with no errors.

/usr/lib/x86_64-linux-gnu/qt5/bin/qmake QMAKE_CFLAGS_ISYSTEM= PREFIX=/usr QT5LIBDIR=/usr/lib/x86_64-linux-gnu/qt5 -o Makefile lumina-xconfig.pro
Project MESSAGE: Build OS Info: Linux, x86_64, #13-Ubuntu SMP Mon Jan 9 20:06:25 UTC 2017
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h:48:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDesktopWidget:1,
                 from ../../core/libLumina/LUtils.h:23,
                 from ../../core/libLumina/LInputDevice.cpp:20:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h:48:2: error: #error qdatastream.h must be included before any header file that defines Status
 #error qdatastream.h must be included before any header file that defines Status
  ^~~~~
Project MESSAGE: Build Settings Loaded: Linux -Ubuntu
make[3]: Nie ma nic do zrobienia w 'first'.
make[3]: Opuszczenie katalogu '/home/xxx/lumina/src-qt5/core-utils/lumina-xconfig'
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DPREFIX=QString\(\"/usr\"\) -DL_ETCDIR=QString\(\"/usr/etc\"\) -DL_SHAREDIR=QString\(\"/usr/share\"\) -DGIT_VERSION="\"96a50ddc\"" -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../../core/libLumina -I/usr/include/x86_64-linux-gnu/qt5 -I/usr -I/usr/include -I/home/xxx/lumina/src-qt5/core-utils/lumina-config -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o page_main.o pages/page_main.cpp
In file included from /usr/include/xcb/xproto.h:15:0,
                 from ../../core/libLumina/LInputDevice.h:19,
                 from ../../core/libLumina/LInputDevice.cpp:7:
/usr/include/xcb/xcb.h:366:7: error: ‘xcb_query_extension_reply_t’ does not name a type
 const xcb_query_extension_reply_t *xcb_get_extension_data(xcb_connection_t *c, xcb_extension_t *ext);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/xcb/xcb.h:402:7: error: ‘xcb_setup_t’ does not name a type
 const xcb_setup_t *xcb_get_setup(xcb_connection_t *c);
       ^~~~~~~~~~~
In file included from /usr/include/X11/Xlib.h:44:0,
                 from /usr/include/xcb/xinput.h:52,
                 from ../../core/libLumina/LInputDevice.cpp:17:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:63:9: error: expected identifier before numeric constant
         None = 0,                               // invalid event
         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:63:9: error: expected ‘}’ before numeric constant
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:63:9: error: expected unqualified-id before numeric constant
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:51:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
                 from ../../core/libLumina/LInputDevice.h:17,
                 from ../../core/libLumina/LInputDevice.cpp:7:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:123:5: error: ‘friend’ used outside of class
     friend Q_DECL_CONSTEXPR const QMetaObject *qt_getEnumMetaObject(ENUM) Q_DECL_NOEXCEPT { return &staticMetaObject; } \
     ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:125:30: note: in expansion of macro ‘Q_ENUM_IMPL’
 #define Q_ENUM(x) Q_ENUMS(x) Q_ENUM_IMPL(x)
                              ^~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(Type)
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:123:73: error: ‘constexpr const QMetaObject* const qt_getEnumMetaObject’ redeclared as different kind of symbol
     friend Q_DECL_CONSTEXPR const QMetaObject *qt_getEnumMetaObject(ENUM) Q_DECL_NOEXCEPT { return &staticMetaObject; } \
                                                                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:125:30: note: in expansion of macro ‘Q_ENUM_IMPL’
 #define Q_ENUM(x) Q_ENUMS(x) Q_ENUM_IMPL(x)
                              ^~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(Type)
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:123:48: note: previous declaration ‘constexpr const QMetaObject* qt_getEnumMetaObject(QLocale::MeasurementSystem)’
     friend Q_DECL_CONSTEXPR const QMetaObject *qt_getEnumMetaObject(ENUM) Q_DECL_NOEXCEPT { return &staticMetaObject; } \
                                                ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:125:30: note: in expansion of macro ‘Q_ENUM_IMPL’
 #define Q_ENUM(x) Q_ENUMS(x) Q_ENUM_IMPL(x)
                              ^~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h:892:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(MeasurementSystem)
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:12: error: ‘Type’ was not declared in this scope
     Q_ENUM(Type)
            ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:123:69: note: in definition of macro ‘Q_ENUM_IMPL’
     friend Q_DECL_CONSTEXPR const QMetaObject *qt_getEnumMetaObject(ENUM) Q_DECL_NOEXCEPT { return &staticMetaObject; } \
                                                                     ^~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(Type)
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:124:5: error: ‘friend’ used outside of class
     friend Q_DECL_CONSTEXPR const char *qt_getEnumName(ENUM) Q_DECL_NOEXCEPT { return #ENUM; }
     ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:125:30: note: in expansion of macro ‘Q_ENUM_IMPL’
 #define Q_ENUM(x) Q_ENUMS(x) Q_ENUM_IMPL(x)
                              ^~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(Type)
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:124:60: error: ‘constexpr const char* const qt_getEnumName’ redeclared as different kind of symbol
     friend Q_DECL_CONSTEXPR const char *qt_getEnumName(ENUM) Q_DECL_NOEXCEPT { return #ENUM; }
                                                            ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:125:30: note: in expansion of macro ‘Q_ENUM_IMPL’
 #define Q_ENUM(x) Q_ENUMS(x) Q_ENUM_IMPL(x)
                              ^~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(Type)
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:124:41: note: previous declaration ‘constexpr const char* qt_getEnumName(QLocale::MeasurementSystem)’
     friend Q_DECL_CONSTEXPR const char *qt_getEnumName(ENUM) Q_DECL_NOEXCEPT { return #ENUM; }
                                         ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:125:30: note: in expansion of macro ‘Q_ENUM_IMPL’
 #define Q_ENUM(x) Q_ENUMS(x) Q_ENUM_IMPL(x)
                              ^~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h:892:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(MeasurementSystem)
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:12: error: ‘Type’ was not declared in this scope
     Q_ENUM(Type)
            ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:124:56: note: in definition of macro ‘Q_ENUM_IMPL’
     friend Q_DECL_CONSTEXPR const char *qt_getEnumName(ENUM) Q_DECL_NOEXCEPT { return #ENUM; }
                                                        ^~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:293:5: note: in expansion of macro ‘Q_ENUM’
     Q_ENUM(Type)
     ^~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h:47:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QCoreApplication:1,
                 from ../../core/libLumina/LUtils.h:10,
                 from ../../core/libLumina/LInputDevice.cpp:20:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:295:26: error: expected ‘)’ before ‘type’
     explicit QEvent(Type type);
                          ^~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:296:12: error: expected unqualified-id before ‘const’
     QEvent(const QEvent &other);
            ^~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:296:12: error: expected ‘)’ before ‘const’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:297:21: error: declaration of ‘~QEvent’ as non-member
     virtual ~QEvent();
                     ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:298:42: error: ‘QEvent& operator=(const QEvent&)’ must be a nonstatic member function
     QEvent &operator=(const QEvent &other);
                                          ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:299:12: error: ‘Type’ does not name a type
     inline Type type() const { return static_cast<Type>(t); }
            ^~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:300:31: error: non-member function ‘bool spontaneous()’ cannot have cv-qualifier
     inline bool spontaneous() const { return spont; }
                               ^~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: In function ‘bool spontaneous()’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:300:46: error: ‘spont’ was not declared in this scope
     inline bool spontaneous() const { return spont; }
                                              ^~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: In function ‘void setAccepted(bool)’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:302:46: error: ‘m_accept’ was not declared in this scope
     inline void setAccepted(bool accepted) { m_accept = accepted; }
                                              ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: At global scope:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:303:30: error: non-member function ‘bool isAccepted()’ cannot have cv-qualifier
     inline bool isAccepted() const { return m_accept; }
                              ^~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: In function ‘bool isAccepted()’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:303:45: error: ‘m_accept’ was not declared in this scope
     inline bool isAccepted() const { return m_accept; }
                                             ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: In function ‘void accept()’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:305:28: error: ‘m_accept’ was not declared in this scope
     inline void accept() { m_accept = true; }
                            ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: In function ‘void ignore()’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:306:28: error: ‘m_accept’ was not declared in this scope
     inline void ignore() { m_accept = false; }
                            ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: At global scope:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:310:1: error: expected unqualified-id before ‘protected’
 protected:
 ^~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:314:1: error: expected unqualified-id before ‘private’
 private:
 ^~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:316:18: error: expected initializer before ‘:’ token
     ushort spont : 1;
                  ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:317:21: error: expected initializer before ‘:’ token
     ushort m_accept : 1;
                     ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:318:21: error: expected initializer before ‘:’ token
     ushort reserved : 13;
                     ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:320:5: error: ‘friend’ used outside of class
     friend class QCoreApplication;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:321:5: error: ‘friend’ used outside of class
     friend class QCoreApplicationPrivate;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:322:5: error: ‘friend’ used outside of class
     friend class QThreadData;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:323:5: error: ‘friend’ used outside of class
     friend class QApplication;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:324:5: error: ‘friend’ used outside of class
     friend class QShortcutMap;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:325:5: error: ‘friend’ used outside of class
     friend class QGraphicsView;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:326:5: error: ‘friend’ used outside of class
     friend class QGraphicsScene;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:327:5: error: ‘friend’ used outside of class
     friend class QGraphicsScenePrivate;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:329:5: error: ‘friend’ used outside of class
     friend class QSpontaneKeyEvent;
     ^~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: In function ‘void setSpontaneous()’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:332:29: error: ‘spont’ was not declared in this scope
     void setSpontaneous() { spont = true; }
                             ^~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h: At global scope:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:333:1: error: expected declaration before ‘}’ token
 };
 ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h:308:16: warning: ‘int registerEventType(int) noexcept’ declared ‘static’ but never defined [-Wunused-function]
     static int registerEventType(int hint = -1) Q_DECL_NOTHROW;
                ^~~~~~~~~~~~~~~~~
Makefile: 950: command object 'LInputDevice.o' failed
make [3]: *** [LInputDevice.o] Error 1
make [3]: *** Waiting for unfinished jobs....

**Comment by beanpole135** [comment]
That appears to be related to the xcb/xinput class usage again. You need to run qmake with the "NO_XINPUT" build flag to skip that class/functionality.

I am actually planning on disabling that class/functionality here soon anyway, since trying to use X11 to manage the input devices simply does not work on a number of operating systems (needs to be OS-specific: `moused` handles it best on FreeBSD, and I am sure that other OS's use other mouse-control daemons as well).
