### ISSUE TITLE
Lumina does not startup in Xvnc

### ISSUE THREAD

**Issue by berlineddy** [trueos/lumina#357]
Lumina does not startup correctly on an Xvnc.

the `~/vnc/xstartup` file:

    #!/bin/sh
    start-lumina-desktop 2> ~/lumina.log

the log file:

    > cat lumina.log
    Starting the Lumina desktop on current X11 session: ":1"
    Found Desktop Lock for X session: ":1"
     - Disabling Lock and starting new desktop session
     - Resetting monitor configuration to last-used settings
     - Starting the session...
    Watch Files for changes: "wm" ("/usr/home/eddy/.config/lumina-desktop/fluxbox-init", "/usr/home/eddy/.config/lumina-desktop/fluxbox-keys")
    Detected GPU Acceleration: false
    Finished Closing Down Lumina

__it looks like lumina is started and immediately closed.__ 

I also tried to put `exec xterm` in `~/vnc/xstartup` then after connection typed `start-lumina-desktop`. This opens the startup loading screen of lumina but after 0.5 seconds closes it with the same messages.

the only way i found to run lumina in an Xvnc is thsi `~/vnc/xstartup` :

    exec startfluxbox 
    exec start-lumina-desktop

but this will first open a full fluxbox with bars and background ad everything and then run the lumina desktop on top of it.

**Comment by berlineddy** [comment]
result after debugging:

start-lumina-desktop relies on the xorg RANDR extention. this is not loaded by the default vnc server. The solution is to use `tigervnc` as the vnc server.

**Comment by q5sys** [comment]
@berlineddy Thanks for the info. I'll pass that along when others run into this issue.  I appreciate you reporting back. :)
