### ISSUE TITLE
Text impossible small on a 42" 1080p TV used as monitor trough HDMI

### ISSUE THREAD

**Issue by roony1974** [trueos/lumina#361]
I have tested PC-BSD and TrueOS and both have same problem with text being so small that it is impossible to read because text is small and distorted (font size 1). I see other have the same issue but no one have any clear instructions to follow that you can do in the blind...

**Comment by RodMyers** [comment]
before logging, at the PCDM prompt. look in the lower right corner. there will be a "button".

click on it, and you can change DPI for you logged in session

**Comment by q5sys** [comment]
Try this:  When are at the login screen, there a power button icon in the bottom right corner.  Click it (dont worry it wont shut down your system).  A little menu will pop up and you can change your DPI.  The default should be 96 DPI, try changing this and see if one of the other options gives you a better result.  Let me know if this helps or not.

**Comment by roony1974** [comment]
Thank, the bottom right corner setting dpi before logging in worked.

**Comment by q5sys** [comment]
Thanks for reporting back!
