### ISSUE TITLE
"Open with ..." - Feature request for Lumina Screenshot

### ISSUE THREAD

**Issue by utrenkner** [trueos/lumina#362]
Lumina Screenshot is nice and handy. Good job!

But I am a year-long user of GIMP and would love to see a button such as "Open screenshot with ..." so that I could jump directly to my preferred image editor. Alternatively: To be able to configure, whether "edit" opens the internal editor or my preferred external editor.

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/lumina/commit/a0572cf5076bbc20248018e98f0faee5a9a644da
