### ISSUE TITLE
lumina-config: at a Locations page of the Panels pane of Desktop Settings, clicking Save causes a switch away from the required page

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#363]
[2017-01-28 issue with the panels pane of Desktop Settings.ogv.zip](https://github.com/trueos/lumina/files/721378/2017-01-28.issue.with.the.panels.pane.of.Desktop.Settings.ogv.zip) – screen recording, thirty-seven seconds. 

Three frames from that recording: 

![one](https://cloud.githubusercontent.com/assets/192271/22176697/0d3dcac4-e008-11e6-9fac-ef9635d4fb20.png)

![two](https://cloud.githubusercontent.com/assets/192271/22176700/13504f90-e008-11e6-9acb-0a47de45155a.png)

![three](https://cloud.githubusercontent.com/assets/192271/22176703/174069f0-e008-11e6-8908-245811063738.png)

**Comment by beanpole135** [comment]
Just for clarification about what you are reporting as a bug:
The currently-selected tab for the various panels will *change* when you save your current settings?

**Comment by grahamperrin** [comment]
Confirmed. The change, away from what was selected by the user, is unexpected.
