### ISSUE TITLE
Feature Request: Configurable Icon for Start Menu

### ISSUE THREAD

**Issue by coppolajj** [trueos/lumina#364]
I'd like to be able to change the icon for the start menu button.

**Comment by q5sys** [comment]
You can accomplish this by using Lumina-Config and the setting "Change User Icon" 
See: https://lumina-desktop.org/handbook/luminaconfig.html#general-options

if you run into any problems with this, let us know. :)

**Comment by coppolajj** [comment]
I originally tried that but when selecting ChangeUserIcon it initially updates the image but the selection doesn't seem to be stored, when I select Save and then BackToSettings and then return to GeneralOptions the selection is gone.  I'm selecting a .png, and I'm running on FreeBSD11 (Desktop Version 1.1.0).

**Comment by q5sys** [comment]
thanks for reporting back, we'll look into it.

**Comment by beanpole135** [comment]
When you assign a user icon, it just places a formatted version of the image you selected into your home directory at `~/.loginIcon.png`. This icon will be used by some graphical login managers (PCDM, KDM?) in addition to the "User Menu" plugin in Lumina. The "Start Menu" and "Application Menu" plugins will use the "start-here-lumina" icon (either from the current theme, or put into the (Local PREFIX)/share/pixmaps directory). If you want to provide an alternate icon for those menu's, I recommend copying an image over to the pixmaps dir (or just making a symlink). That is actually how TrueOS handles it's custom start menu icon as well.

**Comment by coppolajj** [comment]
thanks! this got me what I wanted.  But FYI, in case others are looking into this see below.

On my system (FreeBSD 11 with Lumina 1.1.0):
1) `~/.loginIcon.png` does not exist in my file system.  I do have a `~/.face.icon`, and when I rename it to `~/.loginIcon.png` then the correct image shows up in the UserMenu and also in UserSettings>GeneralOptions, so there seems to be something funny going on with the file name.
2) in `/usr/local/share/pixmaps` I don't have a `start-here-lumina` icon but I do have a `Lumina-DE.png` that I was able to replace with my preferred icon.

Thanks for the help!

**Comment by beanpole135** [comment]
I just fixed the issue where the ~/.loginIcon.png file was not getting saved properly by lumina-config.
Thanks for pointing that out!

https://github.com/trueos/lumina/commit/80032c31b1b99717206773234ea1bd1d9e807684
