### ISSUE TITLE
Keyboard Layout Not Reflected After Logging In

### ISSUE THREAD

**Issue by sgeos** [trueos/lumina#365]
```
$ uname -a
FreeBSD hexahedrite.sennue.com 12.0-CURRENT FreeBSD 12.0-CURRENT #18 4f888bf(drm-next): Wed Jan 18 14:31:26 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
```

The keyboard layout selected on the graphical login screen is not used in the X session after logging in.  On the login screen, I select the "Japanese - (jp)" keyboard layout with the "<none>" variant.  The preview works fine.  After clicking apply and logging in a US keyboard layout is in effect.  Note that the JP layout is preselected if I reopen the keyboard layout selection, so the selection appears to be persisted.  This is a TrueOS install on a T530.  Incidentally the locale is set to ja_JP.

Note that this is an issue with keyboard layout.  In other words, where is the + key?  Shift = by delete on a US layout VS shift ; next to L on a JP layout.  fcitx can be used as an IME to enter Japanese text.  This works.  The issue is the keyboard layout.

Reference image:
http://www.dtp-transit.jp/images/apple-keyboards-US-JIS.jpg

Also note that `setxkbmap -layout jp` can be used to temporarily change the keyboard layout in a terminal.  The keyboard reverts to a US layout as soon as I switch to another window like Chrome.  (I'm pretty sure it is a US layout.)  At this point the US layout is still in effect even if I switch back to the terminal.  This leads me to believe that the layout is being managed at a session level, but it is using a US layout instead of the value specified on the login screen.

**Comment by sgeos** [comment]
The same problem happens in Fluxbox.  The keyboard keeps changing back to US in KDE, and the visual indicator may display what is happening in Lumina/Fluxbox.  At this point I am not convinced that this is a Lumina issue, but there is definitely something very wonky going on with the TrueOS keyboard layout.

**Comment by beanpole135** [comment]
This is very intriguing, and most likely a problem in PCDM (not passing through some ENV variable to the desktop session would be my guess).

PCDM is just running `setxkbmap` to change the keyboard layout, and I am looking to see if that sets any particular environment variables on the current session now.

**Comment by beanpole135** [comment]
Ok, `setxkbmap` does not appear to use environment variables, and running it within one terminal *does* appear to change it for a separate terminal session (so that makes it appear like a property on the X session itself - which is the correct way to do it).
The only other thing that PCDM does to the X session when starting up the user desktop is change some xauth permissions settings before and after dropping to user priviledges. Let me experiment with this a bit - we might just need to setup the desktop-init routine to re-run `setxkbmap` with the previous settings.

**Comment by beanpole135** [comment]
Ok, this seems to be fixed in PCDM now after a bit of testing:

https://github.com/trueos/pcdm/commit/e86ade44860d441540de55489ff0a8b1c9eca2c9
