### ISSUE TITLE
Opting to save should not cause presentation of an 'Open with …' dialogue

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#372]
## Steps

1. launch Lumina Screenshot
2. Quick Save

## Expected

- a save, nothing more; emphasis on the word _quick_.

## Actual result

- some time (not quickly) after the click on Quick Save, an 'Open with …' dialogue. 

I wonder whether this issue is an unintended consequence of the commit that closed https://github.com/trueos/lumina/issues/362

**Comment by q5sys** [comment]
I'll take a look at this once I finish my drive down to TN today.  Thanks for reporting it.  Quick Save should save the file only.

**Comment by beanpole135** [comment]
I fixed this by removing the "Quick Save" button a few minutes ago. The whole point of that button was originally to save a file and instantly open it within some other application. When I made the new "Open With" button as the front-end for that functionality I just forgot to remove the "Quicksave" action from the UI.
