### ISSUE TITLE
Windows "disappear"

### ISSUE THREAD

**Issue by markusalbertgraf** [trueos/lumina#381]
Hi,
most of my Lumina Sessions end with windows disappearing after a few hours.
I mostly work with emacs in fullscreen (F11) and Firefox, also mostly fullscreen (F11).
I have KDE installed in parallel since this "windows disappearing" causes Lumina to loose my work every time it happens.
I use two screens, a laptop screen and an external Samsung monitor.
I use Alt-tab to switch between Applications. 
Most sessions end by open Applications not being selectable by Alt-Tab anymore. In most cases the Task-Bar vanishes when this happens. Once this starts it never becomes better but more open Applications (mostly multiple Firefox Windows and Emacs) start vanishing. I can not bring these windows back. Work in progress in them is lost. The context menu, when I right-click on the desktop, still lists all Windows as existing but I can not bring them back. Ending the session and loosing all work in progress is the only option.

about
  ______                   ____  _____
 /_  __/______  _____     / __ \/ ___/ 
  / / / ___/ / / / _ \   / / / /\__ \ 
 / / / /  / /_/ /  __/  / /_/ /___/ / 
/_/ /_/   \__,_/\___/   \____//____/  

General info:
       Host:...............trueos-Laptop.markusgraf.net
       User:...............markus
       Uptime:.............3:35
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....27d3221
       TrueOS ver:.........TrueOS-Desktop-201702011813
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....EFI
       CPU:................Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
       CPU cores:..........4
       Memory (free/avail):14028 / 16384 Mb
       Package set:........STABLE
       Desktop environment:Lumina
       X11 Driver:.........modesetting_drv.so 
       OSS Driver:.........pcm0: <Realtek ALC269 (Analog 2.0+HP/2.0)> (play/rec) default
       WIFI Driver:........iwm0

**Comment by markusalbertgraf** [comment]
This time the Taskbar has vanished, but I can still reach the two open windows, one emacs fullscreen, one firefox fullscreen with multiple tabs open. Right-click on the desktop lists both windows and clicking them brings them back fullscreen to their respective screens.
-------------------------
Just now I used the "minimise" Button on the firefox and the taskbar is back. And I could bring the firefox to fullscreen again. System uptime is 6 hours 31 minutes.

**Comment by markusalbertgraf** [comment]
I had the vanishing taskbar reproducable. Then I go interruptet. Now it is not reproducable any more.
Both times firefox fullscreen laptopscreen, emacs fullscreen external monitor.
Case 1:
When I press alt-f2 the search window is opened invisibly and I need to press alt-tab, sometimes multiple times, to get to it. But always, when I get to it, it does not show in front of one of the other windows but one of the other windows minimizes and the search-window is shown with the desktop as background. When I press alt-tab while the search window with the desktop as background is visible, the taskbar vanishes, leaving a desktop without taskbar. Closing the search window, alt-tabbing to two fullscreen windows and then using the minimize Button on Firefox brings the taskbar back.
Case 2:
When I press alt-f2 one of the windows minimizes immediately and gets replaced by the search-box in front of the desktop. If this happens the taskbar never vanishes.

I had Case one reproducible two hours ago. I have not rebooted since but now I am in case 2.

I suspect, that something, which has to do with fullscreen windows, minimizes windows and blocks bringing them back again while making the taskbar vanish. Today is only the second time the vanishing taskbar came back. The two windows I have always open bring their own fullscreen (f11). Not the lumina fullscreen (alt-f11).

**Comment by beanpole135** [comment]
Could you verify that Fluxbox is still running when this happens?
Example: `top` or `ps -auwwx | grep fluxbox`

Those are typically indications that the WM (Fluxbox) is no longer running and managing the window layers.

**Comment by markusalbertgraf** [comment]
Rambling protocol in the hope that it helps:

When I play with it now, I can get the task bar to disappear. fluxbox is still there.
I think there may be different issues at play here. The set of windows cycled by alt-tab seems to change. e.g. when I want to change to emacs and start with window A being active, when I hold down alt and press tab repeatedly emacs never shows up, but B, on the other screen, does. If i switch to B, hold down alt again and press tab repeatedly emacs is among the windows being cycled. Both B and emacs were on the same screen and both in fullscreen. However the blank desktop of the screen containing both emacs and B was in the first set being cycled when emacs was not among the cycled windows.

More weirdness:
After I took the windows out of fullscreen they were all there once. Taskbar was still gone. After I alt-tabbed to this window to continue writing this. I could not get back to emacs where the shell is to pgrep fluxbox. I opened a terminal and all windows except the terminal and one firefox window where inaccessible. The terminal showed fluxbox is still running.
Since I put the terminal into fullscreen it got worse. Since I returned the terminal from fullscreen everything is back.
So I had all symptoms again, all at once. And they all vanished by putting the terminal into fullscreen and coming back from fullscreen.
The Terminal is QTerminal 0.7.0.

Now it got so bad, that I had two blank desktops again, Taskbar gone. Alt-tabbing got me nothing. swiching to a virtual console showed fluxbox still running.
Right-clicking on the desktop and selecting open windows did not bring the windows to the desktops.
Then left-clicking on the laptop-screen brought back the taskbar.
Alt-Tabbing still did not bring me the windows. But windows on the external monitor show up with a one pixel line on the side of the laptop screen. This was there when I alt-tabbed. *this means, that the laptop screen was convinced that the external monitor showed the window though it showed a desktop*. Left-clicking on the desktop of the external monitor brought made the window visible again, and I am typing in this window at the moment.
So question: when I alt-tab, should there be empty desktops in the sequence? I definitely have them.

**Comment by beanpole135** [comment]
Your symptoms basically describe what happens when Fluxbox does not respect the special window flags on the Lumina windows (virtual roots, always on bottom/top, sticky, etc...). 
How are you launching Lumina? What version of Lumina are you running? (`lumina-desktop --version`)

**Comment by markusalbertgraf** [comment]
lumina-desktop --version
"1.2.1"
I just installed trueOS from the image in December.
I do not know where or how lumina gets started.
in /etc/ttys ttyv8 is set to off, so it must be started from someplace else

**Comment by beanpole135** [comment]
Are you logging in graphically? If so, then you are probably using PCDM - which is doing the right thing to launch it - so that seems right...

**Comment by markusalbertgraf** [comment]
I log on graphically, there is a process PCDM-session when I am in the login-screen.

**Comment by markusalbertgraf** [comment]
there is three lumina processes:
start-lumina-desktop
lumina-open
lumina-desktop
PDCM-session stays while in the lumina session.

**Comment by beanpole135** [comment]
yes, that is normal:
PCDM-session -> start-lumina-desktop -> lumina-desktop
lumina-open is used for launching apps and opening files - so you will see those for various things started after-the-fact.

**Comment by q5sys** [comment]
Are you still having this issue on the latest sources?

**Comment by markusalbertgraf** [comment]
Thanx for coming back to me!!
I am sorry to tell you that I reinstalled my machine to freebsd when I could not resolve my jvm problems on trueos.
