### ISSUE TITLE
Incorrect value for some language attributes in som TS files

### ISSUE THREAD

**Issue by scootergrisen** [trueos/lumina#382]
It seems like there are some problems with a few of the language strings in some ts files:
```
<TS version="2.1" language="l-screenshot_el">
<TS version="2.1" language="lumina-config_fa">
<TS version="2.1" language="lumina-config_el">
<TS version="2.1" language="lumina-desktop_fa">
```

**Comment by beanpole135** [comment]
I just re-synced all the various translation files with the latest sources.
Please re-test this and see if those files still have any issues.

**Comment by scootergrisen** [comment]
Still there.
I tried changing "l-te_da" to "da" in one of the files and upload to weblate but it does not change it on weblate.

**Comment by beanpole135** [comment]
Fixed! 

https://github.com/trueos/lumina/commit/3a2f9cf23880d4d6849924dce97dc3277a25711f

**Comment by scootergrisen** [comment]
There is also:
```
l-te_da
l-te_el
```
