### ISSUE TITLE
qmake don't give much output on Debian

### ISSUE THREAD

**Issue by scootergrisen** [trueos/lumina#384]
https://lumina-desktop.org/get-lumina/#source-debian tells me to use:
`qmake LINUX_DISTRO=Debian`

But i can't seem to get the "Build OS Info" message described on:
https://github.com/trueos/lumina#how-to-build-from-source

Running qmake the firste time gives:
`Info: creating stash file [...]/lumina2/.qmake.stash`

Running qmake again gives no output.
So perhaps the output could be better to let the user know if things are OK or not.

**Comment by beanpole135** [comment]
Done!
If you cd into the src-qt5 directory first, then you will get that output. I just updated the top-level redirect project file to also load the OS detection file so you can see the output there too.
