### ISSUE TITLE
Perhaps make a Contribute/Translate page so people can know what can be translated

### ISSUE THREAD

**Issue by scootergrisen** [trueos/lumina#386]
I have made work in the danish Lumina translation and now that it it pretty good i look for other things to translate.

How about the "*.desktop" files should those not be translated?
Like https://github.com/trueos/lumina/blob/master/src-qt5/core-utils/lumina-config/lumina-config.desktop and so on.

Perhaps someone could collect information on what needs translation and add a "Contribute" page on https://lumina-desktop.org/

**Comment by scootergrisen** [comment]
Would we perhaps make it so that strings used in the desktop files are included in the same place (weblate) as the other translations.
So that its easier for translators to add translations for the desktop files instead of having to edit like 10-20 desktop files they could just have the strings on weblate and the strings would be taken from weblate to create the desktop files.

**Comment by q5sys** [comment]
I'm not sure exactly how weblate is tied into our build system, but I'll look into this next week.  This sounds like something we should be doing.

**Comment by ZackaryWelch** [comment]
Thanks for your contributions to the project. Translating .desktop files is an interesting idea that I will look into. As for the contribute page, I would post a ticket over at the trueos-website repo, but in the meantime I'll talk to the website team about non-monetary contributions. Weblate is only tied into the translation files from Qt, but adding different files is an option. If we are to make them translatable, we'll put them up on weblate.

**Comment by ZackaryWelch** [comment]
Entries in desktop files can be translated by putting the short language code in brackets after value. So Name[es]="Nombre" will set the name to be "Nombre" if the language is set to Spanish (es). This works for all desktop files and is part of the Lumina library. However, there is not a way currently like weblate to host the translation of these values. I will talk to @beanpole135 and see what can be done. If find a way, we will talk to the web team about putting a link on the website. I defer all matters concerning the website to them.

**Comment by q5sys** [comment]
Since Ken and I can't resolve this, I moved this ticket over to: https://github.com/trueos/trueos-website/issues/18
