### ISSUE TITLE
Translations for calculator and archiver are missing on weblate

### ISSUE THREAD

**Issue by scootergrisen** [trueos/lumina#388]
I don't see translations for calculator and archiver on http://weblate.trueos.org/projects/lumina/

In the repository we got:
```
lumina/src-qt5/desktop-utils/lumina-calculator/i18n/l-calc_da.ts
lumina/src-qt5/desktop-utils/lumina-archiver/i18n/l-archiver_da.ts
```

Should they be included on weblate?

**Comment by q5sys** [comment]
These show up in Weblate now.  Looks like whatever glitch was resolved.  Thanks for reporting this.
