### ISSUE TITLE
Start menu plugin does not have an icon

### ISSUE THREAD

**Issue by scootergrisen** [trueos/lumina#390]
The "Start menu" plugin seem to be missing an icon when you look under desktop settings panels.
Alle the other plugins have an icon.

**Comment by scootergrisen** [comment]
Also the "Browse files" plugin does not have an icon under desktop settings - menu.

**Comment by beanpole135** [comment]
Do you happen to have the oxygen icon set installed on your system?
Lumina uses the oxygen icons as the "fallback" for when a required icon is not found within your current icon theme, so that will probably fix the issue for you.

**Comment by scootergrisen** [comment]
Do you mean package oxygen-icon-theme?

**Comment by beanpole135** [comment]
Yes, that is the name of the package on FreeBSD for the Oxygen icons.

**Comment by scootergrisen** [comment]
I have "oxygen-icon-theme 5:5.28.0-1" on Debian Linux.
Maybe i build Lumina my self and something went wrong i don't know.

**Comment by beanpole135** [comment]
With the replacement of the oxygen icon theme by the built-in "material-design" icon themes this now becomes a moot point.
