### ISSUE TITLE
Removing "system" from strings and using same log out dialog

### ISSUE THREAD

**Issue by scootergrisen** [trueos/lumina#391]
If you select the system menu plugin and select Leave it says:
```
Restart System
Power Off System
Suspend System
```
There is also a thing called:
`System Dashboard`
Where we have:
`System Volume`

If you select log out in the system dashboard or click click the desktop and select leave you get:
Log out, Restart, Power Off, etc... with out "system".

I suggest removing "system" from those strings and just call them:
Restart
Power Off
Suspend
Dashboard
Volume

Also i suggest using either "Log out" or "Leave" instead of both.
And using the same dialog so when you press "Log out"/"Leave" in the desktop context menu, dashboard and system menu you get the exact same dialog.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/8ce3f3f29025a2ff1d187ae4144792a38e28767e
