### ISSUE TITLE
opening a .desktop symbolic link to a .desktop file does not open the executable (application) that is specified within the source file

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#392]
## Steps

1. start menu
2. aim for a favourite application (one of mine is VLC)
3. contextual menu 
4. Pin to Desktop
5. double-click the resulting icon

## Expected

- run of the application (of the executable that is specified within the source file)

## Actual result

- a _Select Application_ dialogue 

![anwendung auswahlen](https://cloud.githubusercontent.com/assets/192271/23350327/b91ab102-fcb1-11e6-9f78-390c4ba6421f.png)

## Notes 

In the screenshot above, the unexpected language (not English) may be negligible in the context of this issue. I have seen language mismatches in the past. 

A later test caused the title bar of the dialogue to appear in English. 

```text
$ ls -hl /usr/home/bbsadmin-l/Desktop/
total 1
lrwxr-xr-x  1 bbsadmin-l  bbsadmin-l    41B 26 Feb 23:38 vlc.desktop -> /usr/local/share/applications/vlc.desktop
$ 
```

Lumina defaults are not a workaround. 

Not reproducible with KDE Plasma 4. 

```text
$ about

===================
General information
===================

boot environment now (N) … 2017-02-25-05-22-57-unstable-2dc2a76-38-b NR 2017-02-26
       after restart (R) … 2017-02-25-05-22-57-unstable-2dc2a76-38-b NR 2017-02-26
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    number of cores ……………… 2
host ……………………………………………………… momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
memory ………………………………………………… 16384 MB available, 9641 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… 2dc2a76
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… CUSTOM
TrueOS version …………………………… TrueOS-Desktop-201702250619
uptime ………………………………………………… 53 mins
user  …………………………………………………… grahamperrin

More (TrueOS Desktop):

    desktop environment …… KDE
    sound card driver ………… pcm1: <Realtek (0x0280) (Analog 2.0+HP/2.0)> on hdaa1  (1p:1v/1r:1v) default
    wireless driver ……………… iwm0
    X11 drivers ………………………… modesetting_drv.so 

$ 
```

## Credit

https://discourse.trueos.org/t/lumina-201702250619-2/901 from @RodMyers: 

> … sym-linked application brings up a requester asking which "application" you wish to run. Even selecting the correct application, it fails to run.

**Comment by beanpole135** [comment]
This was just fixed a moment ago - and only hit Lumina builds over this last weekend (Feb 24-26, 2017). 
Please rebuild Lumina, or wait for the next UNSTABLE update to TrueOS which will fix it.
