### ISSUE TITLE
when I delete /etc/X11/xorg.conf lumina starts without Taskbar

### ISSUE THREAD

**Issue by markusalbertgraf** [trueos/lumina#393]
I deleted /etc/X11/xorg.conf to get trueOS to use the intel GPU, which it currently doesn't.

When I deleted xorg.conf Lumina started up without the Taskbar.
When right-clicking on the desktop and changing settings, all (that I tested) worked except the menu command to edit the bars (called "Leisten" on german GUI). Opening the settings for the bars just does nothing except closing the menu.
Putting xorg.conf back has it work again.

xorg.conf
# XFree86 configuration file for RoFreeSBIE

Section "ServerLayout"
	Identifier     "XFree86 Configured"
	Screen      0  "Screen0" 0 0
EndSection

Section "Files"
	ModulePath   "/usr/local/lib/modules"
	ModulePath   "/usr/local/lib/xorg/modules"
	FontPath     "/usr/local/share/fonts/cyrillic/"
	FontPath     "/usr/local/share/fonts/TrueType/"
	FontPath     "/usr/local/share/fonts/illinoy/"
	FontPath     "/usr/local/share/fonts/webfonts/"
	FontPath     "/usr/local/share/fonts/misc/"
	FontPath     "/usr/local/share/fonts/TTF/"
	FontPath     "/usr/local/share/fonts/Speedo/"
	FontPath     "/usr/local/share/fonts/Type1/"
	FontPath     "/usr/local/share/fonts/CID/"
	FontPath     "/usr/local/share/fonts/75dpi/"
        FontPath     "/usr/local/share/fonts/100dpi/"
	FontPath     "/usr/local/share/fonts/dejavu/"
	FontPath     "/usr/local/share/fonts/cyrillic/"
	FontPath     "/usr/local/share/fonts/hebrew/"
	FontPath     "/usr/local/share/fonts/vietnamese/"
	FontPath     "/usr/local/share/fonts/indic/"
	FontPath     "/usr/local/share/fonts/ae_fonts1/AAHS"
	FontPath     "/usr/local/share/fonts/ae_fonts1/AGA"
	FontPath     "/usr/local/share/fonts/ae_fonts1/FS"
	FontPath     "/usr/local/share/fonts/ae_fonts1/Kasr"
	FontPath     "/usr/local/share/fonts/ae_fonts1/MCS"
	FontPath     "/usr/local/share/fonts/ae_fonts1/Shmookh"
	FontPath     "/usr/local/share/fonts/local/"
EndSection

Section "Module"
        Load  "extmod"
        Load  "record"
        Load  "dbe"
        Load  "glx"
        Load  "dri"
        Load  "dri2"
EndSection

Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	Monitor    "Monitor0"
EndSection

Section "Device"
        Identifier  "Card0"
        Driver      "modesetting"
        Option      "AccelMethod"               "none"
        Option      "SWcursor"                  "true"
EndSection

about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170223_190305 NR 2017-02-23
       after restart (R) … 12.0-CURRENT-up-20170223_190305 NR 2017-02-23
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    number of cores ……………… 4
host ……………………………………………………… trueos-Laptop.markusgraf.net
memory ………………………………………………… 16384 MB available, 14037 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… a7f7424
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201702212122
uptime ………………………………………………… 24 mins

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Realtek ALC269 (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… iwm0
    X11 drivers ………………………… modesetting_drv.so

**Comment by beanpole135** [comment]
Fixed in source. Basically the problem was that the monitor ids were getting changed when you changed graphics drivers in X11. I wrote up a migration function to move desktop settings between monitors and have it setup to automatically do that migration for single-monitor arrangements as needed.
