### ISSUE TITLE
Ubuntu (16.04) - error AppDialog nullptr

### ISSUE THREAD

**Issue by MingHuiLiu** [trueos/lumina#396]
AppDialog.h:30:5: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
     QListWidgetItem *defaultItem = nullptr;
     ^
AppDialog.h: In constructor ‘AppDialog::AppDialog(QWidget*, QString)’:
AppDialog.h:30:36: error: ‘nullptr’ was not declared in this scope
     QListWidgetItem *defaultItem = nullptr;
                                    ^
AppDialog.h: In member function ‘void AppDialog::on_buttonBox_accepted()’:
AppDialog.h:69:15: error: ‘nullptr’ was not declared in this scope
    if(item != nullptr){
               ^
AppDialog.h: In member function ‘void AppDialog::on_lineSearch_textChanged(const QString&)’:
AppDialog.h:88:37: error: ‘nullptr’ was not declared in this scope
    QListWidgetItem *first_visible = nullptr;
                                     ^
Makefile:943: recipe for target 'PanelWidget.o' failed

**Comment by beanpole135** [comment]
I just changed all those variables to use "0" instead (just like most of the rest of the project). This will ensure uniformity and prevent possible contamination by OS-specific definitions.
