### ISSUE TITLE
PDF Viewer Issues

### ISSUE THREAD

**Issue by kmoore134** [trueos/lumina#398]
Couple of issues from Allan at AsiaBSDCon:

'backspace' key should move slides back, not exit (esc does that)

When viewing 16x9 aspect ratio slides on a 4:3 monitor, it chops off the sides to make it fix. It should scale down.

Also, seems VERY slow to render the next slide, probably need to cache the rendered image somehow for X number of slides ahead and behind (if not all)

**Comment by q5sys** [comment]
We have a PDF viewer?    Must have been one of those things Ken added at some point without making sure I got the memo. lol

**Comment by pkgdemon** [comment]
Its also really slow for me when opening documents with 30 + slides, and images.  I can share my openrc presentation for an example.

**Comment by q5sys** [comment]
Joe, can you email to me so I can run it with some debug stuff enabled?

**Comment by pkgdemon** [comment]
@q5sys http://knoxbug.org/sites/default/files/attachments/OpenRC%20Presentation%20Final.odp.pdf

**Comment by beanpole135** [comment]
`lumina-pdf` is in the experimental Lumina category right now, but has been put on the back-burner until the new PDF backend for Qt5 is available (Qt 5.9?). In the meantime I recommend installing/using the "qpdfview" application (Qt5/Poppler PDF viewer without all the KDE dependencies).
