### ISSUE TITLE
Options for removable media

### ISSUE THREAD

**Issue by kmoore134** [trueos/lumina#399]
Folks seem to like the new media insert detection stuff. However somebody had a good request for the ability to right-click on a USB stick and do something like "fsck" if its UFS for example. There are reasons for wanting this ability, figured it could come in handy.

**Comment by pkgdemon** [comment]
+1

**Comment by beanpole135** [comment]
See if this works for you:
https://github.com/trueos/trueos-core/commit/d7e1b96f465dc35abed9922183b323507347565a

Feel free to adjust that "Exec=" line as needed... ;-)
