### ISSUE TITLE
lumina-config segfaults when clicking on 'Panels' item

### ISSUE THREAD

**Issue by duckunix** [trueos/lumina#402]
pkg version: lumina-201703122208,2
TrueOS, tracking UNSTABLE repo, updated 2017-03-14

Bring up lumina-config, click on 'Panels'

Expected result: open Panel config applet
Observed result: lumina-config exits with a segfault

Let me know what information needed to get more data for you.

**Comment by tomoyat1** [comment]
I can confirm this on STABLE repo as well.
This happens when I have a DisplayPort monitor connected, either as the only monitor or in a multi-monitor setup.

**Comment by MAHDTech** [comment]
Hi there,

I have this same thing.

When I start lumia-config from the cli, this is the output I get.

`Loading Locale: "lumina-config" "en_US" "UTF-8"
 - Created new single-instance lock
QMetaObject::connectSlotsByName: No matching signal for on_quitShortcut_Triggered()
Changing page: ""
Found Apps: 0
Auto App List Update: QDateTime(2017-03-26 13:11:38.526 AEDT Qt::TimeSpec(LocalTime)) Files Found: 49
QFileSystemWatcher::removePaths: list is empty
Found Apps: 43
Changing page: "interface-panel"
segmentation fault  /usr/local/bin/lumina-config`

**Comment by beanpole135** [comment]
Sorry about the delay - was on vacation...
I just think I found the cause of the problem and fixed it. See if that works for you guys now.

**Comment by MAHDTech** [comment]
@beanpole135, I am able to open the panel app now and modify configuration on my primary display.

However if I try and attempt to change displays in the top right corner it crashes with the seg fault again. Here's the output from running from the cli.

```
lumina-config 
Loading Locale: "lumina-config" "en_US" "UTF-8"
 - Created new single-instance lock
QMetaObject::connectSlotsByName: No matching signal for on_quitShortcut_Triggered()
Changing page: ""
Found Apps: 0
Auto App List Update: QDateTime(2017-03-29 14:01:07.130 AEDT Qt::TimeSpec(LocalTime)) Files Found: 51
QFileSystemWatcher::removePaths: list is empty
Found Apps: 45
Changing page: "interface-panel"
Loading Panel Settings: "panel_eDP-1.0/"
Loading Panel Settings: "panel_eDP-1.1/"
Found Other Settings: ("panel_eDP-1.0", "panel_eDP-1.1")
segmentation fault  lumina-config
```
