### ISSUE TITLE
Lumia Screen Configuration getting messed up

### ISSUE THREAD

**Issue by MAHDTech** [trueos/lumina#404]
I move between locations alot (Work + Home) and take my laptop with me. Each morning/night I need to mess about getting the displays configured correctly in the right order as they always get messed  up.

1. How is Lumina supposed to handle this currently, should it automatically re-configure correctly when changing around?

2. If not automatic, would it be possible to create "Profiles" ie Work + Home and then on the login screen I select the Monitor configuration to load for that session.

For specific configuration details, the monitors I have are of different brands and sizes, but they re-uses the same ports (Internal Laptop + External  DisplayPort + External HDMI)

GPU: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

**Comment by MAHDTech** [comment]
So it seems the screen configuration is based on the port rather than the connected device, and this is where my issue is stemming from. I was able to improve it as specified below.

Layout Configuration:

Home: 
LEFT: Laptop Screen
MIDDLE: 1x 24" HP Monitor over DisplayPort
RIGHT: 1x 24" DELL Monitor over HDMI

Work:
LEFT: Laptop Screen
MIDDLE: 1x 27" Phillips Monitor over HDMI
RIGHT: 1x 24" DELL Monitor over DisplayPort

Because I have the DisplayPort / HDMI swapped around whilst at work, the layout gets messed up when I login for the day. This morning I swapped the devices around (moved work RIGHT to MIDDLE) and the layout is now alot better (only needed to change the resolution on 1 display).

Is there a way to configure it to be based upon a unique identifier of the monitor, and remember this, rather than the port which it's connected to which might have any number of different displays connected?

Is there already some configuration options I have missed?

**Comment by q5sys** [comment]
We should be able to create a profile option for screen layouts.  We already have that functionality for panels as an example.  Ken and I talked about this a month or so ago. I've been meaning to add the ability to rotate a screen, before going forward with being able to save profiles.

**Comment by q5sys** [comment]
Can you retest this?  Ken has changed quite a bit in how the monitor configuration utility works.  It'd help to know if you're still having this issue.

**Comment by Mrt134** [comment]
This one appears dormant, and the profile option is being worked on in a separate ticket, so I'm going to close this for now. If this is still an issue, please leave a comment and I'll reopen. Thanks!
