### ISSUE TITLE
'error: nullptr was not declared in this scope' - Ubuntu

### ISSUE THREAD

**Issue by gso** [trueos/lumina#409]
> pages/page_defaultapps.cpp
> pages/page_defaultapps.cpp:68:3: warning: identifier nullptr is a keyword in C++11 [-Wc++0x-compat]
>    QTreeWidgetItem *group = nullptr;
>    ^
> pages/page_defaultapps.cpp: In member function â€˜virtual void page_defaultapps::LoadSettings(int)â€™:
> pages/page_defaultapps.cpp:68:28: error: â€˜nullptrâ€™ was not declared in this scope
>    QTreeWidgetItem *group = nullptr;
>                             ^
> Makefile:1037: recipe for target 'page_defaultapps.o' failed

i386 / Ubuntu 16.04.2

The fix was appending `QMAKE_CXXFLAGS += -std=c++11` to all `.pro` files as outlined [here](http://stackoverflow.com/questions/10033373/c-error-nullptr-was-not-declared-in-this-scope-in-eclipse-ide)  and [here](http://stackoverflow.com/questions/6614049/adding-extra-compiler-option-in-qt).

**Comment by q5sys** [comment]
I wonder if this is an i386 issue only. We've never had any one need that before with Debian or Ubuntu. We can add this to the project file, but I'd want to see exactly why this is needed on your machine so we don't break builds for other other Linux Distros. 

Also, I wonder if gcc changed something to make this necessary on your system.

**Comment by niyasc** [comment]
> I wonder if this is an i386 issue only.

No. It is not an i386 issue. I'm using an x86_64 system and was facing the same problem. It was reported here  https://github.com/trueos/lumina/issues/400

At that time, I resolved the issue by replacing `nullptr` with `NULL`

**Comment by beanpole135** [comment]
We have removed all the "nullptr" usage in the Lumina source tree (including the file mentioned above[1]). The release tarballs will reflect this with the next version update.

[1] https://github.com/trueos/lumina/commit/227d2b20ab7ee892021d93a3d3f0f05875885361
