### ISSUE TITLE
error in installation time (Ошибка во время установки)

### ISSUE THREAD

**Issue by ZloyHohol** [trueos/lumina#412]
Hello, I am owner of notebook HP 255 g4 (l8b85es). I cannot install OS from image: TrueOS-Desktop-2017-03-31-x64-USB.img. In installation time i had troubles... pre-installation process had crashed... I was trying install with EFI mode and without efi mode. installation flash drive I made with: dd method, and GUI program of writting instalation image ROSA image writer.

Original text: "Я владелец ноутбука HP 255 g4 (l8b85es). Я не могу установить ОС с образа: TrueOS-Desktop-2017-03-31-x64-USB.img. Во время установки у меня были проблемы ... был прерван процесс установки ... Я пытался установить с режимом EFI и без режима efi. Установочный флеш-диск, сделанный с помощью: dd-метода, и графической программы для создания образа установки ROSA-image-writer"

please look on these photos: [photos from phone in  installation time]( https://yadi.sk/d/x8B27CyS3H4rCe)

P.S. 
previous version OS was installed successfully, however from PC-BSD 9 to trueos 11 i was cannot use some devices: wifi and BT on Broadcom (Bcm43142) and WiFi on tp-link tl-wn721n (atheros chip ath9k)... I hope that current or newer releases of OS can be really user-friendly and work with bigger list of user`s devices.
sorry for my english ...

**Comment by ZloyHohol** [comment]
[Video](https://yadi.sk/i/mBwb04l73H9Csu)

**Comment by DmitryPostolov** [comment]
Please, publish your message at trueos-core branch. This message not for Lumina part of TrueOS.

Пожалуйста, опубликуйте своё сообщение в ветке trueos-core. Это сообщение не относится напрямую к Lumina, скорее оно относится к самой системе.

**Comment by ZloyHohol** [comment]
Спасибо. Обязательно напишу о проблеме в нужном разделе.
