### ISSUE TITLE
Device icons down left side of the desktop

### ISSUE THREAD

**Issue by slicer69** [trueos/lumina#413]
I checked out the latest code, the preview for Lumina 1.3.0 and most things are working very well. However, each time I login there are device icons down the left side of the desktop. These read "usb0", "usb1", "usb2".... I can right-click on these device icons and select Modify Item->Remove Item, but that only gets rid of them for the duration of the session. The next time I login they are back.

I have no embedded utilities on the desktop and the "Display Desktop Folder Contents" is turned off.

I'd like to find a way to get rid of these icons entirely as they overlap the desktop panel.

**Comment by q5sys** [comment]
That's the automounter at work.  You could disable it, but that wont remove the drive icons from your desktop... You'd still have to do that manually, but if you disable automountd `sudo service automountd stop` it shouldn't re-create them the next time you login.

**Comment by beanpole135** [comment]
Those are simply visual icons for files/dirs within your "/media" directory. If you remove those files it will remove the icons from your desktop too. I have it on my list to make showing those icons optional for 1.3.0 - just have not committed the code for it yet.

**Comment by beanpole135** [comment]
I just committed a new setting for determining if these icons should be shown or not:

https://github.com/trueos/lumina/commit/af7d7127d4df1eed6e61e0b57f12b2fa270f2eb7
https://github.com/trueos/lumina/commit/5b3c3b9b380326b2b59943f0b5704cd2cac10f07

**Comment by slicer69** [comment]
Confirmed this works. Thank you.
