### ISSUE TITLE
Time panel widget mostly hidden

### ISSUE THREAD

**Issue by slicer69** [trueos/lumina#418]
In the the latest checkout of Lumina's master branch (May 2, 2017) the Date/Time panel widget does not display the time in a way which can be seen when the panel is aligned vertically. The clock is left-justified off the side of the screen.

In the attached screen shot of my vertical panel, there are five widgets. The fourth one down is the date/time widget. All  I can see of it is the last digit.

This is a new regression as the time was displayed clearly as recently as two week ago.

![system-tray](https://cloud.githubusercontent.com/assets/7461921/25619933/006766e2-2f23-11e7-8a3b-e8bb08cacd58.png)

**Comment by slicer69** [comment]
I did some more testing on this. With the latest git master checkout (May 30, 2017), the clock is mostly hidden at login when the panel is vertical. However, if I go into settings and orient the panel to be horizontal and then back to vertical, the clock is displayed properly.

When I sign out and log back into Lumina, the clock is hidden again. I've only glanced at the clock code, but I think maybe the function call to orient the clock is happening too soon (before the panel done sizing/placing itself)? Forcing the orientation to happen after Lumina has finished loading causes the clock to display properly.

**Comment by beanpole135** [comment]
I was actually just looking into this and am testing out some changes to the plugin size limitations right now. 
Stay tuned.. ;-)

**Comment by beanpole135** [comment]
Done!
Looks like this makes the button sizing a **whole** lot better now.

https://github.com/trueos/lumina/commit/b28765cf26c4ad0570b7d9cc7d277fbc4ad42222
https://github.com/trueos/lumina/commit/c682298b9e36766d09f97c6327ae0d5116a468f

**Comment by slicer69** [comment]
Confirmed it is working for me too. Thank you.
