### ISSUE TITLE
Pull-request 421

### ISSUE THREAD

**Issue by fjs-github** [trueos/lumina#422]
I submitted pull-request 421 eleven days ago to fix the desktop-switcher-panel-plugin. I don't think it's been evaluated, so I'm not sure if I went about the process incorrectly or the fix is too small/unimportant to be considered. If it's the latter, please reject the pull-request and I'll just keep the change(s) local. The problem and code changes are described in the pull-request summary.

**Comment by beanpole135** [comment]
Sorry about that, I was out of town at a conference the beginning of last week and must have missed that pull request when it came in. I will take a look at it here in a moment and merge that in as necessary.

**Comment by fjs-github** [comment]
No problem. Thanks for taking a look.
