### ISSUE TITLE
Insight File Manager issue: If cursor out of folder/file name then wrong "paste" on copy files

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#423]
Insight File Manager issue: If cursor out of folder/file name then wrong "paste" on copy files.

Issue: in Insight File Manager: If cursor out of folder/file name then wrong "paste" on copy files, no active context menu for "paste" command on right mouse button click.

Workaround: to move cursor to the folder or file name, then press the right button on mouse and context menu now is active. Or press "Ctrl-V" hotkey for paste command.

Lumina 1.2.0 installed from pkg on FreeBSD

dmitry@freebsd:~ % pkg info lumina
lumina-1.2.0.p1_3,2
Name           : lumina
Version        : 1.2.0.p1_3,2

dmitry@freebsd:~ % uname -a
FreeBSD freebsd 11.1-PRERELEASE FreeBSD 11.1-PRERELEASE #0 r318893: Thu May 25 23:20:57 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

![insight](https://cloud.githubusercontent.com/assets/20837310/26612402/fb5a350a-45cd-11e7-91a6-4cb3f324a92d.png)

**Comment by beanpole135** [comment]
This was already fixed in the current version in the source tree (1.2.2). 
FreeBSD (and other OS's) will get this fix once 1.3.0 is tagged/released sometime here soon.
