### ISSUE TITLE
Lumina-FM / Insight shortcuts not shown in menu

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#424]
Fresh install of TrueOS-2017-06-01-x64 STABLE on Lenovo Thinkpad T520, using integrated graphics with intel driver.

With localisation set to Germany there are no shortcuts shown in the menus of Insight (see screenshot).
![shortscuts_menu](https://user-images.githubusercontent.com/3322553/26849550-f24599b4-4b04-11e7-91cc-43e417e903ab.png)

**Comment by beanpole135** [comment]
Good catch!
The shortcut labels are something which is built-in to Qt itself, so I would hazard a guess that either the Qt localization files are missing translations for your locale, the Qt localization files are not installed, or a bug slipped into the upstream code which accidentally deactivated the labels for non-native localizations.
In any of these cases, it is probably something to ask about upstream in the Qt project itself (note that we are using Qt 5.7.1 right now - it is very possible that a newer version of Qt fixes this issue).
