### ISSUE TITLE
Feature request: incorporate Lumina Archiver in Lumina like Ark is in KDE

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#425]
It would be nice to have options in the right-click menu like different types of compression, compress and send to... etc. like KDE offers with Ark.

**Comment by q5sys** [comment]
This is already on the roadmap.  Ken and I have talked about this for a while, however we needed to get some other pieces in place before we could go forward with this.  As those pieces are coming together this should be something we can accomplish in the near future. :)

**Comment by q-pa** [comment]
Great news! I guess I can close this (up to you to reopen). Thanks to the team.

**Comment by q5sys** [comment]
Nah, we'll keep it open as a reminder for us to get it done. :)

**Comment by q5sys** [comment]
We've enabled the first step of this today.  Right now we have auto-extraction enabled through the right-click menu on a file.  At the moment it's only able to do a single file, but we will be enabling the ability to auto-extract multiple files at the same time soon.

**Comment by Mrt134** [comment]
Contributor _theloox_ from Gitter chat wanted to take a stab at this.

**Comment by beanpole135** [comment]
Done!
