### ISSUE TITLE
Feature request: Ability to turn on/off thumbnails in Lumina-FM (Insight)

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#428]
This functionality got lost between PCBSD 10.3 and TrueOS (or I cannot find it anymore).

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/lumina/commit/92aef217826de24e8086d88f41ca4bb361c89fc8

**Comment by q-pa** [comment]
Wow, you are quick! Many thanks, @beanpole135! On my way home I just came up with the idea to borrow functionality from PCManFM: there you can choose to either completely turn off thumbnails or allow them for local and/or remote directories. Might be interesting if you have a slow network connection.
