### ISSUE TITLE
add Qarma to Lumina (it's a portage of zenity for Qt)

### ISSUE THREAD

**Issue by chafporte** [trueos/lumina#429]
so the scripts using zenity could run smoothly, lxqt is using it.

https://github.com/luebking/qarma

I am the author of tinyfiledialogs and lumina doesn't offer much to display modal dialogs
gnome has zenity; kde has kdialog;

**Comment by beanpole135** [comment]
No.

Reasons:
1. Lumina does not care what other applications are installed, and there is no reason that something like `qarma` can't be installed/used after-the-fact as the user or the system administrator desires. You could even install it alongside kdialog, zenity, qdialog, or others without too much trouble.
2. `qarma` is available under a GPLv2 license. I will never merge GPL licensed code into the Lumina source tree because it will "infect" the rest of the BSD-licensed project.
3. `qarma` is not available on FreeBSD (the primary development platform for TrueOS), so making it a hard runtime dependency is also out of the question.

**Comment by q5sys** [comment]
You should look at https://github.com/trueos/lumina/tree/master/src-qt5/desktop-utils/lumina-notify
It does not have all the options that zenity does, but its good enough for simple tasks when you need to launch a dialog box from shell and capture the response.

**Comment by chafporte** [comment]
I understand (mostly the GPL issue). and thanks for the lumina-notify tip.

I am not in a situation to install anything, I am just trying to use what is installed.
generally if nothing is present, I can always use xterm with bash (and often dialog).

you don't distribute dialog, and qterminal doesn't behave like an xterm.
even if xterm is listed as a Lumina dependency, it is not distributed with your latest release.

in Lumina, all I can do is xmessage to tell the user to install something.

thanks for your answers.

**Comment by beanpole135** [comment]
Where are you trying to use Lumina?
Utilities like `dialog`, `xterm`, and `bash` would be considered part of the underlying operating system - not part of the desktop. So if you need more utilities installed "out-of-box" then you either need to talk to your OS maintainer(s) to add stuff in, write a system-setup script which installs your needed utilities post-install, or roll your own customized OS image.

**Comment by q5sys** [comment]
What exactly are you trying to accomplish?  Without knowing your use case it's rather hard for us to give you ideas on how you can accomplish it with what we provide.

**Comment by chafporte** [comment]
I am offering file dialogs to C/C++ programmers. It only uses command line calls.
http://tinyfiledialogs.sf.net
I realize there is nothing I can use on trueos/lumina.
everything I need can be installed. but nothing is present upfront:
kdialog: no
qarma (zenity): no
python + tkinter: no
xterm + bash + dialog: no
xterm + bash: no
so there is nothing I can do to launch a file dialogs.
all I can do is display an xmessage to tell the user to install something.

I though maybe I am not the only one who needs this file dialogs functionality.
qarma (i.e. zenity for Qt) could be a good addition. it's a bad idea. I get it.

I must add: trueos/lumina is the only system where I am failing at displaying a file dialog.
I guess I will live with it.
thanks for your help.
