### ISSUE TITLE
Text under window buttons in vertical mode unreadable

### ISSUE THREAD

**Issue by slicer69** [trueos/lumina#430]
I use the Lumina panel in vertical orientation (down the left side of the screen). With recent versions of Lumina, text has been placed under each task manager button, labeling the window's button. Unfortunately, unless the panel is very wide, there is not enough room to display any meaningful amount of text. This results in the button for Konsole simply reading "ons" or the button for Mozilla Firefox reading "lla Fire".

As the text takes up vertical space, but not enough text is displayed horizontally to clearly identify the window, I have created a patch which hides the button text when the panel is in vertical orientation. The window-identifying text is still displayed when the panel is in horizontal orientation. The patch is attached.

I'd like to get this patch into Lumina 1.3.0 as it tidies up my task manager, allowing more buttons/windows to be displayed in the panel.

[taskmanager-patch.txt](https://github.com/trueos/lumina/files/1064637/taskmanager-patch.txt)

**Comment by grahamperrin** [comment]
#325

**Comment by beanpole135** [comment]
Done!
https://github.com/trueos/lumina/commit/4a853e16010357e845a2036c676b460c8173b808
