### ISSUE TITLE
Problem with sort shortcuts and desktop widgets after quit and re-login

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#432]
[dmitry@trueos7517] ~% uname -a
FreeBSD trueos7517.local 12.0-CURRENT FreeBSD 12.0-CURRENT #61 d7b9fac18(trueos-stable)-dirty: Mon May 29 20:21:45 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64

TrueOS image from 1st june 2017 after update from 8 june 2017.

Lumina 1.2.2. Problem with sort shortcuts and desktop widgets after quit and re-login.

YouTube video: https://www.youtube.com/watch?v=lDPIYjusewA

**Comment by beanpole135** [comment]
I am fairly sure that this is already fixed in the version of Lumina in the source tree.
Would you might recompiling and testing it out?

**Comment by DmitryPostolov** [comment]
I will be able to test it 12 hours later.

**Comment by DmitryPostolov** [comment]
Yes, it was fixed in Lumina from src.

![luminafix](https://user-images.githubusercontent.com/20837310/27128808-83f534e0-5119-11e7-98be-43f4ce4ff427.png)

On it I would like to thanks a TrueOS and Lumina-DE for interaction and to finish the involvement in testing of the project.

**Comment by beanpole135** [comment]
Thanks for verifying that!
