### ISSUE TITLE
Improvement: Allow to save my profile (panels settings)

### ISSUE THREAD

**Issue by bmin** [trueos/lumina#438]
Currently there is an option, which is disabled now, "Import". I guess its there to import panels configuration.
I am expecting to save my panels settings so that can be load or share later on.

**Comment by q5sys** [comment]
I'll look into this, when I get time.  I thought we already had enabled this.  But if not, then we need to.

**Comment by Mrt134** [comment]
Closing this as a duplicate of https://github.com/trueos/lumina/issues/355 - the work is close to done.
