### ISSUE TITLE
mainUI.cpp:377:15: error: 'class QMediaPlaylist' has no member named 'moveMedia'

### ISSUE THREAD

**Issue by charIes17** [trueos/lumina#439]
mainUI.cpp: In member function 'void MainUI::upLocalMedia()':
mainUI.cpp:377:15: error: 'class QMediaPlaylist' has no member named 'moveMedia'
     PLAYLIST->moveMedia(row, row-1 );
               ^
mainUI.cpp: In member function 'void MainUI::downLocalMedia()':
mainUI.cpp:388:15: error: 'class QMediaPlaylist' has no member named 'moveMedia'
     PLAYLIST->moveMedia(row, row+1 );
               ^
make[3]: *** [Makefile:525: mainUI.o] Error 1

Full log see https://paste.pound-python.org/show/T04ybi7IJYKzyCEthmAv/

**Comment by beanpole135** [comment]
Your version of Qt is not up to date.
That function call was added in Qt 5.7 (http://doc.qt.io/qt-5/qmediaplaylist.html#moveMedia), but the latest version of Qt is 5.9. You will need to get a newer version of Qt installed (5.7+) before lumina-mediaplayer will work.
