### ISSUE TITLE
OpenBSD port maintainer - trying to port 1.3p1 and hitting problem

### ISSUE THREAD

**Issue by bceverly** [trueos/lumina#440]
Hi,

Sorry to be a pain, but our implementation of qmediaplaylist.h for qt5 on OpenBSD doesn't include a "moveMedia" method in the QMediaPlaylist class.  What do you think?  Is there a way I can #ifdef some stuff out in order to get it working or is this a deeper change I would need to make?

Thanks for the advice in advance!

**Comment by beanpole135** [comment]
Please see issue #439 as this has already been addressed: Qt5.7+ is required for lumina-mediaplayer.

In the absence of Qt5.7+, you could easily disable the lumina-mediaplayer utility within the src-qt5/desktop-utils/desktop-utils.pro (comment out one line) before building the entire project, or take a bit more time to split up the lumina port into each of the individual pieces like we did on TrueOS and FreeBSD (core, core-utils, and each individual desktop-util)

**Comment by sasongko26** [comment]
IMO, we should list Qt5.7 to DEPENDENCIES https://github.com/trueos/lumina/blob/master/DEPENDENCIES#L7

**Comment by beanpole135** [comment]
That is on the roadmap. Due to how every utility is now completely independent from everything else, we still need to go through and create ReadMe files (and Dependency files) for every single tool

**Comment by beanpole135** [comment]
But just FYI: Qt 5.7+ is only required for lumina-mediaplayer. The desktop and all the other tools still only need Qt 5.4+

**Comment by beanpole135** [comment]
Done!
Now all the individual sub-projects have their own README.md files which list all the dependencies and/or optional runtime utilities for the tool.
