### ISSUE TITLE
Control + MouseWheel to change workspaces breaks xnview functionality

### ISSUE THREAD

**Issue by bcoolumbo** [trueos/lumina#441]
I used to zoom in and out with this keybinding in xnviewmp. Under lumina it brings me to another workspace...

**Comment by q5sys** [comment]
You can change this within the keyboard shortcuts file 'fluxbox keys'.  We've made this easy to do within lumina-config. Look for the shortcuts page.  The entry you need to look for is the ones for: Scroll wheel (Buttons 4 and 5).
If you have any problems with this, let us know! :)
