### ISSUE TITLE
Lumina-FM crashing

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#442]
==================
General information
==================
boot environment now (N) … 12.0-CURRENT-up-20170704_202439 NR 2017-07-04
       after restart (R) … 12.0-CURRENT-up-20170704_202439 NR 2017-07-04
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
    number of cores ……………… 8
host ……………………………………………………… trueos-L
memory ………………………………………………… 16384 MB available, 13223 MB free
OS git branch ……………………………………………………………………………………… trueos-stable
OS git revision ………………………………………………………………………………… ac2f0aa3b
OS kernel build time ………………………………………………………… Wed 2017 Jun 21 01:09:23 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201706210948
uptime ………………………………………………… 1:13
user  …………………………………………………… delipu

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Conexant CX20590 (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… iwn0
    X11 drivers ………………………… intel_drv.so
===============================================================================

Lumina-FM crashes everytime after transferring a file from the local disk to a samba share on my NAS. The transfer is finished successfully, though. 

In /var/log/messages there is the line:
kernel: pid 16620 (lumina-fm), uid 1001: exited on signal 10

**Comment by q5sys** [comment]
I'll look into this, sometime this week when I have the chance.

**Comment by q-pa** [comment]
I would have thought I tested this right after the beginning of July update and only then filed this bug report. But I cannot reproduce this. Crashing that is. During most copying operations I get some message from the task panel icon that errors occurred but without more detail I have no chance to find out what went wrong apart from checking each and every single file...

**Comment by beanpole135** [comment]
If you click on the tray message somewhere, there should be a "details" button or something which lists the exact files which errored. (I think the button was on the right-side of the message in the tray menu)

**Comment by q-pa** [comment]
Just checked but I cannot find a "details" button. Clicking into the error messages does not open any details window.
![insight_error](https://user-images.githubusercontent.com/3322553/28542515-b42853c8-70bc-11e7-9b65-4efa3d170804.jpg)

Funny thing is, when I copied stuff around to produce an error, Lumina-FM crashed again.

**Comment by q-pa** [comment]
Wait, that circle icon is the details button! Sorry for being stupid here... ;) Although, in my defence I would never have guessed the icon to be "details" sign. :)

**Comment by q5sys** [comment]
Well that button is actually the cancel button if you want to cancel an operation that's in progress.  Are you saying that button brought up the error details? If so, then we need to change the UI element to display a different icon to signify that there is information that should be read.

**Comment by q-pa** [comment]
Yes, this button brought up the details.

**Comment by beanpole135** [comment]
I just changed the icon around a bit so we avoid icons that might look like a cancel button.

https://github.com/trueos/lumina/commit/1ea1cfc0b10f334f3e15dedbc2238fc68ee60789
