### ISSUE TITLE
Question:  Recommendation for HiDPI

### ISSUE THREAD

**Issue by bceverly** [trueos/lumina#443]
Hi all,

I'm running a Thinkpad X1 Carbon (4th generation) Skylake laptop with Lumina 1.3.0pl1 and my window titlebars are microscopic.  Is there a recommended theme or setting that can help me adjust them to be larger?

Thanks!

**Comment by beanpole135** [comment]
There is a "bora_blue_4k" theme that we created for Fluxbox which is better with High DPI screens which you could try. Some other Fluxbox themes are also larger and more-functional on High DPI screens (I am using the "fireMarks" theme on my 4K screens at the moment). You just need to try some of them out and see what you like. Alternatively, you could always copy/modify a theme that you like just to increase the size of the borders (/usr/local/share/fluxbox/styles).
