### ISSUE TITLE
lumina-fm: video file thumbnail preview support

### ISSUE THREAD

**Issue by danboid** [trueos/lumina#450]
The main reason I use Thunar instead of lumina-fm under TrueOS is because not only does Thunar show thumbnail previews of local video files, it can also show thumbnails of multi-GB video files stored on network shares.

**Comment by ZackaryWelch** [comment]
I am currently looking into video thumbnail support and exploring high performance options for doing so. I have found a few options, though at the moment solutions which are based entirely in the Qt Multimedia framework are preferable, as opposed to outsourcing to ffmpeg or using libav. Performance is an issue, so it might be awhile until a good solution is found, and we can guarantee it won't impact Insight's performance.

**Comment by danboid** [comment]
Thanks for the update Zack!

Please ensure it works well via samba/NFS too.

**Comment by ZackaryWelch** [comment]
Currently works with multiple different types of videos on lumina-fm and lumina-fileinfo. I have not tried for large numbers of videos in a directory. The wait time is small but noticeable. I'm working on performance improvements, but if the current wait time is too large, let me know and I'll see if we need to switch to a different system.
https://github.com/trueos/lumina/commit/79fbc99707377264761434b44147281457189691

**Comment by danboid** [comment]
Hi Zackary

That's great news!

My first questions are:

* Can I build lumina-fm separately from Lumina or do I need to build the entirity of lumina?

* Can I build lumina(-fm) without the theme support? libQt5ThemeSupport.a doesn't seem to be packaged by Ubuntu, which is what I'm trying to test on.

make[3]: Entering directory '/home/dan/src/lumina/src-qt5/core/lumina-theme-engine'
cd src/lthemeengine-qtplugin/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile /home/dan/src/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin/lthemeengine-qtplugin.pro ) && make -f Makefile 
make[4]: Entering directory '/home/dan/src/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin'
make[4]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libQt5ThemeSupport.a', needed by 'liblthemeengine.so'. Stop.
make[4]: Leaving directory '/home/dan/src/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin'
Makefile:46: recipe for target 'sub-src-lthemeengine-qtplugin-make_first' failed
make[3]: *** [sub-src-lthemeengine-qtplugin-make_first] Error 2
make[3]: Leaving directory '/home/dan/src/lumina/src-qt5/core/lumina-theme-engine'
Makefile:174: recipe for target 'sub-lumina-theme-engine-make_first' failed
make[2]: *** [sub-lumina-theme-engine-make_first] Error 2
make[2]: Leaving directory '/home/dan/src/lumina/src-qt5/core'
Makefile:46: recipe for target 'sub-core-make_first' failed
make[1]: *** [sub-core-make_first] Error 2
make[1]: Leaving directory '/home/dan/src/lumina/src-qt5'
Makefile:44: recipe for target 'sub-src-qt5-make_first' failed
make: *** [sub-src-qt5-make_first] Error 2

**Comment by beanpole135** [comment]
1. Yes, just change to the src-qt5/desktop-utils/lumina-fm directory before running the qmake/make commands.
2. Lumina-fm - yes, Lumina core - no. Ubuntu just splits up the Qt5 packages a bit more than the BSD's. If I recall right, you just need to install the "-dev" Qt5 packages to get the actual files needed to build the theme engine plugin.

**Comment by danboid** [comment]
Thanks Ken!
