### ISSUE TITLE
lumina-fm: Adjust display size of file preview icons

### ISSUE THREAD

**Issue by danboid** [trueos/lumina#451]
Thumbnail previews under lumina-fm aren't much use on a 4K display currently because you cannot scale the size of the image (and hopefully video and pdf files soon too) preview icons to make them easily visible.

**Comment by q5sys** [comment]
After looking into this I realized we already have this functionality. 
![screenshot-2017-08-01-16-27-35](https://user-images.githubusercontent.com/4654247/28845795-2c3585be-76d7-11e7-96f0-7b8fb327a917.png)
