### ISSUE TITLE
Issues using mpv under lumina

### ISSUE THREAD

**Issue by danboid** [trueos/lumina#452]
My fave media player by a mile is mpv but unfortunately I cannot use it under lumina 1.3.0 but it works fine under TrueOS / MATE 1.12.

mpv 0.25
lumina 1.3.0 w/ compositing disabled or MATE 1.12
Intel 4600 (Haswell) GPU
Integrated 1080 laptop display and 4K HDMI external monitor set to 4K res so in a non-mirrored display config

If I try to play a 4K h264 video with mpv, lumina fails to play it back in what should be windowed mode. Instead, it plays it back in a funky fullscreen mode that plays the video a bit more than fullscreen so that part of the video spills over onto the other screen. If I play the video in proper mpv fullscreen mode, it plays back correctly under lumina. Hence, windowed playback under lumina/mpv seems to be broken.

I can play back the same video files with mpv in windowed mode fine with the same display config when using MATE under TrueOS instead.

The other thing that works fine under MATE that is broken for mpv under Lumina is that you cannot play (h264) videos rotated when you have an mpv input.conf file configured as such:

https://wiki.archlinux.org/index.php/mpv#An_example_input.conf_file

With that config file in place, you can use Alt+RIGHT-ARROW or Alt+LEFT-ARROW to rotate video playback 90 degrees in realtime under MATE but not lumina.

**Comment by q5sys** [comment]
Have you tested at all under vanilla Fluxbox? That'll help us potentially isolate where the issue may lie.  

Also, so I understand you correctly, you're saying that mpv does actually run under Lumina, it's just that it doesn't run the way you want.

**Comment by danboid** [comment]
I've just tried mpv under vanilla fluxbox and it also has the same problem with not being able to playback videos in a window so this a fluxbox problem.

I have had mpv suffer jerky video playback sometimes under Linux/MATE sometimes which I have fixed by simply adding the line

`profile=xv`

to **~/.config/mpv/mpv.conf** which disables OpenGL accel playback where supported as that is turned on by default under mpv. By adding this config, it fixes the rotation problem but it doesn't fix windowed playback under FB or Lumina.

mpv runs under both fluxbox and lumina but it only displays proper output when in fullscreen (non windowed) mode. Both windowed and fullscreen modes work fine under MATE.

**Comment by danboid** [comment]
Although having

`profile=xv`

In my mpv.conf fixes video rotation under fluxbox and Lumina, its only really a workaround because performance suffers greatly when you use the xv display output profile. Rotation works fine without this option under MATE.

**Comment by danboid** [comment]
I have installed openbox under TrueOS and mpv works fine in window mode under openbox too so it does just seem to be fluxbox and Lumina that don't like mpv. If mpv is having issues, other video players may have similar issues - certainly ones such as gnome-mpv that depend upon mpv, of course.

Are there any reasons Lumina couldn't switch from using fluxbox to using openbox? It would seem openbox is the better choice for my use case at least.

**Comment by danboid** [comment]
I realise the plan is to replace fluxbox with a homegrown lumina wm, but until that is ready why not use openbox?

**Comment by q5sys** [comment]
I'm a fan of openbox myself, but Fluxbox was the better option when Ken was designing Lumina.  I'm not going to go through the laundry list of reasons, but Fluxbox is/was a better option that Openbox for Lumina.  However, this will be a thing of the past once the new Lumina WM is completed.  If you want to run openbox as the WM with Lumina you're more than welcome to do so... no one here is going to stop you.  But we are not going to make that the default.  We have a patch submission that will enable people to change the WM to whatever, but be aware that this will break quite a bit with the desktop, and you will be responsible to support it yourself.

As for mpv, after looking into it a bit more. After scouring the MPV issue tracker itself, I'm not sure if it's an issue with Fluxbox or an issue with MPV, but I'm leaning towards the latter.  There is a long history of MPV trying to override the WM and impose its own values for _NET_WM_STATE_FULLSCREEN and _NET_WM_STATE.  But whether Fluxbox or MPV is to blame, is neither here nor there, as it's not something that Lumina has anything to do with.  If MPV fails under a native Fluxbox environment, there is nothing that Lumina can do to resolve this.
