### ISSUE TITLE
lumina-fm: Find files

### ISSUE THREAD

**Issue by danboid** [trueos/lumina#453]
It would be very handy if lumina-fm had an integrated 'Find file' function.

Extra bonus points for the ability to find text within files too!

**Comment by q5sys** [comment]
>It would be very handy if lumina-fm had an integrated 'Find file' function.
Ken and I would have to talk that over.  IDK if that's something we'd want to integrate into Insight itself, or have a separate utility for that.  

>Extra bonus points for the ability to find text within files too!
aka, a gui for grep?

**Comment by danboid** [comment]
I was thinking the same. Does lumina-fm have plugins?

**Comment by beanpole135** [comment]
Have you tried hitting control-F in lumina-fm? There is already a lumina-search utility (launched in vanilla mode via Alt-F2) that allows the user to search for files (does not look within files though).

**Comment by danboid** [comment]
Haha! I can't believe I missed that!

Still, could I suggest that 'Search Directory' (under the lumina-fm File menu) gets relabelled as 'Find file in directory' because it makes more sense to have CTRL+F be the shortcut for a function called 'Find...'

**Comment by danboid** [comment]
Maybe it should actually be labelled 'Find files and directories in dir' if it does both but that might be deemed overkill.

**Comment by q5sys** [comment]
That's a bit of a long string for the menu.  Ctrl-F is the industry standard, so I'm not really sure why we need to change their wording so the letter matches.  We have other shortcuts that dont match, so it's not out of the ordinary.

As for plug-ins... no, Lumina-FM does not have a plug in system.

**Comment by danboid** [comment]
Fair enuff! Sorry about the noise on this!
