### ISSUE TITLE
Lumina-FM: Right-click Menu Entry Checksum

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#455]
Shouldn't the checksum test (via right-click menu) produce some checksum number? On my up-to-date STABLE install nothing happens when running it on a file.

**Comment by q5sys** [comment]
Thanks, I'll look into this next week when I have some free time.

**Comment by q5sys** [comment]
![lumina-fm](https://user-images.githubusercontent.com/4654247/28837019-44f0999a-76b9-11e7-813f-20ff78072cc3.png)

This is what I get from the latest sources.  Are you getting the dialog window on your system at all?

**Comment by q-pa** [comment]
Turns out I tested it on ZIP files only. And for the latter I do not get a dialog window. Other types of files work.

**Comment by q5sys** [comment]
![lumina-fm-2](https://user-images.githubusercontent.com/4654247/28841354-f3f98150-76c7-11e7-9a20-0035661a5330.png)

Latest sources work fine with zip files.  Probably a regression that we already resolved that hasn't gotten to stable yet.  Thanks for the ticket.
