### ISSUE TITLE
Build error - 

### ISSUE THREAD

**Issue by grafa** [trueos/lumina#456]
Hi guys I wanted to try out your work but when I run `make` I got this error (after like 5 mins of compiling)

```
make[3]: Entering directory '/home/dev/lumina/icon-theme'
cd material-design-light/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/dev/lumina/icon-theme/material-design-light/material-design-light.pro -o Makefile ) && make -f Makefile 
make[4]: Entering directory '/home/dev/lumina/icon-theme/material-design-light'
make[4]: Nothing to be done for 'first'.
make[4]: Leaving directory '/home/dev/lumina/icon-theme/material-design-light'
cd material-design-dark/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/dev/lumina/icon-theme/material-design-dark/material-design-dark.pro -o Makefile ) && make -f Makefile 
make[4]: Entering directory '/home/dev/lumina/icon-theme/material-design-dark'
make[4]: Nothing to be done for 'first'.
make[4]: Leaving directory '/home/dev/lumina/icon-theme/material-design-dark'
make[3]: Leaving directory '/home/dev/lumina/icon-theme'
cd lumina-theme-engine/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/dev/lumina/src-qt5/core/lumina-theme-engine/lumina-theme-engine.pro -o Makefile ) && make -f Makefile 
make[3]: Entering directory '/home/dev/lumina/src-qt5/core/lumina-theme-engine'
cd src/lthemeengine-qtplugin/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/dev/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin/lthemeengine-qtplugin.pro -o Makefile ) && make -f Makefile 
make[4]: Entering directory '/home/dev/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin'
make[4]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libQt5PlatformSupport.a', needed by 'liblthemeengine.so'.  Stop.
make[4]: Leaving directory '/home/dev/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin'
Makefile:44: recipe for target 'sub-src-lthemeengine-qtplugin-make_first' failed
make[3]: *** [sub-src-lthemeengine-qtplugin-make_first] Error 2
make[3]: Leaving directory '/home/dev/lumina/src-qt5/core/lumina-theme-engine'
Makefile:172: recipe for target 'sub-lumina-theme-engine-make_first' failed
make[2]: *** [sub-lumina-theme-engine-make_first] Error 2
make[2]: Leaving directory '/home/dev/lumina/src-qt5/core'
Makefile:44: recipe for target 'sub-core-make_first' failed
make[1]: *** [sub-core-make_first] Error 2
make[1]: Leaving directory '/home/dev/lumina/src-qt5'
Makefile:42: recipe for target 'sub-src-qt5-make_first' failed
make: *** [sub-src-qt5-make_first] Error 2
```

Building on debian and I was following steps for Debian on this page : https://lumina-desktop.org/get-lumina/

**Comment by slicer69** [comment]
Could you please post which version of Debian you are running? Also what version of the Qt5 libraries you have on your system? My guess is either that Lumina needs a newer version of Qt or one of the Qt dev libraries might be missing.

**Comment by grafa** [comment]
Debian: 9.0
Qt: 5.7

**Comment by SolarAquarion** [comment]
pages/page_session_options.cpp: In constructor ‘page_session_options::page_session_options(QWidget*)’:
pages/page_session_options.cpp:36:15: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
   connect(ui->mywindowmanager, SIGNAL(currentIndexChanged(int)), this, SLOT(settingChanged()));
               ^~~~~~~~~~~~~~~
pages/page_session_options.cpp: In member function ‘virtual void page_session_options::SaveSettings()’:
pages/page_session_options.cpp:57:24: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
   QString my_win = ui->mywindowmanager->currentText();
                        ^~~~~~~~~~~~~~~
pages/page_session_options.cpp: In member function ‘virtual void page_session_options::LoadSettings(int)’:
pages/page_session_options.cpp:112:19: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
       index = ui->mywindowmanager->findText( old_wm );
                   ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:115:16: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
            ui->mywindowmanager->addItem( old_wm );
                ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:117:23: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
           index = ui->mywindowmanager->findText( old_wm );
                       ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:121:18: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
      index = ui->mywindowmanager->findText( "Lumina" );
                  ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:123:7: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
   ui->mywindowmanager->setCurrentIndex(index);
       ^~~~~~~~~~~~~~~
pages/page_session_options.cpp: In member function ‘void page_session_options::FindWindowManagerOptions()’:
pages/page_session_options.cpp:147:9: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
     ui->mywindowmanager->clear();
         ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:148:9: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
     ui->mywindowmanager->addItem("Lumina"); // make sure there is a default
         ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:150:13: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
         ui->mywindowmanager->addItem("/usr/bin/fluxbox");
             ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:152:13: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
         ui->mywindowmanager->addItem("/usr/local/bin/fluxbox");
             ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:154:13: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
         ui->mywindowmanager->addItem("/usr/bin/kwin");
             ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:156:13: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
         ui->mywindowmanager->addItem("/usr/local/bin/kwin");
             ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:158:13: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
         ui->mywindowmanager->addItem("/usr/bin/openbox");
             ^~~~~~~~~~~~~~~
pages/page_session_options.cpp:160:13: error: ‘class Ui::page_session_options’ has no member named ‘mywindowmanager’
         ui->mywindowmanager->addItem("/usr/local/bin/openbox");
             ^~~~~~~~~~~~~~~
make[3]: *** [Makefile:2017: .build/obj/page_session_options.o] Error 1
make[3]: Leaving directory '/home/solaraquarion/build/lumina-desktop-git/src/lumina/src-qt5/core-utils/lumina-config'
make[2]: *** [Makefile:47: sub-lumina-config-make_first] Error 2
make[2]: Leaving directory '/home/solaraquarion/build/lumina-desktop-git/src/lumina/src-qt5/core-utils'
make[1]: *** [Makefile:72: sub-core-utils-make_first] Error 2
make[1]: Leaving directory '/home/solaraquarion/build/lumina-desktop-git/src/lumina/src-qt5'
make: *** [Makefile:45: sub-src-qt5-make_first] Error 2
==> ERROR: A failure occurred in build().

Different build error Arch Linux

**Comment by beanpole135** [comment]
Try this (from within the base of the lumina repo):
```
cd src-qt5/core-utils/lumina-config
make distclean
qmake
make
```
the "ui->mywindowmanager" object is a new one which was added to the qt-designer form recently, so your build might just be re-using a stale pre-compiled file.

**Comment by hbarn** [comment]
The list of dependencies there for Debian/Devuan is incomplete.

This can be solved with the following:

`sudo apt-get install qtbase5-private-dev`

Then try make again.

**Comment by SolarAquarion** [comment]
you can close it

**Comment by beanpole135** [comment]
Closing ticket. Feel free to open a new one if this issue pops up again.
