### ISSUE TITLE
Instructions for building on Debian/Devuan/Ubuntu missing dependencies

### ISSUE THREAD

**Issue by hbarn** [trueos/lumina#458]
The list of build dependencies at [https://lumina-desktop.org/get-lumina/](url) is missing:

`qtbase5-private-dev`
`libpoppler-qt5-dev`

**Comment by beanpole135** [comment]
Footnote for @Mrt134 and @JoshDW19:
Note that the dependencies @hbarn listed are specific to some Linux distros (Debian/Ubuntu) - and do not exist on most BSD OS's. They should be added to the respective sections in the handbook/website for those distros.

**Comment by q5sys** [comment]
Since Ken and I can't resolve this, I moved this ticket over to: https://github.com/trueos/trueos-website/issues/17
