### ISSUE TITLE
Lumina 1.* overwrites file associations

### ISSUE THREAD

**Issue by RodMyers** [trueos/lumina#462]
I've went through the  desktop config and associated many text files so they are associated with LibreOffice. Today I double clicked on a .doc file, and Lumina editor popped open.

looked at the system wide  file associations, and they all reverted back to Lumina Editor.

**Comment by beanpole135** [comment]
This should fix it for you.
That is the only piece of code that will overwrite the user's default applications (aside from the lumina-open dialog where you can change a single mimetype's association).

https://github.com/trueos/lumina/commit/4979e9c1bc1a625b8fe3b012d367e45242e4dd7b
