### ISSUE TITLE
x86_32 support

### ISSUE THREAD

**Issue by alxpl** [trueos/lumina#463]
Hello,

Please forgive me if this isn't your preferred method of communication for such issues. If you feel this should be posted elsewhere, I'd be happy to oblige.

I am writing on behalf of the Fedora x86 SIG, which is currently under formation. Our goal is to keep Fedora running on the i686 platform and if there is enough interest, we might produce an i686 spin. As we are examining our options for a specific deliverable that we want to see maintained, the “tiny server” target seems the most sustainable one, but we haven't ruled out desktops yet.

What I would like to hear from you is if your road map for the foreseeable future includes some change that might make it impractical to run Lumina on i686 machines, or if you intend to drop support for the architecture altogether. We haven't decided on the minimum specs we are willing to support/test, but for now PAE support seems out and we are still trying to figure out if we want to include non-SSE2 CPUs. In any case, we are talking about systems with limited resources, so it would be desirable e.g. to keep RAM use of the desktop below 512MB.

Best regards
Alexander Ploumistos

**Comment by Mrt134** [comment]
Hi Alexander,

I believe Lumina is essentially agnostic when it comes to platform hardware - there are no plans to drop support for an i686 platform. Lumina is still intended to be very system resource conscious and this will likely be even more true when Lumina 2.0 is released.

That being said, if you decide to incorporate or use Lumina with your project, we're very open to integrating upstream any specific features or troubleshooting your team may add. Just submit a pull request and we'll review and merge it as soon as possible. :)

**Comment by alxpl** [comment]
Thank you very much Tim, that is good to know.

All the best

**Comment by Mrt134** [comment]
No problem! Best of luck to your new project.
