### ISSUE TITLE
Funny bug in Lumina from pkg on FreeBSD - add shortcuts to Desktop

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#469]
Funny bug in Lumina from pkg on FreeBSD - failure add shortcuts to Desktop.

No this bug on TrueOS, this bug is available only on FreeBSD and xBSD if install Lumina from pkg.

How to reproduce:

1. Install FreeBSD 11.1-amd64.img
2. Update FreeBSD to 11.1-RELEASE-p1.
3. ee /etc/pkg/FreeBSD.conf -> replace "quarterly" to "latest"
4. pkg update; pkg install xorg lumina mc minicom wget qterminal firefox vlc kolourpaint libreoffice (number of packages to be installed: 509)
5. cd /usr/local/etc/X11/xorg.conf.d and ee driver-scfb.conf:
Section "Device"
 Identifier "Card0"
 Driver "scfb"
EndSection
6. ee /etc/rc.conf: dbus_enable="YES" exit and reboot
7. start-lumina-desktop on user
8. Preferences /All desktop settings /Menu /"+" /Custom App /Select Firefox Web Browser and ^ to the first item of menu
9. Try to add shortcuts apps to Desktop with Pin to desktop:

Click Menu /Browse Applications/ Right click on Firefox Web Browser (context menu) and left click to Pin to Desktop

No reaction: Firefox shortcut dont view on Desktop after number of clicks.

Workaround: Open Firefox browser with desktop menu, open some site, for example, opennet.ru and close Firefox. Then try to Pin to Desktop again. After this quit from Lumina and re-start Lumina again: Firefox shortcut is displayed on Desktop and after that all items will be Pin to Desktop OK.

Video: https://www.youtube.com/watch?v=pXxLeU12Opk

**Comment by beanpole135** [comment]
This may be a simple answer, but you have a "Desktop" folder in your home directory?
On stock FreeBSD I do not believe the standard home dir folders are created by default, you need to run an additional command to generate those directories (I don't recall the "xdg-*" utility that you can run to do it easily, but a simple "mkdir ~/Desktop" will also do it)

**Comment by DmitryPostolov** [comment]
Beanpole135, thanks! After mkdir ~/Desktop this problem is [SOLVED].
