### ISSUE TITLE
Opening Device manager in Desktop settings, opens mouse configuration instead

### ISSUE THREAD

**Issue by samob** [trueos/lumina#470]
Testing UNSTABLE OS git revision 2a2a3070d, I noticed that clicking on Device manager icon in Desktop settings, opens mouse configuration instead.

**Comment by RodMyers** [comment]
just checked my UNSTABLE laptop.

Mine opens device manage as expected.

had you adjusted the cursor before hand?

**Comment by samob** [comment]
Nop, nothing changed and I did clean install from USB image.

**Comment by samob** [comment]
I have two separate systems, both clean install and they both act same way.

**Comment by q5sys** [comment]
I can confirm this bug.
![lumina-config-error](https://user-images.githubusercontent.com/4654247/31099172-1267f35a-a793-11e7-9eab-62c9a886d8d8.png)

**Comment by q5sys** [comment]
This was actually a bug in sysadm-ui-qt, but it's been fixed.
https://github.com/trueos/sysadm-ui-qt/commit/21d4a97bbc14ba6901913776d4e4b189ac9f2763
