### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by amt0001** [trueos/lumina#471]
I'm trying to compile lumina but i get an  error in the lumina-pdf step. 

> mainUI.cpp:117:29: error: ‘class Poppler::Document’ has no member named ‘title’  this->setWindowTitle(DOC->title());

I have to add the poppler library
>  INCLUDEPATH+= /usr/include/poppler/qt5

because i get this error
> mainUI.h:19:25: error fatal: poppler-qt5.h: No such file or directory

I'm using Fedora 25 with poppler-qt5 version 0.45.0-5.fc25

**Comment by q5sys** [comment]
You seem to have written this backwards so I'm going to assume that you're getting the no member error AFTER you added poppler to the includes.

I'll have to find the upstream project and see the previous iterations.  
I did find the header file for this in Fedora, which I posted here: https://paste2.org/VXptjIeO  
Line 1079 does have the title object... but it's commented out.

Not sure if upstream changed something or if Fedora did.

**Comment by amt0001** [comment]
By the moment i have commented the line lumina-pdf in the desktop-utils.pro file and now the proyect is compiling.

**Comment by amt0001** [comment]
I think the people of fedora changed the file because in the original [source file](https://people.freedesktop.org/~aacid/docs/qt5/poppler-qt5_8h_source.html) the variable *title* exists.

**Comment by beanpole135** [comment]
Closing this as a 3rd-party problem.
Fedora needs to fix their poppler package/includes to maintain support for all upstream interactions. ("title" in particular - kind of important for a document to be able to report it's title....)

**Comment by rezso** [comment]
Note: poppler 0.45 requires a patch in lumina-pdf, because poppler 0.45 doesn't contains title() function:

-  this->setWindowTitle(DOC->title());
+  this->setWindowTitle(DOC->info("Title"));
