### ISSUE TITLE
Lumina forgets user specified file associations

### ISSUE THREAD

**Issue by RodMyers** [trueos/lumina#473]
===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170927_143731 NR 2017-09-27
       after restart (R) … 12.0-CURRENT-up-20170927_143731 NR 2017-09-27
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    number of cores ……………… 4
host ……………………………………………………… watton.hitwe-8.org
memory ………………………………………………… 12288 MB available, 6778 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… 2a2a3070d
OS kernel build time ………………………………………………………… Fri 2017 Sep 22 13:48:41 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201707111911
uptime ………………………………………………… 7 days,  3:24
user  …………………………………………………… rodney

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Conexant CX20590 (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… iwn0
    X11 drivers ………………………… modesetting_drv.so 

I went through and changed a bunch of file associations AWAY from lumina-editor, and phototonic.

After this recent upgrade, I went and double clicked a csv file, and lumina-editor was started. Looked at;

Preferences -> All Desktop Settings -> Desktop Defaults --> applications --> advanced

all previous entries were overwritten now to the default of text -> Lumina-editor, and image -> phototonic

**Comment by samob** [comment]
I have tried to set default app for txt files to Mousepad, but next time I doubleclick text file in Lumina-FM, Lumina text editor pops up.
![set-default-txt](https://user-images.githubusercontent.com/335163/31268906-a2cdd4f8-aa7e-11e7-9bb0-51fd3f26f691.png)

I have also noticed that opening text file with Mousepad as suggested default app, does not open selected document, but opens Mousepad with blank document.

**Comment by Mrt134** [comment]
This looks like a regression as I want to say this same issue came up and was resolved earlier this year. Thanks for the report - we'll look into it!

**Comment by ZackaryWelch** [comment]
@RodMyers How is your issue with setting application defaults in the settings menu different from
https://github.com/trueos/lumina/issues/474
Is this still an issue for you?

**Comment by RodMyers** [comment]
@ZackaryWelch  thank you, forgot.

just checked an it holds my changes.

and with that, time to close

**Comment by ZackaryWelch** [comment]
So while your issue is resolved @RodMyers , I'm noticing some odd behavior with the Open With function and setting default applications as per @samob . These two ways of setting defaults need to work together, and so in the mean time I'm going to keep this issue open.

**Comment by ZackaryWelch** [comment]
So the same issue that was affecting lumina-config was affecting the Open With setting defaults. Setting binaries directly worked, but setting an application from the drop down list was saved as an invalid default and the user set default was reverted to the initial system default. This has been fixed so that defaults are saved when the user selects the "Set this application as default" checkbox.
https://github.com/trueos/lumina/commit/08d871eeab89f38dcd1717cd6a29dfbbcc6b79b7
