### ISSUE TITLE
Lumina preferences do not stick , after upgrade

### ISSUE THREAD

**Issue by RodMyers** [trueos/lumina#474]
===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170927_143731 NR 2017-09-27
       after restart (R) … 12.0-CURRENT-up-20170927_143731 NR 2017-09-27
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    number of cores ……………… 4
host ……………………………………………………… watton.hitwe-8.org
memory ………………………………………………… 12288 MB available, 6778 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… 2a2a3070d
OS kernel build time ………………………………………………………… Fri 2017 Sep 22 13:48:41 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201707111911
uptime ………………………………………………… 7 days,  3:24
user  …………………………………………………… rodney

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Conexant CX20590 (Analog 2.0+HP/2.0)> (play/rec) default
    wireless driver ……………… iwn0
    X11 drivers ………………………… modesetting_drv.so 

Preferences -> All Desktop Settings -> Desktop Defaults -> Applications -> Advanced -> image

went through and changed ALL file types from phototonic to viewnior. No "Save" button presented itself, hit the "Back to Settings" tab, and back into advanced. My settings were not saved

**Comment by ZackaryWelch** [comment]
Thanks for the bug report! I have reproduced this bug on the current unstable, and I will work to add a save button that should have been there in the first place.

**Comment by ZackaryWelch** [comment]
As it turns out, changing the binary settings work fine, while setting the app directly does that. Reading the desktop file from the full path fixes this issue. Fitting with how the basic settings and the binary settings work, I don't believe a save button is necessary. Simply changing the value in the list will change the system settings.
https://github.com/trueos/lumina/commit/20373eb1665303d77c17d4b268b95e7a4b6ab440
