### ISSUE TITLE
lumina-fm: Resizing video thumbnails causes segfault

### ISSUE THREAD

**Issue by danboid** [trueos/lumina#477]
@ZackaryWelch 

I have just built the latest lumina-fm git code under Ubuntu 17.10 and it segfaults after pushing 'Increase Icon Sizes' about 7 times (from the smallest icon size) within a directory with only 4 MP4 files.

After pushing the plus icon twice, often (but not always) the thumbnail for one or two if the video files will disappear. Push it again (and again) and some of the disappearing icons will reappear. After pushing plus about 7 times, lumina-fm segfaults with an error (or several) like:

```
Error: "Internal data stream error."
Segmentation fault
```

Another issue I've noticed with regards to the video thumbnails is that they don't seem to respect the setting of View -> Show Image Previews. I think this feature should be adjusted now, if it hasn't been already, so that it enables/disables previews for both images and videos, in which case it probably should be renamed 'Show Thumbnails'.

**Comment by danboid** [comment]
All 4 videos in the directory used a codec/container such as below - all the same res/framerate but different lengths:

$ mediainfo 20170827_020246.mp4
General
Complete name                            : 20170827_020246.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 1.24 GiB
Duration                                 : 3 min 41 s
Overall bit rate                         : 48.1 Mb/s
Performer                                : LGE
Encoded date                             : UTC 2017-08-27 01:06:29
Tagged date                              : UTC 2017-08-27 01:06:29
com.android.version                      : 6.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 1 frame
Format settings, GOP                     : M=1, N=31
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 3 min 41 s
Source duration                          : 3 min 41 s
Bit rate                                 : 48.0 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Rotation                                 : 90°
Frame rate mode                          : Variable
Frame rate                               : 29.936 FPS
Minimum frame rate                       : 23.322 FPS
Maximum frame rate                       : 30.508 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.193
Stream size                              : 1.24 GiB (100%)
Source stream size                       : 1.24 GiB (100%)
Title                                    : VideoHandle
Language                                 : English
Encoded date                             : UTC 2017-08-27 01:06:29
Tagged date                              : UTC 2017-08-27 01:06:29
mdhd_Duration                            : 221564

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 3 min 41 s
Source duration                          : 3 min 41 s
Bit rate mode                            : Constant
Bit rate                                 : 156 kb/s
Nominal bit rate                         : 96.0 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 4.13 MiB (0%)
Source stream size                       : 4.13 MiB (0%)
Title                                    : SoundHandle
Language                                 : English
Encoded date                             : UTC 2017-08-27 01:06:29
Tagged date                              : UTC 2017-08-27 01:06:29
mdhd_Duration                            : 221842

**Comment by ZackaryWelch** [comment]
Thanks for your bug report! I've made the video thumbnail system use the same setting as images, but I am unable to reproduce the seg fault from resizing currently. Tomorrow I will bring a drive with more videos to test.

**Comment by danboid** [comment]
Hi Zack

You just at least 2X 4K vids within the same folder to cause this crash. I've uploaded a short 4K vid from my phone here:

https://drive.google.com/open?id=0B7N9S9Y9ZSgebGRUM3VrdFFUUk0

Download that video then copy/rename it at least  once (so as to have 2x 4K res vids) then zoom the icons.

**Comment by ZackaryWelch** [comment]
I found the cause of the issue to be the way the thumbnails are created. If you go to resize the videos while the directory is still loading the videos from the previous zoom in it will crash. I'm currently implementing a way to terminate loading when you go to resize. The current way to avoid this is to only press zoom in when all files are loaded, but that will not be necessary soon.

**Comment by ZackaryWelch** [comment]
https://github.com/trueos/lumina/commit/cd928a79ff4bf6da55689bc100168355ec962b50
The resizing issue is no longer a problem as when videos are loaded their thumbnails are stored, and the videos do not have to be reloaded.

**Comment by danboid** [comment]
Hi Zack

Have you noticed https://github.com/trueos/lumina/issues/483 already?

Thanks
