### ISSUE TITLE
lumina-fm: Type-ahead find

### ISSUE THREAD

**Issue by danboid** [trueos/lumina#478]
It would be useful if lumina-fm supported type-ahead find (find as you type) so you can quickly navigate to files and directories by typing their name when the lumina-fm main window is in focus.

**Comment by beanpole135** [comment]
It already does.
If you click in the path bar and start typing it will show a list of suggestions in a drop-down menu under the bar. You just need to hit the down arrow to select one of the suggestions and enter to go to it.
