### ISSUE TITLE
Calling checkpass with the password as an argument is a security risk.

### ISSUE THREAD

**Issue by cpforbes** [trueos/lumina#479]
https://github.com/trueos/lumina/blob/a2bb82ae14f9f52c15e08880a559781d6f9e9ecb/src-qt5/core/lumina-desktop-unified/src-screensaver/LLockScreen.cpp#L80

The cleartext password will appear in the process list.

**Comment by beanpole135** [comment]
Fixed!
https://github.com/trueos/lumina/commit/2cedaf2c2ac9e4b4e3078c5a6f04ba5fc3f4f5b3

That was actually just a temporary placeholder while I was doing the initial write up for lock functionality in Lumina 2, so I went ahead and just finished that up now rather than wait for later.

**Comment by cpforbes** [comment]
It might make sense to also remove the password on the command line option entirely to prevent it from being used.

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/lumina/commit/221c57a127579d6ad4849b475e107d7b60369db3
