### ISSUE TITLE
(Linux) Update Battery Info routine to support upower.

### ISSUE THREAD

**Issue by rezso** [trueos/lumina#48]
I have Linux, with upower. This combination not supported by Lumina, it uses acpi command to query some battery info.
But Qt5 contains an QBatteryInfo class:
http://qt.developpez.com/doc/5.0-snapshot/qbatteryinfo/
It is possible to use this class instead of hardcoded commands?

**Comment by beanpole135** [comment]
I only have two concerns with using QBatteryInfo:
1) QBatteryInfo is not included in the official/non-commercial Qt libraries (Checked Qt 5.3/5.4). It appears to be either an external Qt-based utility/library (requiring it's own set of dependencies), or a special non-standard/developer addition that requires the distribution of customized Qt libraries (which causes issues with the LGPL licensing).
2) Since I do not use Linux, I do not have the ability to test that it works on Linux systems - so I would prefer it if one of the Linux developers/contributors adjusts the battery routines to be a bit more flexible (or create a special version of the Linux interface for your particular distro).

**Comment by beanpole135** [comment]
I just updated the issue title/summary and am leaving it open so that a Linux contributor can take a look at it.

**Comment by Nanolx** [comment]
QBatteryInfo is part of Qt Mobility which is an official side-project of Qt. (on Debian install qtmobility-dev and libqtsysteminfo1 for QBatteryInfo stuff).

I would afford some free time for this, but I don't own any notebook or other portable PC (except here non-relevant tablet PC).

**Comment by beanpole135** [comment]
Qt Mobility is not available for Qt5, only Qt4. Many of the Qt-mobility classes were moved into the mainline Qt library/modules for Qt5, but QBatteryInfo did not make the transition. I think the way to go is for some Linux developer to simply adjust the battery routines to support a couple different utilities. Something along the lines of this:
[pseudo-code]
if(QFile::exists(<utility1>)){
 UseUtility1(); //upower? (whatever is only installed on a subset of systems)
}else if(QFile::exists(<utility2>)){
 UseUtility2(); //other optional battery utility
}else{
 UseFallbackMethod(); //use the acpi call directly (what is used now)
}
[/pseudo-code]

**Comment by rezso** [comment]
Another possibility adding upower support like this:
https://github.com/mgottschlag/kwin-tiling/blob/master/powerdevil/daemon/backends/upower/powerdevilupowerbackend.cpp#L248

**Comment by q5sys** [comment]
I'm going to mark this as Help Wanted since it's going to require someone other than Ken and I to tackle this.

**Comment by slicer69** [comment]
I looked into this and I have two concerns:

1. I tried Upower on two computers and it didn't work on either. It failed to detect my power levels, or show any useful information. So I'm not going to be able to add a Upower backend for Lumina.

2. The man pages for both the client and daemon parts of Upower basically just say "todo". So there isn't much to go on or trouble-shoot.

**Comment by andybarnes** [comment]
Just FYI QtSystems module contains QBatteryInfo in QT5.

**Comment by Mrt134** [comment]
After investigating briefly, it appears the QtSystems module is not an official part of Qt and is unavailable on some operating systems, including FreeBSD + other *BSDs. Unfortunately, this pretty much removes it as a workable option for us.

**Comment by Kurgol** [comment]
weird it's hosted on their github https://github.com/qt/qtsystems

**Comment by Mrt134** [comment]
Apologies, you're right, my mistake. I didn't see it listed with the other modules when I looked through the Qt5 documentation (http://doc.qt.io/qt-5/qtmodules.html). We'll need to go through the code and see how much is usable in a BSD system

**Comment by beanpole135** [comment]
After a review of the QtSystems module in the Qt repository and the code associated with the "Linux" option (used for all Non-Windows and Non-Mac OS's), it appears to be an experimental module that does not have reliable compatibility across operating systems (even across various Linux distros). This might explain why it is not officially listed in the Qt documentation or almost anywhere else for that matter.
For a project like Lumina which focuses on cross-platform functionality much like Qt itself, I don't think that using/expecting the QtSystems module is a good idea.
