### ISSUE TITLE
Full screen windows hide behind the Lumina taskbar

### ISSUE THREAD

**Issue by JoshDW19** [trueos/lumina#484]
I want to search for something but I can't see what I'm typing. This is using Firefox. I've had this issue on other apps as well where when they are opened full screen, the very bottom part of the app will hide behind the lumina taskbar. I've looked through the settings and can't find anything. Help!!

![image](https://user-images.githubusercontent.com/6586006/31773307-549b763c-b4b0-11e7-91f2-95c25f24d98f.png)

**Comment by beanpole135** [comment]
This is a bug in Fluxbox at the moment that still re-appears when you have multiple monitors enabled that are different resolutions (such as a 1080p monitor and a 3-4K monitor).
There is really nothing that we can do about it at the moment for Lumina 1 - it would need to get fixed in Fluxbox.
