### ISSUE TITLE
Feature Request: lumina-pdf change hotkeys so that up/down arrows scroll document

### ISSUE THREAD

**Issue by ldemouy** [trueos/lumina#485]
In all other pdf viewers the up/down arrow keys scoll the document, and when at the bottom of the current page goes to the next page, in lumina-pdf they change the page number, which is not what is expected.

**Comment by q5sys** [comment]
Thanks for the issue, we'll look into it and get back you.  Do other PDF viewers have a way to jump pages instead of just scrolling?  PgDn/PgUp I assume or do they use the left/right arrow keys?

**Comment by beanpole135** [comment]
I just unified the page-change mechanisms between the presentation window and the main viewer so they always show the same page and they use the same keyboard shortcuts (arrow keys, spacebar, page up/down) to change pages.

I was **not** able to make the up/down arrows keys scroll the viewer at the moment though. It looks like the Qt widget we are using right now (QPrintPreviewWidget) does not expose the scrollbar to external interactions, so I cannot re-direct the keyboard shortcuts over to that functionality at the moment.

**Comment by beanpole135** [comment]
Done!
https://github.com/trueos/lumina/commit/7de410fca082c16f4e725d86b3558e441c619590
