### ISSUE TITLE
In detailed list Lumina-FM resizes columns when changing dirs

### ISSUE THREAD

**Issue by q5sys** [trueos/lumina#488]
As the title says, as you change directories in detailed list mode the width of the columns changes based on the shortest file name.  If a user widens any column to a preferred width it will rest upon changing directory. 

I don't recall this behavior in the past, but I may have just not noticed it before.

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/df0a6abc4622e4527fb8ef6f618485bb4fdc4cb1
