### ISSUE TITLE
Less strict rules in .desktop files parser

### ISSUE THREAD

**Issue by digitalist** [trueos/lumina#494]
In  many cases devs enclose paths in quotes to prevent potential issues with spaces and special chars, for example, all `Exec="path"` entries in JetBrains product

Lumina doesn't parse files with such entries. Can it be fixed?

example .desktop file, it works ok with quotes deleted in Exec:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=CLion
Icon=/usr/home/user/prog/clion-2017.2.3/bin/clion.svg
Exec="/usr/home/user/prog/clion-2017.2.3/bin/clion.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-clion
OnlyShowIn=Old;
```

**Comment by beanpole135** [comment]
Fixed!

https://github.com/trueos/lumina/commit/f8b26186ce5b6a018d2c833188fb1e9ee7f902d5
