### ISSUE TITLE
Building from source (Ubuntu 17.04)

### ISSUE THREAD

**Issue by hari-rangarajan** [trueos/lumina#501]
Deps installed:
 sudo apt-get install build-essential git qt5-default qttools5-dev-tools libqt5gui5 qtmultimedia5-dev libqt5multimediawidgets5 libqt5network5 libqt5svg5-dev libqt5x11extras5-dev libxcb-icccm4-dev libxcb-ewmh-dev libxcb-composite0-dev libxcb-damage0-dev libxcb-util0-dev libphonon-dev libxcomposite-dev libxdamage-dev libxrender-dev libxcb-image0-dev libxcb-screensaver0-dev qtdeclarative5-dev fluxbox kde-style-oxygen xscreensaver xbacklight alsa-utils acpi numlockx pavucontrol xterm sysstat gi

~/lumina$ qmake
Project MESSAGE: Build OS Info: Linux, x86_64, #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017
Project MESSAGE:  - Detected Qt Version: 5.7.1
Project MESSAGE: Build Settings Loaded: Linux -Ubuntu

make[4]: Entering directory '/home/hari/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin'
make[4]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libQt5PlatformSupport.a', needed by 'liblthemeengine.so'.  Stop.
make[4]: Leaving directory '/home/hari/lumina/src-qt5/core/lumina-theme-engine/src/lthemeengine-qtplugin'
Makefile:44: recipe for target 'sub-src-lthemeengine-qtplugin-make_first' failed
make[3]: *** [sub-src-lthemeengine-qtplugin-make_first] Error 2
make[3]: Leaving directory '/home/hari/lumina/src-qt5/core/lumina-theme-engine'
Makefile:172: recipe for target 'sub-lumina-theme-engine-make_first' failed
make[2]: *** [sub-lumina-theme-engine-make_first] Error 2
make[2]: Leaving directory '/home/hari/lumina/src-qt5/core'
Makefile:44: recipe for target 'sub-core-make_first' failed
make[1]: *** [sub-core-make_first] Error 2
make[1]: Leaving directory '/home/hari/lumina/src-qt5'
Makefile:42: recipe for target 'sub-src-qt5-make_first' failed
make: *** [sub-src-qt5-make_first] Error 2

**Comment by beanpole135** [comment]
Trying to reproduce this in an Ubuntu 17.10 VM I just created. Will report back in a little bit.

**Comment by beanpole135** [comment]
Ok, steps taken to get Lumina to build on a newly-installed Ubuntu 17.10 VM:

```
sudo dpkg --configure -a
sudo apt-get install build-essential git libqt5* qt5-default qtmultimedia5-dev qtbase5-* libxcb-ewmh* libxcb-icccm* libxcb-composite* libxcb-damage* libxcb-util* libxcb-image* libpoppler-qt5*
```
The "qtbase5-*" package group is what installed the necessary Qt5 libraries for creating a theme plugin. Not sure exactly which one of them, but you should be able to dig into that more if you want to try and narrow it down to a "minimal" build environment.

Runtime Dependencies
```
sudo apt-get install fluxbox kde-style-oxygen xscreensaver xbacklight alsa-utils acpi numlockx pavucontrol xterm sysstat
``

I also just pushed a commit to automatically add the poppler "include" path to the build on Ubuntu so lumina-pdf will build for you without any additional hassle.

**Comment by hari-rangarajan** [comment]
Installing 'qtbase5-private-gles-dev' seemed to do the trick for me
