### ISSUE TITLE
auto-extract option showing up for every file

### ISSUE THREAD

**Issue by q5sys** [trueos/lumina#507]
We wrote an if statement so this would only show up if Lumina-Archiver is installed.  That works properly, but we should also add an XDG check so this only shows up for compressed files.  There's no reason for the 'auto-extract' option to show up for JPG images. 

https://github.com/trueos/lumina/blob/f741ebb9536522a12ce63a9e6f93aaf44905531a/src-qt5/desktop-utils/lumina-fm/widgets/DirWidget2.cpp#L563

**Comment by beanpole135** [comment]
Done!
https://github.com/trueos/lumina/commit/5312b9161aa82ec8139c73b5f7dddd269120f15d
