### ISSUE TITLE
Lumina default theme failure

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#508]
Lumina default theme failure after start Preferences / About Lumina.

[dmitry@trueos-1781] ~% about

General information

boot environment now (N) … 12.0-CURRENT-up-20171118_112816 NR 2017-11-18
 after restart (R) … 12.0-CURRENT-up-20171118_112816 NR 2017-11-18
boot loader …………………………………… BSD
 type ……………………… EFI
CPU ………………………………………………………… Intel(R) Pentium(R) CPU  N3700  @ 1.60GHz
 number of cores ……………… 4
host ……………………………………………………… trueos-1781.local
memory ………………………………………………… 4096 MB available, 2192 MB free
OS git branch ……………………………………………………………………………………… trueos-master
OS git revision ………………………………………………………………………………… 67a4643eb
OS kernel build time ………………………………………………………… Wed 2017 Nov 8 18:09:27 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201711140940
uptime ………………………………………………… 2:06
user  …………………………………………………… dmitry

More (TrueOS Desktop):

desktop environment …… Lumina
sound card driver ………… pcm1: <Realtek ALC283 (Front Analog Headphones)> (play) default
wireless driver ……………… iwm0
X11 drivers ………………………… modesetting_drv.so

**Comment by beanpole135** [comment]
Fixed!
https://github.com/trueos/lumina/commit/b9afbb6b6133552113ac8da9d7edf62e45c454ae
