### ISSUE TITLE
Lumina menu failure in Russian language after install some apps

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#509]
Lumina menu failure in Russian language after install some apps and reboot: mc minicom wget firefox-i18n kolourpaint ru-libreoffice. 

In this case Lumina menu is become too short.

![luminamenufailure](https://user-images.githubusercontent.com/20837310/33056083-4bab0c7c-cea5-11e7-86cc-834af0d5bbb5.png)

**Comment by beanpole135** [comment]
Just click/drag the edge of the start menu to make it larger/smaller as needed. It will save that size in it's settings file and re-use it later for consistency between sessions.
