### ISSUE TITLE
1.4.0 build failed on Stretch

### ISSUE THREAD

**Issue by pavroo** [trueos/lumina#510]
Hi
Just tried 1.4.0 to build on Debian Stretch amd64.
Build failed with the message:
`g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o lumina-desktop .build/obj/ResizeMenu.o .build/obj/LDesktopUtils.o .build/obj/LuminaOS-Linux.o .build/obj/OSInterface-template.o .build/obj/LUtils.o .build/obj/LuminaThemes.o .build/obj/LuminaXDG.o .build/obj/LFileInfo.o .build/obj/LuminaX11.o .build/obj/LuminaSingleApplication.o .build/obj/LIconCache.o .build/obj/main.o .build/obj/WMProcess.o .build/obj/LXcbEventFilter.o .build/obj/LSession.o .build/obj/LDesktop.o .build/obj/LDesktopBackground.o .build/obj/LDesktopPluginSpace.o .build/obj/LPanel.o .build/obj/LWinInfo.o .build/obj/AppMenu.o .build/obj/SettingsMenu.o .build/obj/SystemWindow.o .build/obj/BootSplash.o .build/obj/LDPlugin.o .build/obj/LUserButton.o .build/obj/UserWidget.o .build/obj/UserItemWidget.o .build/obj/LDeskBar.o .build/obj/LTaskManagerPlugin.o .build/obj/LTaskButton.o .build/obj/LSysTray.o .build/obj/TrayIcon.o .build/obj/LClock.o .build/obj/LBattery.o .build/obj/LDesktopSwitcher.o .build/obj/LSysDashboard.o .build/obj/SysMenuQuick.o .build/obj/LHomeButton.o .build/obj/LAppMenuPlugin.o .build/obj/AppLaunchButton.o .build/obj/LStartButton.o .build/obj/StartMenu.o .build/obj/ItemWidget.o .build/obj/LPAudioPlayer.o .build/obj/PPlayerWidget.o .build/obj/PPJsonMenu.o .build/obj/AppLauncherPlugin.o .build/obj/DesktopViewPlugin.o .build/obj/NotepadPlugin.o .build/obj/PlayerWidget.o .build/obj/MonitorWidget.o .build/obj/RSSFeedPlugin.o .build/obj/RSSObjects.o .build/obj/qrc_Lumina-DE.o .build/obj/moc_ResizeMenu.o .build/obj/moc_OSInterface.o .build/obj/moc_LuminaThemes.o .build/obj/moc_LuminaXDG.o .build/obj/moc_LuminaSingleApplication.o .build/obj/moc_ExternalProcess.o .build/obj/moc_LIconCache.o .build/obj/moc_WMProcess.o .build/obj/moc_LSession.o .build/obj/moc_LDesktop.o .build/obj/moc_LDesktopBackground.o .build/obj/moc_LDesktopPluginSpace.o .build/obj/moc_LPanel.o .build/obj/moc_AppMenu.o .build/obj/moc_SettingsMenu.o .build/obj/moc_SystemWindow.o .build/obj/moc_BootSplash.o .build/obj/moc_LPPlugin.o .build/obj/moc_LTBWidget.o .build/obj/moc_LDPlugin.o .build/obj/moc_JsonMenu.o .build/obj/moc_RotateToolButton.o .build/obj/moc_LUserButton.o .build/obj/moc_UserWidget.o .build/obj/moc_UserItemWidget.o .build/obj/moc_LDeskBar.o .build/obj/moc_LSysTray.o .build/obj/moc_TrayIcon.o .build/obj/moc_LSpacer.o .build/obj/moc_LLine.o .build/obj/moc_LClock.o .build/obj/moc_LBattery.o .build/obj/moc_LDesktopSwitcher.o .build/obj/moc_LTaskManagerPlugin.o .build/obj/moc_LTaskButton.o .build/obj/moc_LSysDashboard.o .build/obj/moc_SysMenuQuick.o .build/obj/moc_LHomeButton.o .build/obj/moc_LAppMenuPlugin.o .build/obj/moc_AppLaunchButton.o .build/obj/moc_LStartButton.o .build/obj/moc_StartMenu.o .build/obj/moc_ItemWidget.o .build/obj/moc_LPAudioPlayer.o .build/obj/moc_PPlayerWidget.o .build/obj/moc_PPJsonMenu.o .build/obj/moc_CalendarPlugin.o .build/obj/moc_AppLauncherPlugin.o .build/obj/moc_OutlineToolButton.o .build/obj/moc_DesktopViewPlugin.o .build/obj/moc_NotepadPlugin.o .build/obj/moc_PlayerWidget.o .build/obj/moc_MonitorWidget.o .build/obj/moc_RSSFeedPlugin.o .build/obj/moc_RSSObjects.o   -L/media/pavroo/dysk2-2/lumina/64-140-stretch/lumina-1.4.0/src-qt5/core/libLumina -L/usr/lib/x86_64-linux-gnu -L/qt5 -L/usr/X11R6/lib64 -L/usr/local/lib -L/usr/lib -L/lib -lc -lxcb -lxcb-ewmh -lxcb-icccm -lxcb-image -lxcb-composite -lxcb-damage -lxcb-util -lXdamage -lQt5Svg -lQt5Widgets -lQt5X11Extras -lQt5Multimedia -lQt5Gui -lQt5Network -lQt5Concurrent -lQt5Core -lGL -lpthread 
make[3]: Leaving directory '/media/pavroo/dysk2-2/lumina/64-140-stretch/lumina-1.4.0/src-qt5/core/lumina-desktop'
make[2]: Leaving directory '/media/pavroo/dysk2-2/lumina/64-140-stretch/lumina-1.4.0/src-qt5/core'
Makefile:44: recipe for target 'sub-core-make_first' failed
make[1]: *** [sub-core-make_first] Error 2
make[1]: Leaving directory '/media/pavroo/dysk2-2/lumina/64-140-stretch/lumina-1.4.0/src-qt5'
Makefile:42: recipe for target 'sub-src-qt5-make_first' failed
make: *** [sub-src-qt5-make_first] Error 2`

**Comment by beanpole135** [comment]
That does not look like the error - just the gcc command which failed. Do you have the full log?

**Comment by pavroo** [comment]
No, I don't.
I tried on Buster too, but the same result.

**Comment by beanpole135** [comment]
How are you building it?
If you are following the instructions listed on the Lumina repo, you should be getting a lot more output than that, including things like the detected OS, Qt versions, and more.

**Comment by pavroo** [comment]
I used to build debs, but when failed, I tried via qmake & make
There was more output of course, but no log file.
I enclosed qmake.stash and makefiles 
[Makefile-buster.txt](https://github.com/trueos/lumina/files/1497276/Makefile-buster.txt)
[Makefile-stretch.txt](https://github.com/trueos/lumina/files/1497278/Makefile-stretch.txt)
[qmake-buster.stash.txt](https://github.com/trueos/lumina/files/1497280/qmake-buster.stash.txt)
[qmake-stretch.stash.txt](https://github.com/trueos/lumina/files/1497281/qmake-stretch.stash.txt)

**Comment by beanpole135** [comment]
The Makefiles and qmake stashes don't contain any information about the build error.
Try following the commands listed on the Lumina repo and pipe them to your own logfile - by default the messages are just printed in the terminal where you are running the commands, so when I say "log" I mean just copy/paste the terminal output (unless your specific build system actually dumps that output to a log file - which it does not sound like).

Example:
```
qmake > log.txt
echo "=== Starting Make ===" >> log.txt
make >> log.txt
```
Then you can send the "log.txt" file along or look at the end of it to see what the error is,
If I had to hazard a guess though, you probably did not install all of the build dependencies first.

**Comment by pavroo** [comment]
Run a fresh build as you said with the output.
[stretch64log.txt](https://github.com/trueos/lumina/files/1499860/stretch64log.txt)

**Comment by beanpole135** [comment]
Ok, there is still almost no output from your compiler (check if you have some kind of "quiet" compile flag set system-wide), but it appears to be failing when building the theme engine Qt plugin. Please make sure that you have the Qt source/dev library packages installed. The plugin has to use a couple private dev libraries to build/integrate with the current version of Qt.

**Comment by pavroo** [comment]
Missing deps comparing to older versions 1.3.0 & 1.2.0.
Installed them and builds 1.4.0 on Stretch i386 and amd64 ok.
Now cooking it on armhf.
Can be closed.

**Comment by q5sys** [comment]
Thanks for reporting back.  If you come across any other problems, let us know.
