### ISSUE TITLE
Build error: /usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so when searching for -lgcc_s etc.

### ISSUE THREAD

**Issue by marcin-82** [trueos/lumina#515]
Hi

**Target release: lumina-desktop 1.4.0**
https://github.com/trueos/lumina/archive/v1.4.0.tar.gz

Compiling ends with error:
`/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so when searching for -lgcc_s`
`/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1`
`/usr/bin/ld: skipping incompatible /lib/libgcc_s.so.1 when searching for libgcc_s.so.1`
`/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so when searching for -lgcc_s`
`/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1`
`/usr/bin/ld: skipping incompatible /lib/libgcc_s.so.1 when searching for libgcc_s.so.1`

**Environment:**
OS: PCLinuxOS
`qmake --version`
`QMake version 3.1`
`Using Qt version 5.9.2 in /usr/lib64`

**GCC:**
`rpm -qa ^gcc*`
`gcc-7.2.1-4pclos2017`
`gccmakedep-1.0.2-4pclos2017`
`gcc-c++-7.2.1-4pclos2017`
`gcc-cpp-7.2.1-4pclos2017`

I've started with these qmake settings:
`qmake \`
`QMAKE_CFLAGS_ISYSTEM= \`
`CONFIG+=configure \`
`PREFIX="/usr" \`
`LIBPREFIX="/usr/lib64" \`
`CONFIG+="WITH_I18N" \`
`QT5LIBDIR="/usr/lib64" \`
`L_LIBDIR="/usr/lib64"`

**LDCONFIG:**
`LC_MESSAGES=C ldconfig -v | grep libgcc`
`ldconfig: Can't stat /libx32: No such file or directory`
`ldconfig: Can't stat /usr/libx32: No such file or directory`
`	libgcc_s.so.1 -> libgcc_s-7.2.1.so.1`
`	libgcc_s.so.1 -> libgcc_s-7.2.1.so.1`
`ldconfig: Cannot stat /usr/lib64/libLLVM-3.7.1.so: No such file or directory`
`	libgcc_s.so.1 -> libgcc_s_32.so`

Please give feedback if any rurther information are necessary.

**Comment by rezso** [comment]
It seems to me, that the libgcc is an 32-bit library, but you want to compile with 64-bit environment / options.

**Comment by marcin-82** [comment]
I've played around with "brutal" hack:
`sed -i 's|LIBS += -L/usr/local/lib -L/usr/lib -L/lib|LIBS += -L/usr/lib64 -L=/lib64|g' src-qt5/OS-detect.pri`
to avoid using 32bit libgcc_s, bu still with no luck. Build log from rpm says nothing ...

Here is the content of **libgcc1** package:
`rpm -ql libgcc1 `
`/lib/libgcc_s-7.2.1.so.1`
`/lib/libgcc_s.so.1`
`/lib64/libgcc_s-7.2.1.so.1`
`/lib64/libgcc_s.so.1`
`/usr/lib64/libcc1.so.0`
`/usr/lib64/libcc1.so.0.0.0`

**Comment by marcin-82** [comment]
> but still with no luck. Build log from rpm says nothing ...

Problem is solved. I've reviewed and completed build requirements.
