### ISSUE TITLE
RSS reader to include ATOM feeds

### ISSUE THREAD

**Issue by rvdpluijm** [trueos/lumina#516]
First of all, let me start by saying that I love the look and feel of your minimalist design. I find it intuitive to use and has a lot of nice features.

What I would love to see added is an Atom reader. Most feeds I read (e.g. Github) are in ATOM format and since it will probably become even more prevalent it would be great if you could include it!

Kind regards,

Remko van der Pluijm

**Comment by q5sys** [comment]
Thanks for the suggestion, we'll see about making this happen.

**Comment by beanpole135** [comment]
Please try to load an Atom feed into it right now. The RSS and ATOM specifications already overlap significantly, and I seem to remember adding a couple extra parsing options for some differences, but I don't recall if it was complete or not yet.

Parsing Rules:
https://github.com/trueos/lumina/blob/master/src-qt5/core/lumina-desktop/desktop-plugins/rssreader/RSSObjects.cpp

Sample Combination feed (RSS2 and ATOM):
http://lumina-desktop.org/feed/

**Comment by ZackaryWelch** [comment]
The RSS reading should be working with ATOM feeds now.
https://github.com/trueos/lumina/commit/6679414ee4e385e3f88aa1401cb24f8afe73b4c3
