### ISSUE TITLE
Current STABLE/UNSTABLE lumina-pdf version not the same

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#525]
I am testing TrueOS on two different computers. Both running the recent STABLE and UNSTABLE releases, respectively. 

Although AppCafé says lumina-pdf is the same version (1.4.1_201712071357), they are not. And there is a significant difference in the output as you can see from attached screenshots.

![stable](https://user-images.githubusercontent.com/3322553/34040700-1f2fc798-e195-11e7-81cb-4ce08a23fe8b.png)
![unstable](https://user-images.githubusercontent.com/3322553/34040701-1f4f9672-e195-11e7-90e3-e378466de56e.png)

**Comment by beanpole135** [comment]
The second screenshot is not lumina-pdf, that is the older "pc-pdfviewer" utility that we have been phasing out.
In the application list you should see "Lumina PDF Viewer" and "TrueOS PDF Viewer". The TrueOS one is the second/older utility.

**Comment by q-pa** [comment]
But the resolution of the TrueOS viewer is much better as you can see. The Lumina PDF viewer only display sharp text when in presentation mode.
