### ISSUE TITLE
Lumina-fm crashes on multiple columns

### ISSUE THREAD

**Issue by ZackaryWelch** [trueos/lumina#526]
Lumina-fm confirmed to crash or hang up the entire system if there is a tab with two columns and one of the tabs has a multiple gigabytes of data in the directory. Might be due to multi-threading or a memory leak. Trying to reproduce reliably.

**Comment by q5sys** [comment]
When you get a chance, can you retest this on the system that you produced it on?  Ken and I did change some of the loading routines last time I was down in TN.  Not sure if that's fixed it or if I dont have the same conditions to reproduce it.
