### ISSUE TITLE
Feature request: Lumina-fm to remember chosen sort-by option

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#531]
Lumina-fm will always switch back to sort by name.

**Comment by q5sys** [comment]
Thanks for the request!  That should be something we can add without too much trouble.

**Comment by q5sys** [comment]
we've the ability to change this via the View Menu.  This will globally set a default, you are still able to change it within a single browser to whatever you may want at the time.

https://github.com/trueos/lumina/commit/a8cf372fe539a3a1d9b32424f8e92eb72a0a921d
