### ISSUE TITLE
[Feature request] enable xrandr so that it allows the usage of another screen without the mirroring

### ISSUE THREAD

**Issue by SolarAquarion** [trueos/lumina#533]

**Comment by q5sys** [comment]
I already though this was possible, so I'll kick this one over to Ken, since he's the one that's worked on the multi screen stuff.
Thanks for the request.

**Comment by SolarAquarion** [comment]
I had to explicitly type xrandr for some reason

**Comment by beanpole135** [comment]
xrandr should automatically allow both mirroring and individual screens.
`lumina-xconfig` is just a graphical front-end to xrandr, and should already do individual screens automatically (since mirrored screens are less-used in multi-monitor situations).
