### ISSUE TITLE
Hard to change wallpaper

### ISSUE THREAD

**Issue by outpaddling** [trueos/lumina#534]
I like the latest enhancements to Lumina, save one:

When changing the wallpaper, the file browser always defaults to $HOME.

I think it could do two things to improve on this:

1. Default to /usr/local/share/wallpapers if it exists
2. Remember the location of the last wallpaper loaded

Thanks for your continued work on this!

**Comment by q5sys** [comment]
Thanks for the bug/request.  Those seem like sane requests.  We'll talk it over and figure out how we want to move on this.

**Comment by beanpole135** [comment]
Fixed!
https://github.com/trueos/lumina/commit/e288a9d60e8325779690d5157cf47db66b156a71

**Comment by outpaddling** [comment]
Thanks!
