### ISSUE TITLE
Suspend button does not work

### ISSUE THREAD

**Issue by outpaddling** [trueos/lumina#535]
Since the latest update to the FreeBSD port, the suspend button now appears in the exit window, but it does not work.  It just locks the screen instead.
Suspend does work on my test machine ( a Thinkpad T61 ) via hw.acpi.lid_switch_state.
I'm running stock FreeBSD 11.1, fully updated.
Thanks,
    Jason

**Comment by q5sys** [comment]
Thanks for the report, we'll look into it.

**Comment by beanpole135** [comment]
You need to ensure that the `acpiconf` utility (/sbin/acpiconf) is setuid first (chmod 4555 /sbin/acpiconf).
That utility is what Lumina uses to issue the ACPI sleep request (and the utility that other FreeBSD "sleep" commands run in the background as well, such as the "zzz" command) and it needs root access to issue the signal to the base system.

The reason your lid switch state option works is that devd is running with root permissions already, so when it calls acpiconf it has access to do so - running it from the Lumina session (as a user) does not work without the setuid flag on the binary.

**Comment by outpaddling** [comment]
That works, thanks.
Note that the correct path is /usr/sbin/acpiconf.
One other question: Is it possible to prevent the sleep button from appearing through some config setting, for systems where the sleep function doesn't work properly?
