### ISSUE TITLE
Unstable TrueOS-Desktop-201712111405 Auto login doesn't work 

### ISSUE THREAD

**Issue by maurizio-emmex** [trueos/lumina#537]
![screenshot-2017-12-28-10-55-47](https://user-images.githubusercontent.com/10965847/34407304-efa40240-ebbd-11e7-9860-aec43e5009fd.png)
These settings are ignored and, at login, a password is required.

**Comment by beanpole135** [comment]
This was just fixed in the master branch of PCDM yesterday:
https://github.com/trueos/pcdm/commit/f5cba77be4ea265accd5a2ef848aecacb7d7522c

I will be backporting this update to TrueOS STABLE 17.12 here soon.

**Comment by maurizio-emmex** [comment]
Thank you. Sorry for the noise.
