### ISSUE TITLE
Qterminal non-functional in TrueOS under VirtualBox

### ISSUE THREAD

**Issue by outpaddling** [trueos/lumina#542]
FYI,
In the latest trueos-stable running under VirtualBox, qterminal opens up with no window border and cannot be closed properly.  Exiting the shell leaves a remnant of the borderless terminal window on the screen and I have not found a way to get rid of it short of logging out.  You can probably reproduce the issue outside VirtualBox by resizing the screen.  That was the case last time I saw window border issues.  FTR, they turned out to be a fluxbox issue.
I'd actually recommend ditching qtermina as the primary terminal appl, unless someone has time to fix the numerous regressions that have appeared since 0.6.0.  I'm the creator and former maintainer of the qterminal FreeBSD port, but I've given up on it as it has become more buggy and LXQT-centric since 0.6.0.  I've switched to Lilyterm on my stock FreeBSD/Lumina systems.  It's not QT-based, but dependencies are minimal and it's very functional.
I'd also urge the team to do thorough testing of TrueOS under VirtualBox before future releases, as many new users will have their first experience with it as a VM guest.  Inability to use the provided terminal application would give new users a very bad first impression and I suspect that many will not give TrueOS a second chance.

**Comment by RodMyers** [comment]
read https://github.com/trueos/lumina/issues/460

reopen if @beanpole135 suggestion does not work

**Comment by pkgdemon** [comment]
@outpaddling The issue you describe where qterminal appears without a border happens on real systems as well upon the first login when a new display is attached.  Second login seems to fix, and it does appear to be a fluxbox issue.

I agree with your feedback, and will bring this up in our next meeting.  I too have noticed issues with qterminal beginning with cut, and paste which has been frustrating me for some time.  It's good to know you were the maintainer, and it sounds like this port might not have a bright future.  Appreciate the heads up!

**Comment by outpaddling** [comment]
Well, if someone who likes QT development has the time and interest, qterminal should not be too far gone to clean up.  That's not me, though.
On the other note, I've been dabbling with PC-BSD/TrueOS for many years.  It's a great idea and a pretty solid implementation, but I've noticed a pattern of high-visibility bugs over the years (this qterminal issue, confusing behavior with the update system, ...)  I think shifting a few man-hours from new development to tying up loose ends is all it needs to become rock-solid and get rave reviews from everyone who tries it.
