### ISSUE TITLE
[Feature request]Enable to set the parcentage of lumina-open -volume[up/down] 

### ISSUE THREAD

**Issue by boronology** [trueos/lumina#545]
Hello.

Now lumina-open -volume[up/down] changes the volume constantly 5%, and the default shortcut key Alt+Page[up/down] calls this command.
But 5% is too large for my environment, so I would like to change the volume less than 5% , like "lumina-open -volumeup 2".

I tried implementing and upload to my repository.
How about this?
https://github.com/boronology/lumina/blob/feature/volume/src-qt5/core/lumina-open/main.cpp

Thanks.(and sorry for my poor English)

**Comment by q5sys** [comment]
would you mind doing a pull request on this?

**Comment by jwvdveen** [comment]
I'm not sure I'm your man on this one. This request isn't mine.

If I can help, I will. I only have to figure out how things are done through git.

Regards,
Jan-Willem

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________
