### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [trueos/lumina#550]
mainUI.cpp: In member function ‘void MainUI::loadPage(int, fz_document*, MainUI*, QSize)’:
mainUI.cpp:287:69: warning: unused parameter ‘dpi’ [-Wunused-parameter]
 void MainUI::loadPage(int num, fz_document *doc, MainUI *obj, QSize dpi){
                                                                     ^~~
mainUI.cpp: In member function ‘void MainUI::find(QString, bool)’:
mainUI.cpp:660:13: error: ‘fz_stext_sheet’ was not declared in this scope
             fz_stext_sheet *sheet = fz_new_stext_sheet(CTX);
             ^~~~~~~~~~~~~~
mainUI.cpp:660:13: note: suggested alternative: ‘fz_stext_page’
             fz_stext_sheet *sheet = fz_new_stext_sheet(CTX);
             ^~~~~~~~~~~~~~
             fz_stext_page
mainUI.cpp:660:29: error: ‘sheet’ was not declared in this scope
             fz_stext_sheet *sheet = fz_new_stext_sheet(CTX);
                             ^~~~~
mainUI.cpp:660:29: note: suggested alternative: ‘short’
             fz_stext_sheet *sheet = fz_new_stext_sheet(CTX);
                             ^~~~~
                             short
mainUI.cpp:660:37: error: ‘fz_new_stext_sheet’ was not declared in this scope
             fz_stext_sheet *sheet = fz_new_stext_sheet(CTX);
                                     ^~~~~~~~~~~~~~~~~~
mainUI.cpp:660:37: note: suggested alternative: ‘fz_new_stext_page’
             fz_stext_sheet *sheet = fz_new_stext_sheet(CTX);
                                     ^~~~~~~~~~~~~~~~~~
                                     fz_new_stext_page
mainUI.cpp:662:84: error: could not convert ‘rectBuffer[j]’ from ‘fz_rect {aka fz_rect_s}’ to ‘fz_point {aka fz_point_s}’
             QString currentStr = QString(fz_copy_selection(CTX, sPage, rectBuffer[j]));
                                                                        ~~~~~~~~~~~~^
make[3]: *** [Makefile:1310: .build/obj/mainUI.o] Error 1
make[3]: Leaving directory '/home/solaraquarion/build/lumina-desktop-git/src/lumina/src-qt5/desktop-utils/lumina-pdf'
make[2]: *** [Makefile:227: sub-lumina-pdf-make_first] Error 2
make[2]: Leaving directory '/home/solaraquarion/build/lumina-desktop-git/src/lumina/src-qt5/desktop-utils'
make[1]: *** [Makefile:97: sub-desktop-utils-make_first] Error 2
make[1]: Leaving directory '/home/solaraquarion/build/lumina-desktop-git/src/lumina/src-qt5'
make: *** [Makefile:45: sub-src-qt5-make_first] Error 2

**Comment by ZackaryWelch** [comment]
This is related to the changes in lumina-pdf with the inclusion of the MuPDF library. It seems like you have a different version of MuPDF installed. I am currently using mupdf 1.11_2. Do you know what version you have instead? Try "cat /usr/local/share/doc/mupdf/CHANGES".

**Comment by SolarAquarion** [comment]
I have 1.12

**Comment by ZackaryWelch** [comment]
Yeah, that would be the issue. I'll update lumina-pdf to use 1.12 once I get mupdf to build. It's a shame that each version of mupdf breaks code for fairly minor reasons.

**Comment by beanpole135** [comment]
Fixed!
