### ISSUE TITLE
Feature Request: Add a "rotate" or "change orientation" button in lumina-pdf

### ISSUE THREAD

**Issue by SawFishDaemon** [trueos/lumina#551]
Sometimes we get PDF files that are upside down or sideways. They are difficult to read, but usualy easily solved by rotating the PDF image. As of right now there is no way of changing the orientation of a PDF image within lumina-pdf. This would be a very nice feautre to have. Thank you.

**Comment by beanpole135** [comment]
This has already been implemented in the version of lumina-pdf in source (currently 1.4.2).
