### ISSUE TITLE
[feature request] lumina-fm: bypassing confirmation dialogue at delete

### ISSUE THREAD

**Issue by rostwald** [trueos/lumina#556]
IMHO a major annoyance with the filemanager is the constantly appearing confirmation dialogue when deleting files/directories.

It would be extremely helpful to either add an option like "never show this again" or (maybe the safer solution regarding inexperienced users), to bypass it by using "shift+del" to delete. Accidental deletes might still be catched, but accidentally pressing shift + del is rather unlikely.

**Comment by q5sys** [comment]
idk how I feel about changing the function of the delete key.  The delete key deleting files is common expected behavior in just about every OS I know of.
We could probably put in an override so it doesn't ask every time.  I'll have to bring that up with Ken and see how he wants to handle that.

**Comment by beanpole135** [comment]
Done!
https://github.com/trueos/lumina/commit/f71b705ac5e676f0d1f2c1fa75c7bd789d59ceec

**Comment by rostwald** [comment]
@q5sys:
> idk how I feel about changing the function of the delete key. The delete key deleting files is common expected behavior in just about every OS I know of.

Therefore I was suggesting the "shift+del" combination for "delete immediately without asking" - this behavior can be found in many Filemanagers (even the Windows Explorer). Using only the delete key would still trigger the confirmation dialogue.

@beanpole135: wow, that was quick! thanks!
